"use client";

import { useState } from "react";
import Link from "next/link";

type Tab = "html" | "css" | "js";
type EpistemeStatus = "idle" | "thinking" | "ready" | "blocked";

const EPISTEME_STEPS = [
  "Intent analysis",
  "Architecture planning",
  "Safety review",
  "Code generation",
  "Output preparation",
];

const BLOCKED_PATTERNS = [
  /document\.cookie/i,
  /localStorage/i,
  /sessionStorage/i,
  /indexedDB/i,
  /eval\s*\(/i,
  /new Function/i,
  /fetch\s*\(/i,
  /XMLHttpRequest/i,
  /navigator\.sendBeacon/i,
  /window\.open/i,
  /location\.href/i,
  /<script[^>]+src=/i,
  /<iframe/i,
  /<form/i,
  /onerror\s*=/i,
  /onload\s*=/i,
  /onclick\s*=/i,
];

function clean(input: string) {
  return input.trim() || "Create a premium civilization interface";
}

function escapeHtml(input: string) {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function validateGeneratedCode(input: string) {
  const issues = BLOCKED_PATTERNS.filter((pattern) =>
    pattern.test(input)
  ).map((pattern) => `Blocked pattern: ${pattern}`);

  return {
    safe: issues.length === 0,
    issues,
  };
}

function makeHtml(prompt: string) {
  const title = escapeHtml(clean(prompt));

  return `<main class="runtime">
  <section class="hero">
    <div class="label">GENERATED BY ARCHENOVA BUILDER</div>
    <h1>${title}</h1>
    <p>
      Generated through a safe Prompt → Episteme → Code workflow.
    </p>
  </section>

  <section class="grid">
    <article class="card">
      <span>01</span>
      <h2>Prompt</h2>
      <p>Transform intent into a structured build direction.</p>
    </article>

    <article class="card">
      <span>02</span>
      <h2>Episteme</h2>
      <p>Analyze, plan, review safety, and generate code.</p>
    </article>

    <article class="card">
      <span>03</span>
      <h2>Code</h2>
      <p>Produce editable HTML, CSS, and JavaScript.</p>
    </article>
  </section>
</main>`;
}

function makeCss() {
  return `body {
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at 20% 0%, rgba(120, 200, 255, 0.24), transparent 34%),
    radial-gradient(circle at 80% 20%, rgba(210, 160, 255, 0.18), transparent 34%),
    #05070d;
  color: white;
  font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
  display: grid;
  place-items: center;
  padding: 28px;
}

.runtime {
  width: min(100%, 980px);
}

.hero {
  padding: 44px;
  border-radius: 32px;
  background: rgba(255,255,255,0.06);
  border: 1px solid rgba(255,255,255,0.12);
  box-shadow: 0 0 90px rgba(120,180,255,0.14);
}

.label {
  font-size: 12px;
  letter-spacing: .18em;
  opacity: .72;
  margin-bottom: 18px;
}

h1 {
  margin: 0 0 18px;
  font-size: clamp(38px, 8vw, 86px);
  line-height: .92;
  letter-spacing: -0.06em;
  background: linear-gradient(90deg, #fff, #8bd0ff, #d0a8ff, #ffe4a3);
  -webkit-background-clip: text;
  color: transparent;
}

p {
  line-height: 1.8;
  opacity: .8;
  max-width: 760px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 16px;
  margin-top: 18px;
}

.card {
  padding: 24px;
  border-radius: 24px;
  background: rgba(255,255,255,0.055);
  border: 1px solid rgba(255,255,255,0.1);
}

.card span {
  font-size: 12px;
  opacity: .6;
}

.card h2 {
  margin: 14px 0 8px;
}

@media (max-width: 720px) {
  body {
    padding: 18px;
  }

  .hero {
    padding: 28px;
  }

  .grid {
    grid-template-columns: 1fr;
  }
}`;
}

function makeJs() {
  return `const cards = document.querySelectorAll(".card");

cards.forEach((card) => {
  card.addEventListener("mouseenter", () => {
    card.style.transform = "translateY(-4px)";
    card.style.transition = "transform 240ms ease";
  });

  card.addEventListener("mouseleave", () => {
    card.style.transform = "translateY(0)";
  });
});`;
}

export default function ArcheNovaBuilderPage() {
  const [prompt, setPrompt] = useState("");
  const [html, setHtml] = useState(makeHtml(""));
  const [css, setCss] = useState(makeCss());
  const [js, setJs] = useState(makeJs());
  const [tab, setTab] = useState<Tab>("html");
  const [status, setStatus] = useState<EpistemeStatus>("idle");
  const [phase, setPhase] = useState(0);
  const [copied, setCopied] = useState("");
  const [safetyIssues, setSafetyIssues] = useState<string[]>([]);

  const currentCode = tab === "html" ? html : tab === "css" ? css : js;

  function setCurrentCode(value: string) {
    if (tab === "html") setHtml(value);
    if (tab === "css") setCss(value);
    if (tab === "js") setJs(value);
  }

  async function generate() {
    setStatus("thinking");
    setCopied("");
    setSafetyIssues([]);
    setPhase(0);

    for (let i = 0; i < EPISTEME_STEPS.length; i += 1) {
      setPhase(i);
      await new Promise((resolve) => setTimeout(resolve, 240));
    }

    const nextHtml = makeHtml(prompt);
    const nextCss = makeCss();
    const nextJs = makeJs();

    const safety = validateGeneratedCode(
      `${nextHtml}\n${nextCss}\n${nextJs}`
    );

    if (!safety.safe) {
      setSafetyIssues(safety.issues);
      setStatus("blocked");
      setPhase(EPISTEME_STEPS.length);
      return;
    }

    setHtml(nextHtml);
    setCss(nextCss);
    setJs(nextJs);
    setPhase(EPISTEME_STEPS.length);
    setStatus("ready");
  }

  function reset() {
    setPrompt("");
    setHtml(makeHtml(""));
    setCss(makeCss());
    setJs(makeJs());
    setTab("html");
    setStatus("idle");
    setPhase(0);
    setCopied("");
    setSafetyIssues([]);
  }

  async function copy(value: string, label: string) {
    await navigator.clipboard.writeText(value);
    setCopied(label);
  }

  return (
    <main className="page-standard builder-cosmos-page">
      <div className="page-head">
        <span className="home-section-label">ARCHENOVA BUILDER</span>

        <h1>Prompt. Episteme. Code.</h1>

        <p className="page-lead">
          A simple public Builder interface powered by ArcheNova&apos;s
          safety-first generation logic.
        </p>
      </div>

      <section className="glass-block builder-simple-flow">
        <div className="builder-simple-step">
          <span className="home-section-label">PROMPT</span>

          <h2>What would you like to build?</h2>

          <textarea
            value={prompt}
            onChange={(event) => setPrompt(event.target.value)}
            placeholder="Example: Create a premium dashboard for a civilization intelligence platform..."
            className="builder-input"
          />

          <div className="builder-actions">
            <button type="button" onClick={generate} className="back-link">
              Generate →
            </button>

            <button type="button" onClick={reset} className="back-link">
              Reset
            </button>
          </div>
        </div>

        <div className="builder-simple-step">
          <span className="home-section-label">EPISTEME</span>

          <h2>Generation Engine</h2>

          <div className="builder-thinking-list">
            {EPISTEME_STEPS.map((step, index) => (
              <div
                key={step}
                className={`builder-thinking-step ${
                  index < phase
                    ? "done"
                    : status === "thinking" && index === phase
                    ? "active"
                    : "pending"
                }`}
              >
                <span />
                <p>{step}</p>
              </div>
            ))}
          </div>

          <p className="plaza-hint">
            {status === "idle"
              ? "Waiting for prompt."
              : status === "thinking"
              ? "Generating..."
              : status === "blocked"
              ? "Blocked by safety filter."
              : "Generated."}
          </p>
        </div>
      </section>

      {safetyIssues.length > 0 && (
        <section className="glass-block">
          <span className="home-section-label">SAFETY FILTER</span>

          <h2>Output blocked.</h2>

          <div className="feed-list">
            {safetyIssues.map((issue) => (
              <div key={issue} className="feed-row wide">
                <div className="feed-source">Blocked</div>
                <div className="feed-title">{issue}</div>
              </div>
            ))}
          </div>
        </section>
      )}

      <section className="glass-block builder-code-section">
        <span className="home-section-label">CODE</span>

        <h2>Editable Output</h2>

        <div className="builder-tabs">
          {(["html", "css", "js"] as Tab[]).map((item) => (
            <button
              key={item}
              type="button"
              onClick={() => setTab(item)}
              className={`builder-tab ${tab === item ? "active" : ""}`}
            >
              {item.toUpperCase()}
            </button>
          ))}
        </div>

        <textarea
          value={currentCode}
          onChange={(event) => setCurrentCode(event.target.value)}
          spellCheck={false}
          className="builder-code"
        />

        <div className="builder-actions">
          <button
            type="button"
            onClick={() => copy(currentCode, tab.toUpperCase())}
            className="back-link"
          >
            Copy {tab.toUpperCase()}
          </button>

          {copied && <span className="plaza-hint">Copied {copied}</span>}
        </div>
      </section>

      <section className="glass-block">
        <h2>Builder Principle</h2>

        <p>
          Builder keeps the interface simple while preserving a safety-first
          generation workflow. Live Preview is intentionally disabled.
        </p>
      </section>

      <div className="page-foot">
        <Link href="/home" className="back-link">
          ← Back to Home
        </Link>
      </div>
    </main>
  );
}