"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

function clean(input: string) {
  return input.trim() || "Build an ArcheNova interface";
}

function escapeHtml(input: string) {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function makeReactCode(prompt: string) {
  const title = clean(prompt);

  return `export default function GeneratedArcheNovaRuntime() {
  return (
    <main className="page-standard">
      <section className="glass-block">
        <span className="home-section-label">
          GENERATED BY ARCHENOVA BUILDER
        </span>

        <h1>${title}</h1>

        <p className="page-lead">
          This interface was generated from intent through ArcheNova Builder.
        </p>

        <div className="research-report-grid">
          <div className="research-report-card">
            <h3>Intent</h3>
            <p>Transform idea into structure.</p>
          </div>

          <div className="research-report-card">
            <h3>System</h3>
            <p>Convert structure into implementation.</p>
          </div>

          <div className="research-report-card">
            <h3>Reality</h3>
            <p>Preview, refine, and deploy.</p>
          </div>
        </div>
      </section>
    </main>
  );
}`;
}

function makePreviewHtml(prompt: string) {
  const title = escapeHtml(clean(prompt));

  return `
<html>
<head>
<style>
  body {
    margin: 0;
    min-height: 100vh;
    background:
      radial-gradient(circle at 20% 0%, rgba(120, 200, 255, 0.2), transparent 35%),
      radial-gradient(circle at 80% 20%, rgba(210, 160, 255, 0.18), transparent 35%),
      #05070d;
    color: white;
    font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
    display: grid;
    place-items: center;
    padding: 28px;
  }

  .runtime {
    max-width: 920px;
    width: 100%;
    padding: 42px;
    border-radius: 30px;
    background: rgba(255,255,255,0.06);
    border: 1px solid rgba(255,255,255,0.12);
    box-shadow: 0 0 80px rgba(120,180,255,0.14);
  }

  .label {
    font-size: 12px;
    letter-spacing: .18em;
    opacity: .72;
    margin-bottom: 18px;
  }

  h1 {
    margin: 0 0 18px;
    font-size: clamp(36px, 8vw, 82px);
    line-height: .95;
    background: linear-gradient(90deg, #fff, #8bd0ff, #d0a8ff, #ffe4a3);
    -webkit-background-clip: text;
    color: transparent;
  }

  p {
    line-height: 1.8;
    opacity: .82;
    max-width: 760px;
  }

  .grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 16px;
    margin-top: 28px;
  }

  .card {
    padding: 22px;
    border-radius: 22px;
    background: rgba(255,255,255,0.055);
    border: 1px solid rgba(255,255,255,0.1);
  }

  .card h3 {
    margin: 0 0 10px;
  }

  @media (max-width: 720px) {
    .grid {
      grid-template-columns: 1fr;
    }
  }
</style>
</head>

<body>
  <section class="runtime">
    <div class="label">GENERATED BY ARCHENOVA BUILDER</div>
    <h1>${title}</h1>
    <p>
      This preview represents how the generated React structure could appear
      as an interface. Refine the prompt, regenerate, then copy the React code.
    </p>

    <div class="grid">
      <div class="card">
        <h3>Intent</h3>
        <p>Transform idea into structure.</p>
      </div>

      <div class="card">
        <h3>System</h3>
        <p>Convert structure into implementation.</p>
      </div>

      <div class="card">
        <h3>Reality</h3>
        <p>Preview, refine, and deploy.</p>
      </div>
    </div>
  </section>
</body>
</html>`;
}

function makeAgentAdvice(prompt: string) {
  const text = prompt.toLowerCase();

  if (!prompt.trim()) {
    return "Enter a prompt. Example: Create a premium dashboard for ArcheNova Intelligence Platform.";
  }

  if (text.includes("dashboard")) {
    return "Agent: Use a hero summary, metric cards, signal list, and decision section. Dashboard outputs should prioritize clarity and hierarchy.";
  }

  if (text.includes("landing") || text.includes("home")) {
    return "Agent: Use a strong hero, concise mission, visual product cards, and a clear action path.";
  }

  if (text.includes("system") || text.includes("architecture")) {
    return "Agent: Separate the design into input, intelligence, generation, execution, and feedback layers.";
  }

  return "Agent: Good prompt. Next, refine the desired user, purpose, page type, and final action.";
}

export default function ArcheNovaBuilderPage() {
  const [prompt, setPrompt] = useState("");
  const [reactCode, setReactCode] = useState(makeReactCode(""));
  const [previewHtml, setPreviewHtml] = useState(makePreviewHtml(""));
  const [copied, setCopied] = useState(false);

  const agentAdvice = useMemo(() => makeAgentAdvice(prompt), [prompt]);

  function generateRuntime() {
    setReactCode(makeReactCode(prompt));
    setPreviewHtml(makePreviewHtml(prompt));
    setCopied(false);
  }

  async function copyCode() {
    await navigator.clipboard.writeText(reactCode);
    setCopied(true);
  }

  return (
    <main className="page-standard builder-cosmos-page">
      <div className="page-head">
        <span className="home-section-label">
          ARCHENOVA BUILDER
        </span>

        <h1>Builder Runtime</h1>

        <p className="page-lead">
          Write a prompt, generate React code, preview the interface, and use
          the agent as an implementation partner.
        </p>
      </div>

      <section className="glass-block">
        <h2>Mission</h2>

        <p>
          Episteme reasons. Builder executes. This workspace transforms intent
          into React structure, visual preview, and implementation guidance.
        </p>
      </section>

      <section className="glass-block">
        <h2>Prompt</h2>

        <textarea
          value={prompt}
          onChange={(event) => setPrompt(event.target.value)}
          placeholder="Example: Create a premium dashboard for ArcheNova Intelligence Platform..."
          style={{
            width: "100%",
            minHeight: "140px",
            padding: "1rem",
            borderRadius: "18px",
            border: "1px solid rgba(255,255,255,0.12)",
            background: "rgba(255,255,255,0.04)",
            color: "inherit",
            lineHeight: 1.7,
          }}
        />

        <button
          type="button"
          onClick={generateRuntime}
          className="back-link"
          style={{ marginTop: "1rem" }}
        >
          Generate Runtime →
        </button>
      </section>

      <section className="glass-block">
        <h2>Workspace</h2>

        <div style={{ display: "grid", gap: "1rem" }}>
          <div>
            <div className="home-card-meta">Generated React Code</div>

            <textarea
              value={reactCode}
              onChange={(event) => setReactCode(event.target.value)}
              spellCheck={false}
              style={{
                width: "100%",
                minHeight: "360px",
                marginTop: "0.75rem",
                padding: "1rem",
                borderRadius: "18px",
                border: "1px solid rgba(255,255,255,0.12)",
                background: "rgba(0,0,0,0.38)",
                color: "inherit",
                fontFamily:
                  "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
                lineHeight: 1.7,
              }}
            />

            <button
              type="button"
              onClick={copyCode}
              className="back-link"
              style={{ marginTop: "1rem" }}
            >
              {copied ? "Copied" : "Copy React Code"}
            </button>
          </div>

          <div>
            <div className="home-card-meta">Live Preview</div>

            <iframe
              title="ArcheNova Builder Runtime Preview"
              srcDoc={previewHtml}
              sandbox=""
              style={{
                width: "100%",
                minHeight: "460px",
                marginTop: "0.75rem",
                borderRadius: "22px",
                border: "1px solid rgba(255,255,255,0.12)",
                background: "rgba(0,0,0,0.35)",
              }}
            />
          </div>

          <div className="feed-row wide">
            <div className="feed-source">Builder Agent</div>
            <div className="feed-title">Implementation Guidance</div>
            <div className="feed-summary">{agentAdvice}</div>
          </div>
        </div>
      </section>

      <div className="page-foot">
        <Link href="/home" className="back-link">
          ← Back to Home
        </Link>
      </div>
    </main>
  );
}