"use client";

import {
  useMemo,
  useState,
} from "react";


/* ==========================================================
   TYPES
========================================================== */

type SelectedPaper = {
  title: string;
  source: string;
  url: string;
  summary: string;
  publishedAt: string;
};


type SimulationHypothesis = {
  id: string;
  label: string;
  title: string;
  statement: string;
};


type SimulationPrediction = {
  id: string;
  label: string;
  statement: string;
};


type ExperimentOption = {
  id: string;
  label: string;
  title: string;
  description: string;
};


type SimulatedExperimentResult = {
  status:
    | "CONSISTENT"
    | "AMBIGUOUS"
    | "CHALLENGED";

  observation: string;

  interpretation: string;

  discriminationStrength:
    | "LOW"
    | "MODERATE"
    | "HIGH";

  caveat: string;
};


type FalsificationOption = {
  id: string;
  label: string;
  title: string;
  description: string;
};


type RevisionDecision =
  | "RETAIN"
  | "WEAKEN"
  | "REPLACE"
  | "UNRESOLVED";


type RevisionOption = {
  id: RevisionDecision;
  label: string;
  title: string;
  description: string;
  implication: string;
};


type EngineeringOption = {
  id: string;
  label: string;
  title: string;
  description: string;
};


type CivilizationScientificSimulationProps = {
  paper: SelectedPaper;
};


type ActiveStage =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8;


/* ==========================================================
   THEORY SPACE
========================================================== */

function buildHypotheses(
  paper: SelectedPaper,
): SimulationHypothesis[] {
  return [
    {
      id: "h1",

      label:
        "HYPOTHESIS A",

      title:
        "Direct causal mechanism",

      statement:
        `The observation reported in "${paper.title}" is primarily generated by the mechanism proposed or implied by the current scientific interpretation.`,
    },

    {
      id: "h2",

      label:
        "HYPOTHESIS B",

      title:
        "Hidden-variable mechanism",

      statement:
        "The reported observation is real, but an unmeasured physical, environmental, structural, or causal variable accounts for part or all of the observed effect.",
    },

    {
      id: "h3",

      label:
        "HYPOTHESIS C",

      title:
        "Boundary-condition dependence",

      statement:
        "The observed effect depends strongly on preparation history, geometry, environment, operating regime, or another boundary condition rather than representing a universal mechanism.",
    },

    {
      id: "h4",

      label:
        "HYPOTHESIS D",

      title:
        "Measurement or inference artifact",

      statement:
        "The apparent effect may partly arise from calibration, reconstruction assumptions, statistical inference, finite resolution, or another measurement artifact.",
    },
  ];
}


/* ==========================================================
   PREDICTION SPACE
========================================================== */

function buildPredictions(
  hypothesisId:
    string |
    null,
): SimulationPrediction[] {
  switch (
    hypothesisId
  ) {
    case "h1":
      return [
        {
          id: "p1",

          label:
            "PREDICTION A",

          statement:
            "The effect should reproduce when the proposed causal variable is independently controlled under comparable conditions.",
        },

        {
          id: "p2",

          label:
            "PREDICTION B",

          statement:
            "Removing or reversing the proposed causal variable should systematically weaken, eliminate, or reverse the observed effect.",
        },

        {
          id: "p3",

          label:
            "PREDICTION C",

          statement:
            "The effect should remain detectable through at least one independent measurement modality.",
        },
      ];


    case "h2":
      return [
        {
          id: "p1",

          label:
            "PREDICTION A",

          statement:
            "The apparent primary relationship should weaken when additional latent or environmental variables are controlled.",
        },

        {
          id: "p2",

          label:
            "PREDICTION B",

          statement:
            "A previously unmeasured variable should explain a reproducible fraction of the observed effect.",
        },

        {
          id: "p3",

          label:
            "PREDICTION C",

          statement:
            "The original interpretation should become less stable as experimental context changes.",
        },
      ];


    case "h3":
      return [
        {
          id: "p1",

          label:
            "PREDICTION A",

          statement:
            "Changing preparation history or environmental conditions should materially alter the observed result.",
        },

        {
          id: "p2",

          label:
            "PREDICTION B",

          statement:
            "The phenomenon should occupy only a restricted region of the accessible parameter space.",
        },

        {
          id: "p3",

          label:
            "PREDICTION C",

          statement:
            "The effect should weaken or disappear outside the reported boundary conditions.",
        },
      ];


    case "h4":
      return [
        {
          id: "p1",

          label:
            "PREDICTION A",

          statement:
            "An independent apparatus or analysis pipeline should produce a weaker or materially different effect.",
        },

        {
          id: "p2",

          label:
            "PREDICTION B",

          statement:
            "Changing calibration or inference assumptions should significantly change the apparent result.",
        },

        {
          id: "p3",

          label:
            "PREDICTION C",

          statement:
            "The effect should fail to reproduce under blinded or independently reconstructed analysis.",
        },
      ];


    default:
      return [];
  }
}


/* ==========================================================
   EXPERIMENT SPACE
========================================================== */

const INTERVENTIONS:
  ExperimentOption[] = [
    {
      id: "i1",

      label:
        "INTERVENTION A",

      title:
        "Control the proposed causal variable",

      description:
        "Directly vary the variable most closely associated with the current working hypothesis.",
    },

    {
      id: "i2",

      label:
        "INTERVENTION B",

      title:
        "Reverse or remove the causal condition",

      description:
        "Reduce, reverse, or eliminate the suspected causal input and observe whether the effect follows.",
    },

    {
      id: "i3",

      label:
        "INTERVENTION C",

      title:
        "Alter boundary conditions",

      description:
        "Change preparation, environment, geometry, timing, or another contextual constraint.",
    },

    {
      id: "i4",

      label:
        "INTERVENTION D",

      title:
        "Hold the system constant",

      description:
        "Avoid direct intervention and instead strengthen observational discrimination across repeated measurements.",
    },
  ];


const MEASUREMENTS:
  ExperimentOption[] = [
    {
      id: "m1",

      label:
        "MEASUREMENT A",

      title:
        "Primary measurement channel",

      description:
        "Repeat the principal type of observation used to detect the reported effect.",
    },

    {
      id: "m2",

      label:
        "MEASUREMENT B",

      title:
        "Independent measurement modality",

      description:
        "Observe the same predicted consequence through a physically or methodologically distinct channel.",
    },

    {
      id: "m3",

      label:
        "MEASUREMENT C",

      title:
        "Time-resolved measurement",

      description:
        "Measure how the phenomenon emerges, evolves, relaxes, or disappears over time.",
    },

    {
      id: "m4",

      label:
        "MEASUREMENT D",

      title:
        "Parameter-space mapping",

      description:
        "Map the effect across multiple operating conditions rather than testing a single point.",
    },
  ];


const CONTROLS:
  ExperimentOption[] = [
    {
      id: "c1",

      label:
        "CONTROL A",

      title:
        "Negative control",

      description:
        "Repeat the experiment under conditions where the proposed mechanism should not produce the effect.",
    },

    {
      id: "c2",

      label:
        "CONTROL B",

      title:
        "Independent replication",

      description:
        "Require reconstruction by a separate apparatus, pipeline, or experimental team.",
    },

    {
      id: "c3",

      label:
        "CONTROL C",

      title:
        "Blinded reconstruction",

      description:
        "Separate data generation from interpretation to reduce confirmation and analysis bias.",
    },

    {
      id: "c4",

      label:
        "CONTROL D",

      title:
        "Competing-model control",

      description:
        "Design the experiment so that at least one credible alternative explanation predicts a different outcome.",
    },
  ];


/* ==========================================================
   SIMULATED REALITY
========================================================== */

function simulateExperiment(
  hypothesisId: string,
  predictionId: string,
  interventionId: string,
  measurementId: string,
  controlId: string,
): SimulatedExperimentResult {
  let discriminationScore =
    0;


  if (
    interventionId ===
      "i2" ||
    interventionId ===
      "i3"
  ) {
    discriminationScore +=
      2;
  }


  if (
    measurementId ===
      "m2" ||
    measurementId ===
      "m4"
  ) {
    discriminationScore +=
      2;
  }


  if (
    controlId ===
      "c2" ||
    controlId ===
      "c4"
  ) {
    discriminationScore +=
      2;
  }


  const seed =
    hypothesisId.charCodeAt(
      hypothesisId.length -
        1,
    ) +
    predictionId.charCodeAt(
      predictionId.length -
        1,
    ) +
    interventionId.charCodeAt(
      interventionId.length -
        1,
    ) +
    measurementId.charCodeAt(
      measurementId.length -
        1,
    ) +
    controlId.charCodeAt(
      controlId.length -
        1,
    );


  const mode =
    seed % 3;


  const strength:
    SimulatedExperimentResult["discriminationStrength"] =
      discriminationScore >=
      5
        ? "HIGH"
        : discriminationScore >=
            3
          ? "MODERATE"
          : "LOW";


  if (
    mode === 0
  ) {
    return {
      status:
        "CONSISTENT",

      observation:
        "The simulated observable changes in the direction expected by the locked prediction and remains detectable under the selected measurement and control structure.",

      interpretation:
        "The result is consistent with the working hypothesis, but consistency does not uniquely identify the mechanism. Credible alternatives may still reproduce the same observation.",

      discriminationStrength:
        strength,

      caveat:
        "This is a synthetic experimental outcome generated by the ArcheNova simulation architecture. It is not a claim about the source paper's actual reported data.",
    };
  }


  if (
    mode === 1
  ) {
    return {
      status:
        "AMBIGUOUS",

      observation:
        "The simulated effect remains detectable, but its magnitude and stability change under the selected intervention or measurement conditions.",

      interpretation:
        "Reality does not cleanly discriminate the working hypothesis from competing explanations under this experimental design. A stronger intervention or independent measurement is required.",

      discriminationStrength:
        strength,

      caveat:
        "This is a synthetic experimental outcome generated for scientific-reasoning simulation, not a reconstruction of the source paper's experimental result.",
    };
  }


  return {
    status:
      "CHALLENGED",

    observation:
      "The simulated observable fails to reproduce the locked prediction consistently once the selected control or intervention is applied.",

    interpretation:
      "The working hypothesis is challenged under the current simulated conditions. The appropriate response is revision or stronger discrimination, not preservation of the preferred explanation.",

    discriminationStrength:
      strength,

    caveat:
      "This synthetic result demonstrates falsification logic only. It must not be interpreted as evidence that the source paper is incorrect.",
  };
}


/* ==========================================================
   FALSIFICATION SPACE
========================================================== */

const FALSIFICATION_OPTIONS:
  FalsificationOption[] = [
    {
      id: "f1",

      label:
        "FALSIFICATION A",

      title:
        "Independent replication",

      description:
        "Repeat the decisive test with independently constructed apparatus, calibration, and analysis.",
    },

    {
      id: "f2",

      label:
        "FALSIFICATION B",

      title:
        "Reverse the intervention",

      description:
        "Reverse the suspected causal manipulation and test whether the observable follows the predicted direction.",
    },

    {
      id: "f3",

      label:
        "FALSIFICATION C",

      title:
        "Change measurement modality",

      description:
        "Demand the same causal consequence through an independent physical or methodological measurement channel.",
    },

    {
      id: "f4",

      label:
        "FALSIFICATION D",

      title:
        "Remove the proposed mechanism",

      description:
        "Construct conditions in which the proposed causal mechanism is absent while competing explanations remain possible.",
    },

    {
      id: "f5",

      label:
        "FALSIFICATION E",

      title:
        "Expand parameter space",

      description:
        "Test whether the explanation survives beyond the narrow regime in which the original effect was observed.",
    },
  ];


/* ==========================================================
   REVISION SPACE
========================================================== */

const REVISION_OPTIONS:
  RevisionOption[] = [
    {
      id:
        "RETAIN",

      label:
        "REVISION A",

      title:
        "Retain the model",

      description:
        "The working hypothesis remains the strongest surviving explanation under the evidence generated so far.",

      implication:
        "Retain provisionally. Stronger future tests must remain capable of overturning it.",
    },

    {
      id:
        "WEAKEN",

      label:
        "REVISION B",

      title:
        "Weaken the model",

      description:
        "The hypothesis retains explanatory value, but its scope, confidence, or claimed generality should be reduced.",

      implication:
        "Restrict the model to the region of evidence it actually survives.",
    },

    {
      id:
        "REPLACE",

      label:
        "REVISION C",

      title:
        "Replace the model",

      description:
        "The present explanation no longer adequately survives the experimental or falsification structure.",

      implication:
        "Return to theory space and construct a competing explanation with different testable consequences.",
    },

    {
      id:
        "UNRESOLVED",

      label:
        "REVISION D",

      title:
        "Remain unresolved",

      description:
        "Current evidence cannot discriminate strongly enough between the working hypothesis and credible alternatives.",

      implication:
        "Preserve uncertainty rather than forcing a conclusion unsupported by the experiment.",
    },
  ];


/* ==========================================================
   ENGINEERING SPACE
========================================================== */

const FUNCTIONAL_TARGETS:
  EngineeringOption[] = [
    {
      id: "ft1",

      label:
        "TARGET A",

      title:
        "Measurement capability",

      description:
        "Convert the surviving scientific relation into a more sensitive, reliable, or discriminating sensing capability.",
    },

    {
      id: "ft2",

      label:
        "TARGET B",

      title:
        "Controlled physical function",

      description:
        "Use the surviving relation to deliberately generate, suppress, stabilize, or transform a measurable physical state.",
    },

    {
      id: "ft3",

      label:
        "TARGET C",

      title:
        "Computational capability",

      description:
        "Translate the physical relation into information processing, simulation, prediction, or control capability.",
    },

    {
      id: "ft4",

      label:
        "TARGET D",

      title:
        "Infrastructure capability",

      description:
        "Use the validated relation as part of a repeatable system capable of operating beyond a laboratory demonstration.",
    },
  ];


const CONTROL_VARIABLES:
  EngineeringOption[] = [
    {
      id: "cv1",

      label:
        "CONTROL A",

      title:
        "Primary causal variable",

      description:
        "Engineer direct control over the variable most strongly associated with the surviving scientific mechanism.",
    },

    {
      id: "cv2",

      label:
        "CONTROL B",

      title:
        "Boundary conditions",

      description:
        "Control environmental, geometric, temporal, or preparation conditions required for reliable function.",
    },

    {
      id: "cv3",

      label:
        "CONTROL C",

      title:
        "Feedback architecture",

      description:
        "Measure the system continuously and adjust operation so the required state remains within its functional region.",
    },

    {
      id: "cv4",

      label:
        "CONTROL D",

      title:
        "Redundant control",

      description:
        "Use multiple independent control channels so functional capability does not depend on one fragile mechanism.",
    },
  ];


const RESOURCE_CONSTRAINTS:
  EngineeringOption[] = [
    {
      id: "rc1",

      label:
        "RESOURCE A",

      title:
        "Minimum energy",

      description:
        "Prioritize the least energy-intensive architecture capable of preserving the required function.",
    },

    {
      id: "rc2",

      label:
        "RESOURCE B",

      title:
        "Minimum material complexity",

      description:
        "Reduce dependence on scarce, unstable, difficult-to-manufacture, or highly specialized material structures.",
    },

    {
      id: "rc3",

      label:
        "RESOURCE C",

      title:
        "Minimum control complexity",

      description:
        "Minimize sensing, computation, feedback, calibration, and operator requirements while retaining function.",
    },

    {
      id: "rc4",

      label:
        "RESOURCE D",

      title:
        "Maximum reproducibility",

      description:
        "Accept greater resource use when necessary to maximize independent reproducibility and operational reliability.",
    },
  ];


const FAILURE_BOUNDARIES:
  EngineeringOption[] = [
    {
      id: "fb1",

      label:
        "BOUNDARY A",

      title:
        "Loss of physical effect",

      description:
        "Define the conditions under which the scientific mechanism itself becomes too weak or disappears.",
    },

    {
      id: "fb2",

      label:
        "BOUNDARY B",

      title:
        "Loss of controllability",

      description:
        "Define where the phenomenon may still exist but can no longer be reliably driven into the required state.",
    },

    {
      id: "fb3",

      label:
        "BOUNDARY C",

      title:
        "Loss of reproducibility",

      description:
        "Define where performance becomes too sensitive to device, environment, manufacturing, or operator variation.",
    },

    {
      id: "fb4",

      label:
        "BOUNDARY D",

      title:
        "Irreversible failure",

      description:
        "Identify states from which the system cannot safely or economically recover after failure.",
    },
  ];

  /* ==========================================================
   COMPONENT
========================================================== */

export default function CivilizationScientificSimulation({
  paper,
}: CivilizationScientificSimulationProps) {
  const [
    activeStage,
    setActiveStage,
  ] =
    useState<ActiveStage>(
      1,
    );


  const [
    selectedHypothesisId,
    setSelectedHypothesisId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    selectedPredictionId,
    setSelectedPredictionId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    predictionLocked,
    setPredictionLocked,
  ] =
    useState(
      false,
    );


  const [
    interventionId,
    setInterventionId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    measurementId,
    setMeasurementId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    controlId,
    setControlId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    experimentResult,
    setExperimentResult,
  ] =
    useState<
      SimulatedExperimentResult |
      null
    >(
      null,
    );


  const [
    falsificationId,
    setFalsificationId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    revisionDecision,
    setRevisionDecision,
  ] =
    useState<
      RevisionDecision |
      null
    >(
      null,
    );


  const [
    revisionLocked,
    setRevisionLocked,
  ] =
    useState(
      false,
    );


  const [
    functionalTargetId,
    setFunctionalTargetId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    engineeringControlId,
    setEngineeringControlId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    resourceConstraintId,
    setResourceConstraintId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    failureBoundaryId,
    setFailureBoundaryId,
  ] =
    useState<
      string |
      null
    >(
      null,
    );


  const [
    engineeringLocked,
    setEngineeringLocked,
  ] =
    useState(
      false,
    );


  /* ==========================================================
     DERIVED THEORY
  ========================================================== */

  const hypotheses =
    useMemo(
      () =>
        buildHypotheses(
          paper,
        ),
      [
        paper,
      ],
    );


  const predictions =
    useMemo(
      () =>
        buildPredictions(
          selectedHypothesisId,
        ),
      [
        selectedHypothesisId,
      ],
    );


  const selectedHypothesis =
    hypotheses.find(
      (
        hypothesis,
      ) =>
        hypothesis.id ===
        selectedHypothesisId,
    ) ??
    null;


  const selectedPrediction =
    predictions.find(
      (
        prediction,
      ) =>
        prediction.id ===
        selectedPredictionId,
    ) ??
    null;


  const selectedIntervention =
    INTERVENTIONS.find(
      (
        item,
      ) =>
        item.id ===
        interventionId,
    ) ??
    null;


  const selectedMeasurement =
    MEASUREMENTS.find(
      (
        item,
      ) =>
        item.id ===
        measurementId,
    ) ??
    null;


  const selectedControl =
    CONTROLS.find(
      (
        item,
      ) =>
        item.id ===
        controlId,
    ) ??
    null;


  const selectedFalsification =
    FALSIFICATION_OPTIONS.find(
      (
        item,
      ) =>
        item.id ===
        falsificationId,
    ) ??
    null;


  const selectedRevision =
    REVISION_OPTIONS.find(
      (
        item,
      ) =>
        item.id ===
        revisionDecision,
    ) ??
    null;


  const selectedFunctionalTarget =
    FUNCTIONAL_TARGETS.find(
      (
        item,
      ) =>
        item.id ===
        functionalTargetId,
    ) ??
    null;


  const selectedEngineeringControl =
    CONTROL_VARIABLES.find(
      (
        item,
      ) =>
        item.id ===
        engineeringControlId,
    ) ??
    null;


  const selectedResourceConstraint =
    RESOURCE_CONSTRAINTS.find(
      (
        item,
      ) =>
        item.id ===
        resourceConstraintId,
    ) ??
    null;


  const selectedFailureBoundary =
    FAILURE_BOUNDARIES.find(
      (
        item,
      ) =>
        item.id ===
        failureBoundaryId,
    ) ??
    null;


  const experimentReady =
    Boolean(
      interventionId &&
        measurementId &&
        controlId,
    );


  const engineeringReady =
    Boolean(
      functionalTargetId &&
        engineeringControlId &&
        resourceConstraintId &&
        failureBoundaryId,
    );


  const canEngineer =
    revisionDecision ===
      "RETAIN" ||
    revisionDecision ===
      "WEAKEN";


  /* ==========================================================
     RESET FROM THEORY
  ========================================================== */

  function chooseHypothesis(
    id: string,
  ) {
    setSelectedHypothesisId(
      id,
    );

    setSelectedPredictionId(
      null,
    );

    setPredictionLocked(
      false,
    );

    setInterventionId(
      null,
    );

    setMeasurementId(
      null,
    );

    setControlId(
      null,
    );

    setExperimentResult(
      null,
    );

    setFalsificationId(
      null,
    );

    setRevisionDecision(
      null,
    );

    setRevisionLocked(
      false,
    );

    resetEngineering();
  }


  /* ==========================================================
     RESET ENGINEERING
  ========================================================== */

  function resetEngineering() {
    setFunctionalTargetId(
      null,
    );

    setEngineeringControlId(
      null,
    );

    setResourceConstraintId(
      null,
    );

    setFailureBoundaryId(
      null,
    );

    setEngineeringLocked(
      false,
    );
  }


  /* ==========================================================
     RUN EXPERIMENT
  ========================================================== */

  function runExperiment() {
    if (
      !selectedHypothesisId ||
      !selectedPredictionId ||
      !interventionId ||
      !measurementId ||
      !controlId
    ) {
      return;
    }


    const result =
      simulateExperiment(
        selectedHypothesisId,
        selectedPredictionId,
        interventionId,
        measurementId,
        controlId,
      );


    setExperimentResult(
      result,
    );


    setActiveStage(
      5,
    );
  }


  /* ==========================================================
     RETURN TO THEORY
  ========================================================== */

  function returnToTheory() {
    setSelectedHypothesisId(
      null,
    );

    setSelectedPredictionId(
      null,
    );

    setPredictionLocked(
      false,
    );

    setInterventionId(
      null,
    );

    setMeasurementId(
      null,
    );

    setControlId(
      null,
    );

    setExperimentResult(
      null,
    );

    setFalsificationId(
      null,
    );

    setRevisionDecision(
      null,
    );

    setRevisionLocked(
      false,
    );

    resetEngineering();

    setActiveStage(
      2,
    );
  }


  /* ==========================================================
     RETURN TO EXPERIMENT
  ========================================================== */

  function returnToExperiment() {
    setInterventionId(
      null,
    );

    setMeasurementId(
      null,
    );

    setControlId(
      null,
    );

    setExperimentResult(
      null,
    );

    setFalsificationId(
      null,
    );

    setRevisionDecision(
      null,
    );

    setRevisionLocked(
      false,
    );

    resetEngineering();

    setActiveStage(
      4,
    );
  }


  /* ==========================================================
     UI
  ========================================================== */

  return (
    <section className="ce-sim">
      {/* ==================================================
          STATUS
      ================================================== */}

      <div className="ce-sim__status">
        <span>
          SCIENTIFIC SIMULATION
        </span>

        <div>
          {[
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
          ].map(
            (
              stage,
            ) => (
              <i
                key={
                  stage
                }
                className={
                  activeStage >=
                  stage
                    ? "is-active"
                    : ""
                }
              />
            ),
          )}
        </div>

        <strong>
          THEORY × EMPIRICISM × ENGINEERING
        </strong>
      </div>


      {/* ==================================================
          01 OBSERVE
      ================================================== */}

      <article
        className={[
          "ce-sim-stage",

          activeStage ===
          1
            ? "is-current"
            : "is-complete",
        ].join(
          " ",
        )}
      >
        <div className="ce-sim-stage__index">
          01
        </div>

        <div className="ce-sim-stage__content">
          <span className="ce-sim-stage__label">
            OBSERVE
          </span>

          <h2>
            What did reality
            actually return?
          </h2>

          <p className="ce-sim-stage__intro">
            Begin with the reported observation,
            not with the preferred explanation.
          </p>

          <div className="ce-sim-observation">
            <small>
              REPORTED SCIENTIFIC SIGNAL
            </small>

            <p>
              {paper.summary ||
                paper.title}
            </p>
          </div>

          <div className="ce-sim-principle">
            <span>
              SCIENTIFIC CONSTRAINT
            </span>

            <strong>
              Observation
              {" ≠ "}
              Explanation
            </strong>

            <p>
              An observation constrains explanations
              without necessarily identifying a
              unique underlying mechanism.
            </p>
          </div>

          {activeStage ===
            1 && (
            <button
              type="button"
              className="ce-sim-advance"
              onClick={() =>
                setActiveStage(
                  2,
                )
              }
            >
              <span>
                Enter Theory Space
              </span>

              <span
                aria-hidden="true"
              >
                ↓
              </span>
            </button>
          )}
        </div>
      </article>


      {/* ==================================================
          02 THEORY
      ================================================== */}

      {activeStage >=
        2 && (
        <article
          className={[
            "ce-sim-stage",

            activeStage ===
            2
              ? "is-current"
              : "is-complete",
          ].join(
            " ",
          )}
        >
          <div className="ce-sim-stage__index">
            02
          </div>

          <div className="ce-sim-stage__content">
            <span className="ce-sim-stage__label">
              THEORIZE
            </span>

            <h2>
              Which explanation
              should be tested?
            </h2>

            <p className="ce-sim-stage__intro">
              Select a working hypothesis.
              Selection determines what you will
              ask reality to discriminate.
            </p>

            <div className="ce-sim-hypotheses">
              {hypotheses.map(
                (
                  hypothesis,
                ) => {
                  const selected =
                    hypothesis.id ===
                    selectedHypothesisId;

                  return (
                    <button
                      key={
                        hypothesis.id
                      }
                      type="button"
                      className={[
                        "ce-sim-hypothesis",

                        selected
                          ? "is-selected"
                          : "",
                      ].join(
                        " ",
                      )}
                      onClick={() =>
                        chooseHypothesis(
                          hypothesis.id,
                        )
                      }
                    >
                      <small>
                        {
                          hypothesis.label
                        }
                      </small>

                      <strong>
                        {
                          hypothesis.title
                        }
                      </strong>

                      <p>
                        {
                          hypothesis.statement
                        }
                      </p>

                      <span>
                        {selected
                          ? "SELECTED"
                          : "SELECT"}
                      </span>
                    </button>
                  );
                },
              )}
            </div>

            {selectedHypothesis && (
              <div className="ce-sim-selection">
                <span>
                  CURRENT WORKING HYPOTHESIS
                </span>

                <strong>
                  {
                    selectedHypothesis.title
                  }
                </strong>

                <p>
                  A working hypothesis is a
                  testable commitment, not a
                  declaration of truth.
                </p>
              </div>
            )}

            {activeStage ===
              2 && (
              <button
                type="button"
                className="ce-sim-advance"
                disabled={
                  !selectedHypothesisId
                }
                onClick={() =>
                  setActiveStage(
                    3,
                  )
                }
              >
                <span>
                  Generate Predictions
                </span>

                <span
                  aria-hidden="true"
                >
                  ↓
                </span>
              </button>
            )}
          </div>
        </article>
      )}


      {/* ==================================================
          03 PREDICT
      ================================================== */}

      {activeStage >=
        3 && (
        <article
          className={[
            "ce-sim-stage",

            activeStage ===
            3
              ? "is-current"
              : "is-complete",
          ].join(
            " ",
          )}
        >
          <div className="ce-sim-stage__index">
            03
          </div>

          <div className="ce-sim-stage__content">
            <span className="ce-sim-stage__label">
              PREDICT
            </span>

            <h2>
              What should reality
              produce?
            </h2>

            <p className="ce-sim-stage__intro">
              Commit before seeing the simulated
              empirical outcome.
            </p>

            {selectedHypothesis && (
              <div className="ce-sim-testing">
                <small>
                  TESTING
                </small>

                <strong>
                  {
                    selectedHypothesis.title
                  }
                </strong>
              </div>
            )}

            <div className="ce-sim-predictions">
              {predictions.map(
                (
                  prediction,
                ) => {
                  const selected =
                    prediction.id ===
                    selectedPredictionId;

                  return (
                    <button
                      key={
                        prediction.id
                      }
                      type="button"
                      disabled={
                        predictionLocked
                      }
                      className={[
                        "ce-sim-prediction",

                        selected
                          ? "is-selected"
                          : "",

                        selected &&
                        predictionLocked
                          ? "is-locked"
                          : "",
                      ].join(
                        " ",
                      )}
                      onClick={() =>
                        setSelectedPredictionId(
                          prediction.id,
                        )
                      }
                    >
                      <small>
                        {
                          prediction.label
                        }
                      </small>

                      <p>
                        {
                          prediction.statement
                        }
                      </p>

                      <span>
                        {selected &&
                        predictionLocked
                          ? "LOCKED"
                          : selected
                            ? "SELECTED"
                            : "SELECT"}
                      </span>
                    </button>
                  );
                },
              )}
            </div>

            {selectedPredictionId &&
              !predictionLocked && (
                <button
                  type="button"
                  className="ce-sim-lock"
                  onClick={() =>
                    setPredictionLocked(
                      true,
                    )
                  }
                >
                  Lock Prediction
                </button>
              )}

            {predictionLocked &&
              selectedPrediction && (
                <>
                  <div className="ce-sim-locked">
                    <span>
                      PREDICTION LOCKED
                    </span>

                    <strong>
                      {
                        selectedPrediction.label
                      }
                    </strong>

                    <p>
                      {
                        selectedPrediction.statement
                      }
                    </p>
                  </div>

                  {activeStage ===
                    3 && (
                    <button
                      type="button"
                      className="ce-sim-advance"
                      onClick={() =>
                        setActiveStage(
                          4,
                        )
                      }
                    >
                      <span>
                        Design Experiment
                      </span>

                      <span
                        aria-hidden="true"
                      >
                        ↓
                      </span>
                    </button>
                  )}
                </>
              )}
          </div>
        </article>
      )}


      {/* ==================================================
          04 EXPERIMENT
      ================================================== */}

      {activeStage >=
        4 && (
        <article
          className={[
            "ce-sim-stage",

            activeStage ===
            4
              ? "is-current"
              : "is-complete",
          ].join(
            " ",
          )}
        >
          <div className="ce-sim-stage__index">
            04
          </div>

          <div className="ce-sim-stage__content">
            <span className="ce-sim-stage__label">
              EXPERIMENT
            </span>

            <h2>
              How should reality
              be interrogated?
            </h2>

            <p className="ce-sim-stage__intro">
              Experimental discrimination requires
              an intervention, a measurement
              channel, and a control structure.
            </p>

            <ExperimentGroup
              title="INTERVENTION"
              question="What will you change?"
              options={
                INTERVENTIONS
              }
              selectedId={
                interventionId
              }
              onSelect={
                setInterventionId
              }
            />

            <ExperimentGroup
              title="MEASUREMENT"
              question="What will you observe?"
              options={
                MEASUREMENTS
              }
              selectedId={
                measurementId
              }
              onSelect={
                setMeasurementId
              }
            />

            <ExperimentGroup
              title="CONTROL"
              question="What protects inference?"
              options={
                CONTROLS
              }
              selectedId={
                controlId
              }
              onSelect={
                setControlId
              }
            />

            {experimentReady && (
              <div className="ce-sim-experiment-summary">
                <span>
                  EXPERIMENT READY
                </span>

                <div>
                  <p>
                    <small>
                      INTERVENTION
                    </small>

                    {
                      selectedIntervention
                        ?.title
                    }
                  </p>

                  <p>
                    <small>
                      MEASUREMENT
                    </small>

                    {
                      selectedMeasurement
                        ?.title
                    }
                  </p>

                  <p>
                    <small>
                      CONTROL
                    </small>

                    {
                      selectedControl
                        ?.title
                    }
                  </p>
                </div>
              </div>
            )}

            <button
              type="button"
              className="ce-sim-run"
              disabled={
                !experimentReady
              }
              onClick={
                runExperiment
              }
            >
              <span>
                Run Experiment
              </span>

              <strong>
                REALITY →
              </strong>
            </button>
          </div>
        </article>
      )}


      {/* ==================================================
          05 CONFRONT REALITY
      ================================================== */}

      {activeStage >=
        5 &&
        experimentResult && (
        <article
          className={[
            "ce-sim-stage",

            activeStage ===
            5
              ? "is-current"
              : "is-complete",
          ].join(
            " ",
          )}
        >
          <div className="ce-sim-stage__index">
            05
          </div>

          <div className="ce-sim-stage__content">
            <span className="ce-sim-stage__label">
              CONFRONT REALITY
            </span>

            <h2>
              What did the
              simulation return?
            </h2>

            <div className="ce-sim-warning">
              <span>
                SIMULATED OUTCOME
              </span>

              <strong>
                NOT THE SOURCE PAPER&apos;S
                REPORTED RESULT
              </strong>
            </div>

            <div className="ce-sim-comparison">
              <div>
                <small>
                  YOUR LOCKED PREDICTION
                </small>

                <strong>
                  {
                    selectedPrediction
                      ?.label
                  }
                </strong>

                <p>
                  {
                    selectedPrediction
                      ?.statement
                  }
                </p>
              </div>

              <div className="ce-sim-comparison__axis">
                VS
              </div>

              <div>
                <small>
                  SIMULATED REALITY
                </small>

                <strong>
                  {
                    experimentResult.status
                  }
                </strong>

                <p>
                  {
                    experimentResult.observation
                  }
                </p>
              </div>
            </div>

            <div className="ce-sim-result">
              <div>
                <small>
                  INTERPRETATION
                </small>

                <p>
                  {
                    experimentResult.interpretation
                  }
                </p>
              </div>

              <div>
                <small>
                  DISCRIMINATION STRENGTH
                </small>

                <strong>
                  {
                    experimentResult
                      .discriminationStrength
                  }
                </strong>
              </div>
            </div>

            <p className="ce-sim-result__caveat">
              {
                experimentResult.caveat
              }
            </p>

            {activeStage ===
              5 && (
              <button
                type="button"
                className="ce-sim-advance"
                onClick={() =>
                  setActiveStage(
                    6,
                  )
                }
              >
                <span>
                  Try to Falsify
                </span>

                <span
                  aria-hidden="true"
                >
                  ↓
                </span>
              </button>
            )}
          </div>
        </article>
      )}


      {/* ==================================================
          06 FALSIFY
      ================================================== */}

      {activeStage >=
        6 && (
        <article
          className={[
            "ce-sim-stage",

            activeStage ===
            6
              ? "is-current"
              : "is-complete",
          ].join(
            " ",
          )}
        >
          <div className="ce-sim-stage__index">
            06
          </div>

          <div className="ce-sim-stage__content">
            <span className="ce-sim-stage__label">
              FALSIFY
            </span>

            <h2>
              What is the strongest
              test against your own
              explanation?
            </h2>

            <p className="ce-sim-stage__intro">
              Scientific strength does not come
              from protecting an explanation.
              It comes from exposing it to tests
              capable of making it fail.
            </p>

            <div className="ce-sim-falsification-grid">
              {FALSIFICATION_OPTIONS.map(
                (
                  option,
                ) => (
                  <button
                    key={
                      option.id
                    }
                    type="button"
                    className={[
                      "ce-sim-falsification",

                      falsificationId ===
                      option.id
                        ? "is-selected"
                        : "",
                    ].join(
                      " ",
                    )}
                    onClick={() =>
                      setFalsificationId(
                        option.id,
                      )
                    }
                  >
                    <small>
                      {
                        option.label
                      }
                    </small>

                    <strong>
                      {
                        option.title
                      }
                    </strong>

                    <p>
                      {
                        option.description
                      }
                    </p>
                  </button>
                ),
              )}
            </div>

            {selectedFalsification && (
              <div className="ce-sim-falsification-lock">
                <span>
                  STRONGEST COUNTER-TEST SELECTED
                </span>

                <strong>
                  {
                    selectedFalsification.title
                  }
                </strong>

                <p>
                  The current model remains
                  provisional until it survives
                  this stronger discriminatory
                  test.
                </p>
              </div>
            )}

            {selectedFalsification &&
              activeStage ===
                6 && (
                <button
                  type="button"
                  className="ce-sim-advance"
                  onClick={() =>
                    setActiveStage(
                      7,
                    )
                  }
                >
                  <span>
                    Enter Scientific Revision
                  </span>

                  <span
                    aria-hidden="true"
                  >
                    ↓
                  </span>
                </button>
              )}
          </div>
        </article>
      )}


      {/* ==================================================
          07 REVISE
      ================================================== */}

      {activeStage >=
        7 && (
        <article
          className={[
            "ce-sim-stage",

            activeStage ===
            7
              ? "is-current"
              : "is-complete",
          ].join(
            " ",
          )}
        >
          <div className="ce-sim-stage__index">
            07
          </div>

          <div className="ce-sim-stage__content">
            <span className="ce-sim-stage__label">
              REVISE
            </span>

            <h2>
              What should survive
              contact with reality?
            </h2>

            <p className="ce-sim-stage__intro">
              Scientific revision asks how much
              of the current model remains
              justified by the evidence generated
              so far.
            </p>

            {/* ==========================================
                EVIDENCE LEDGER
            ========================================== */}

            <div className="ce-sim-ledger">
              <div className="ce-sim-ledger__header">
                <span>
                  EVIDENCE LEDGER
                </span>

                <strong>
                  What is actually known?
                </strong>
              </div>

              <div className="ce-sim-ledger__grid">
                <div>
                  <small>
                    01 / OBSERVATION
                  </small>

                  <p>
                    {paper.summary ||
                      paper.title}
                  </p>
                </div>

                <div>
                  <small>
                    02 / WORKING MODEL
                  </small>

                  <strong>
                    {
                      selectedHypothesis
                        ?.title
                    }
                  </strong>

                  <p>
                    {
                      selectedHypothesis
                        ?.statement
                    }
                  </p>
                </div>

                <div>
                  <small>
                    03 / LOCKED PREDICTION
                  </small>

                  <p>
                    {
                      selectedPrediction
                        ?.statement
                    }
                  </p>
                </div>

                <div>
                  <small>
                    04 / INTERVENTION
                  </small>

                  <strong>
                    {
                      selectedIntervention
                        ?.title
                    }
                  </strong>
                </div>

                <div>
                  <small>
                    05 / SIMULATED OUTCOME
                  </small>

                  <strong>
                    {
                      experimentResult
                        ?.status
                    }
                  </strong>

                  <p>
                    {
                      experimentResult
                        ?.observation
                    }
                  </p>
                </div>

                <div>
                  <small>
                    06 / COUNTER-TEST
                  </small>

                  <strong>
                    {
                      selectedFalsification
                        ?.title
                    }
                  </strong>

                  <p>
                    {
                      selectedFalsification
                        ?.description
                    }
                  </p>
                </div>
              </div>
            </div>

            <div className="ce-sim-revision-principle">
              <span>
                EPISTEMIC CONSTRAINT
              </span>

              <strong>
                Evidence
                {" ≠ "}
                Certainty
              </strong>

              <p>
                A model may survive the current
                experiment without becoming true,
                and it may be challenged without
                immediately identifying its
                replacement.
              </p>
            </div>

            {/* ==========================================
                REVISION OPTIONS
            ========================================== */}

            <div className="ce-sim-revision-grid">
              {REVISION_OPTIONS.map(
                (
                  option,
                ) => {
                  const selected =
                    revisionDecision ===
                    option.id;

                  return (
                    <button
                      key={
                        option.id
                      }
                      type="button"
                      disabled={
                        revisionLocked
                      }
                      className={[
                        "ce-sim-revision",

                        selected
                          ? "is-selected"
                          : "",

                        selected &&
                        revisionLocked
                          ? "is-locked"
                          : "",
                      ].join(
                        " ",
                      )}
                      onClick={() =>
                        setRevisionDecision(
                          option.id,
                        )
                      }
                    >
                      <small>
                        {
                          option.label
                        }
                      </small>

                      <strong>
                        {
                          option.title
                        }
                      </strong>

                      <p>
                        {
                          option.description
                        }
                      </p>

                      <span>
                        {selected &&
                        revisionLocked
                          ? "LOCKED"
                          : selected
                            ? "SELECTED"
                            : "SELECT"}
                      </span>
                    </button>
                  );
                },
              )}
            </div>

            {revisionDecision &&
              !revisionLocked && (
                <button
                  type="button"
                  className="ce-sim-lock"
                  onClick={() =>
                    setRevisionLocked(
                      true,
                    )
                  }
                >
                  Lock Scientific Revision
                </button>
              )}

            {revisionLocked &&
              selectedRevision && (
                <>
                  <div className="ce-sim-scientific-state">
                    <div className="ce-sim-scientific-state__top">
                      <span>
                        CURRENT SCIENTIFIC STATE
                      </span>

                      <small>
                        PROVISIONAL
                      </small>
                    </div>

                    <strong className="ce-sim-scientific-state__decision">
                      {
                        selectedRevision.id
                      }
                    </strong>

                    <h3>
                      {
                        selectedRevision.title
                      }
                    </h3>

                    <p>
                      {
                        selectedRevision.implication
                      }
                    </p>

                    <div className="ce-sim-scientific-state__equation">
                      <span>
                        Current Model
                      </span>

                      <b>→</b>

                      <span>
                        Evidence
                      </span>

                      <b>→</b>

                      <span>
                        Falsification
                      </span>

                      <b>→</b>

                      <strong>
                        {
                          selectedRevision.id
                        }
                      </strong>
                    </div>
                  </div>

                  {/* ======================================
                      BRANCHING
                  ====================================== */}

                  {revisionDecision ===
                    "REPLACE" && (
                    <div className="ce-sim-branch">
                      <span>
                        THEORY REVISION REQUIRED
                      </span>

                      <strong>
                        Return to Theory Space
                      </strong>

                      <p>
                        The current model should not
                        yet be translated into
                        engineering. Construct a new
                        explanation with different
                        testable consequences.
                      </p>

                      <button
                        type="button"
                        className="ce-sim-advance"
                        onClick={
                          returnToTheory
                        }
                      >
                        Return to Theory Space
                      </button>
                    </div>
                  )}

                  {revisionDecision ===
                    "UNRESOLVED" && (
                    <div className="ce-sim-branch">
                      <span>
                        MORE EVIDENCE REQUIRED
                      </span>

                      <strong>
                        Design a Stronger Experiment
                      </strong>

                      <p>
                        Current evidence does not
                        justify technological
                        translation. Increase
                        discriminatory power before
                        engineering the relation.
                      </p>

                      <button
                        type="button"
                        className="ce-sim-advance"
                        onClick={
                          returnToExperiment
                        }
                      >
                        Return to Experiment
                      </button>
                    </div>
                  )}

                  {canEngineer &&
                    activeStage ===
                      7 && (
                      <button
                        type="button"
                        className="ce-sim-advance"
                        onClick={() =>
                          setActiveStage(
                            8,
                          )
                        }
                      >
                        <span>
                          Enter Engineering
                        </span>

                        <span
                          aria-hidden="true"
                        >
                          ↓
                        </span>
                      </button>
                    )}
                </>
              )}
          </div>
        </article>
      )}


      {/* ==================================================
          08 ENGINEER
      ================================================== */}

      {activeStage >=
        8 &&
        canEngineer && (
        <article className="ce-sim-stage is-current">
          <div className="ce-sim-stage__index">
            08
          </div>

          <div className="ce-sim-stage__content">
            <span className="ce-sim-stage__label">
              ENGINEER
            </span>

            <h2>
              What controllable
              capability can be built?
            </h2>

            <p className="ce-sim-stage__intro">
              Scientific survival alone is not
              engineering. A usable technology
              requires a task, controllable
              variables, finite resources, and
              explicit failure boundaries.
            </p>

            {revisionDecision ===
              "WEAKEN" && (
              <div className="ce-sim-engineering-warning">
                <span>
                  BOUNDED SCIENTIFIC MODEL
                </span>

                <strong>
                  Engineering scope must remain
                  restricted.
                </strong>

                <p>
                  The selected model was weakened
                  rather than fully retained.
                  Technology should therefore be
                  designed only within the
                  conditions under which the
                  scientific relation currently
                  survives.
                </p>
              </div>
            )}

            <div className="ce-sim-engineering-principle">
              <span>
                ENGINEERING CONSTRAINT
              </span>

              <strong>
                Physical Possibility
                {" ≠ "}
                Technological Capability
              </strong>

              <p>
                A physical relation becomes useful
                only when it can be reached,
                controlled, measured, reproduced,
                maintained, and recovered within
                finite resources.
              </p>
            </div>

            {/* ==========================================
                FUNCTIONAL TARGET
            ========================================== */}

            <EngineeringGroup
              title="FUNCTIONAL TARGET"
              question="What should the technology actually do?"
              options={
                FUNCTIONAL_TARGETS
              }
              selectedId={
                functionalTargetId
              }
              onSelect={
                setFunctionalTargetId
              }
              disabled={
                engineeringLocked
              }
            />

            {/* ==========================================
                CONTROL VARIABLE
            ========================================== */}

            <EngineeringGroup
              title="CONTROL ARCHITECTURE"
              question="What must remain controllable?"
              options={
                CONTROL_VARIABLES
              }
              selectedId={
                engineeringControlId
              }
              onSelect={
                setEngineeringControlId
              }
              disabled={
                engineeringLocked
              }
            />

            {/* ==========================================
                RESOURCE CONSTRAINT
            ========================================== */}

            <EngineeringGroup
              title="RESOURCE CONSTRAINT"
              question="What should the architecture minimize?"
              options={
                RESOURCE_CONSTRAINTS
              }
              selectedId={
                resourceConstraintId
              }
              onSelect={
                setResourceConstraintId
              }
              disabled={
                engineeringLocked
              }
            />

            {/* ==========================================
                FAILURE BOUNDARY
            ========================================== */}

            <EngineeringGroup
              title="FAILURE BOUNDARY"
              question="Where must the technology stop being trusted?"
              options={
                FAILURE_BOUNDARIES
              }
              selectedId={
                failureBoundaryId
              }
              onSelect={
                setFailureBoundaryId
              }
              disabled={
                engineeringLocked
              }
            />

            {/* ==========================================
                ENGINEERING READY
            ========================================== */}

            {engineeringReady &&
              !engineeringLocked && (
                <div className="ce-sim-engineering-ready">
                  <span>
                    ENGINEERING ARCHITECTURE READY
                  </span>

                  <div>
                    <p>
                      <small>
                        FUNCTION
                      </small>

                      {
                        selectedFunctionalTarget
                          ?.title
                      }
                    </p>

                    <p>
                      <small>
                        CONTROL
                      </small>

                      {
                        selectedEngineeringControl
                          ?.title
                      }
                    </p>

                    <p>
                      <small>
                        RESOURCE
                      </small>

                      {
                        selectedResourceConstraint
                          ?.title
                      }
                    </p>

                    <p>
                      <small>
                        FAILURE
                      </small>

                      {
                        selectedFailureBoundary
                          ?.title
                      }
                    </p>
                  </div>
                </div>
              )}

            {engineeringReady &&
              !engineeringLocked && (
                <button
                  type="button"
                  className="ce-sim-lock"
                  onClick={() =>
                    setEngineeringLocked(
                      true,
                    )
                  }
                >
                  Lock Engineering Candidate
                </button>
              )}

            {/* ==========================================
                ENGINEERING CANDIDATE
            ========================================== */}

            {engineeringLocked && (
              <>
                <div className="ce-sim-engineering-candidate">
                  <div className="ce-sim-engineering-candidate__top">
                    <span>
                      CURRENT ENGINEERING CANDIDATE
                    </span>

                    <small>
                      PROVISIONAL
                    </small>
                  </div>

                  <h3>
                    {
                      selectedFunctionalTarget
                        ?.title
                    }
                  </h3>

                  <p>
                    Build a system that uses the
                    surviving scientific relation
                    through{" "}
                    <strong>
                      {
                        selectedEngineeringControl
                          ?.title
                      }
                    </strong>
                    , prioritizes{" "}
                    <strong>
                      {
                        selectedResourceConstraint
                          ?.title
                      }
                    </strong>
                    , and stops being trusted at{" "}
                    <strong>
                      {
                        selectedFailureBoundary
                          ?.title
                      }
                    </strong>
                    .
                  </p>

                  <div className="ce-sim-engineering-chain">
                    <span>
                      Surviving Relation
                    </span>

                    <i>
                      →
                    </i>

                    <span>
                      Control
                    </span>

                    <i>
                      →
                    </i>

                    <span>
                      Function
                    </span>

                    <i>
                      →
                    </i>

                    <span>
                      Failure Boundary
                    </span>

                    <i>
                      →
                    </i>

                    <strong>
                      Engineering Candidate
                    </strong>
                  </div>
                </div>

                <div className="ce-sim-next-phase">
                  <span>
                    NEXT
                  </span>

                  <strong>
                    09 — Civilization Consequence
                  </strong>

                  <p>
                    The next stage asks what happens
                    when a scientific capability
                    escapes the laboratory and becomes
                    a device, platform, infrastructure,
                    institution, or civilization-scale
                    dependency.
                  </p>

                  <div className="ce-sim-next-phase__chain">
                    Science
                    <i>→</i>
                    Engineering
                    <i>→</i>
                    Technology
                    <i>→</i>
                    Infrastructure
                    <i>→</i>
                    Civilization
                  </div>

                  <small>
                    PHASE 5C-6
                  </small>
                </div>
              </>
            )}
          </div>
        </article>
      )}
    </section>
  );
}


/* ==========================================================
   EXPERIMENT GROUP
========================================================== */

function ExperimentGroup({
  title,
  question,
  options,
  selectedId,
  onSelect,
}: {
  title: string;
  question: string;
  options: ExperimentOption[];
  selectedId: string | null;
  onSelect: (
    id: string,
  ) => void;
}) {
  return (
    <div className="ce-sim-experiment-group">
      <header>
        <span>
          {title}
        </span>

        <strong>
          {question}
        </strong>
      </header>

      <div className="ce-sim-option-grid">
        {options.map(
          (
            option,
          ) => {
            const selected =
              selectedId ===
              option.id;

            return (
              <button
                key={
                  option.id
                }
                type="button"
                className={[
                  "ce-sim-option",

                  selected
                    ? "is-selected"
                    : "",
                ].join(
                  " ",
                )}
                onClick={() =>
                  onSelect(
                    option.id,
                  )
                }
              >
                <small>
                  {
                    option.label
                  }
                </small>

                <strong>
                  {
                    option.title
                  }
                </strong>

                <p>
                  {
                    option.description
                  }
                </p>
              </button>
            );
          },
        )}
      </div>
    </div>
  );
}


/* ==========================================================
   ENGINEERING GROUP
========================================================== */

function EngineeringGroup({
  title,
  question,
  options,
  selectedId,
  onSelect,
  disabled,
}: {
  title: string;
  question: string;
  options: EngineeringOption[];
  selectedId: string | null;
  onSelect: (
    id: string,
  ) => void;
  disabled: boolean;
}) {
  return (
    <div className="ce-sim-engineering-group">
      <header>
        <span>
          {title}
        </span>

        <strong>
          {question}
        </strong>
      </header>

      <div className="ce-sim-engineering-grid">
        {options.map(
          (
            option,
          ) => {
            const selected =
              selectedId ===
              option.id;

            return (
              <button
                key={
                  option.id
                }
                type="button"
                disabled={
                  disabled
                }
                className={[
                  "ce-sim-engineering-option",

                  selected
                    ? "is-selected"
                    : "",

                  selected &&
                  disabled
                    ? "is-locked"
                    : "",
                ].join(
                  " ",
                )}
                onClick={() =>
                  onSelect(
                    option.id,
                  )
                }
              >
                <small>
                  {
                    option.label
                  }
                </small>

                <strong>
                  {
                    option.title
                  }
                </strong>

                <p>
                  {
                    option.description
                  }
                </p>

                <span>
                  {selected &&
                  disabled
                    ? "LOCKED"
                    : selected
                      ? "SELECTED"
                      : "SELECT"}
                </span>
              </button>
            );
          },
        )}
      </div>
    </div>
  );
}