export type BuilderDiffAction = "create" | "update" | "delete";

export type BuilderDiffFile = {
  path: string;
  action: BuilderDiffAction;
  language: "tsx" | "ts" | "css" | "json" | "md" | "html" | "js";
  before?: string;
  after: string;
  summary: string;
  risk: "low" | "medium" | "high";
};

export type BuilderDiffPlan = {
  id: string;
  title: string;
  description: string;
  files: BuilderDiffFile[];
  approvalRequired: boolean;
};

function safeTitle(input: string) {
  return input.trim() || "Create a new Builder interface";
}

export function createBuilderDiffPlan(prompt: string): BuilderDiffPlan {
  const title = safeTitle(prompt);

  return {
    id: `BD-${Date.now()}`,
    title,
    description:
      "A proposed file-level implementation plan generated by ArcheNova Builder. This plan does not modify files automatically.",
    approvalRequired: true,
    files: [
      {
        path: "app/example/page.tsx",
        action: "create",
        language: "tsx",
        before: "",
        after: `export default function ExamplePage() {
  return (
    <main className="page-standard">
      <section className="glass-block">
        <span className="home-section-label">
          GENERATED BY ARCHENOVA BUILDER
        </span>

        <h1>${title}</h1>

        <p className="page-lead">
          This page was proposed by Builder as a safe implementation draft.
        </p>
      </section>
    </main>
  );
}
`,
        summary: "Create a new example page from the Builder request.",
        risk: "low",
      },
      {
        path: "styles/globals.css",
        action: "update",
        language: "css",
        before: "/* existing styles */",
        after: `.builder-generated-card {
  border-radius: 24px;
  border: 1px solid rgba(255,255,255,0.12);
  background: rgba(255,255,255,0.055);
  padding: 1rem;
}
`,
        summary: "Add optional styling for generated Builder output.",
        risk: "low",
      },
    ],
  };
}

export function summarizeBuilderDiff(plan: BuilderDiffPlan) {
  const created = plan.files.filter((file) => file.action === "create").length;
  const updated = plan.files.filter((file) => file.action === "update").length;
  const deleted = plan.files.filter((file) => file.action === "delete").length;

  return {
    total: plan.files.length,
    created,
    updated,
    deleted,
    approvalRequired: plan.approvalRequired,
  };
}