export const senateAgenda =
[
  {
    "id": "agenda-1",
    "rank": 1,
    "title": "Why Scaling AI Compute Performance Requires a New Power Architecture",
    "slug": "ai-why-scaling-ai-compute-performance-requires-a-new-power-architecture",
    "category": "AI",
    "source": "NVIDIA",
    "score": 9.9,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because biological engineering can reshape food security, medicine, agriculture, manufacturing, ecological resilience, and civilization’s relationship with living systems.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-2",
    "rank": 2,
    "title": "H3 launches navigation satellite",
    "slug": "ai-h3-launches-navigation-satellite",
    "category": "AI",
    "source": "SpaceNews",
    "score": 9.6,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-3",
    "rank": 3,
    "title": "Three energy-loss routes may explain Tarantula Nebula's X-ray shortfall",
    "slug": "ai-three-energy-loss-routes-may-explain-tarantula-nebula-s-x-ray-shortfall",
    "category": "AI",
    "source": "Phys.org",
    "score": 9.5,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-4",
    "rank": 4,
    "title": "SpaceX increasing footprint in missile defense",
    "slug": "space-spacex-increasing-footprint-in-missile-defense",
    "category": "Space",
    "source": "SpaceNews",
    "score": 9.5,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because advanced civilization depends on the ability to convert knowledge into reproducible material capability, reliable production, and resilient supply systems.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-5",
    "rank": 5,
    "title": "BlackSky wins seven-figure, multiyear international contract",
    "slug": "space-blacksky-wins-seven-figure-multiyear-international-contract",
    "category": "Space",
    "source": "SpaceNews",
    "score": 9.4,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-6",
    "rank": 6,
    "title": "Curiosity Blog, Sols 4968-4974: Rock Climbing Towards the Discontinuity",
    "slug": "space-curiosity-blog-sols-4968-4974-rock-climbing-towards-the-discontinuity",
    "category": "Space",
    "source": "NASA",
    "score": 9.4,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-7",
    "rank": 7,
    "title": "Golden Dome faces 2027 funding cliff ",
    "slug": "space-golden-dome-faces-2027-funding-cliff",
    "category": "Space",
    "source": "SpaceNews",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-8",
    "rank": 8,
    "title": "Lion Nebula Roars in Webb’s Sights",
    "slug": "ai-lion-nebula-roars-in-webb-s-sights",
    "category": "AI",
    "source": "NASA",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-9",
    "rank": 9,
    "title": "NASA Telescopes Create Colorful ‘Craft’ From Nearby Nebula",
    "slug": "ai-nasa-telescopes-create-colorful-craft-from-nearby-nebula",
    "category": "AI",
    "source": "NASA",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-10",
    "rank": 10,
    "title": "Building the Moon Base: NASA Stories at the Ion  ",
    "slug": "space-building-the-moon-base-nasa-stories-at-the-ion",
    "category": "Space",
    "source": "NASA",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-11",
    "rank": 11,
    "title": "Former Space Force general joins Lunar Outpost board",
    "slug": "space-former-space-force-general-joins-lunar-outpost-board",
    "category": "Space",
    "source": "SpaceNews",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because biological engineering can reshape food security, medicine, agriculture, manufacturing, ecological resilience, and civilization’s relationship with living systems.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-12",
    "rank": 12,
    "title": "First Neutron launch may slip to 2027",
    "slug": "space-first-neutron-launch-may-slip-to-2027",
    "category": "Space",
    "source": "SpaceNews",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  }
];
