export const senateAgenda =
[
  {
    "id": "agenda-1",
    "rank": 1,
    "title": "A Physics--ML Multi-Fidelity Strategy for Earth System Model Parameter Optimization: A QG Proof-of-Concept",
    "slug": "general-a-physics-ml-multi-fidelity-strategy-for-earth-system-model-parameter-optimizati",
    "category": "General",
    "source": "arXiv Physics",
    "score": 9.8,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this signal influence civilization?",
    "whyItMatters": "This matters because energy availability, reliability, and scalability determine the freedom, complexity, and resilience of civilization-scale systems.",
    "architectureHandoff": "Civilization Architecture",
    "status": "Open"
  },
  {
    "id": "agenda-2",
    "rank": 2,
    "title": "Magnets could help quantum computers talk to each other, says researcher",
    "slug": "energy-magnets-could-help-quantum-computers-talk-to-each-other-says-researcher",
    "category": "Energy",
    "source": "Phys.org",
    "score": 9.6,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Should ArcheNova prioritize this energy capability?",
    "whyItMatters": "This matters because energy availability, reliability, and scalability determine the freedom, complexity, and resilience of civilization-scale systems.",
    "architectureHandoff": "Civilization Energy Architecture",
    "status": "Open"
  },
  {
    "id": "agenda-3",
    "rank": 3,
    "title": "More satellites watch the battlefield, putting a premium on making sense of the data",
    "slug": "ai-more-satellites-watch-the-battlefield-putting-a-premium-on-making-sense-of-the-d",
    "category": "AI",
    "source": "SpaceNews",
    "score": 9.6,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-4",
    "rank": 4,
    "title": "FLEX and Sentinel-3C launch highlights ",
    "slug": "space-flex-and-sentinel-3c-launch-highlights",
    "category": "Space",
    "source": "ESA",
    "score": 9.6,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-5",
    "rank": 5,
    "title": "Calibrating subgrid parametrizations of single-column ocean models via simulation-based inference",
    "slug": "ai-calibrating-subgrid-parametrizations-of-single-column-ocean-models-via-simulatio",
    "category": "AI",
    "source": "arXiv Physics",
    "score": 9.6,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because energy availability, reliability, and scalability determine the freedom, complexity, and resilience of civilization-scale systems.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-6",
    "rank": 6,
    "title": "AI Infra Summit: NVIDIA Vera Rubin and DSX Platform Advancements Showcase Energy Efficiencies of Optimizing Tokens Per Watt for AI Factories",
    "slug": "ai-ai-infra-summit-nvidia-vera-rubin-and-dsx-platform-advancements-showcase-energy-",
    "category": "AI",
    "source": "NVIDIA",
    "score": 9.5,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because advanced civilization depends on the ability to convert knowledge into reproducible material capability, reliable production, and resilient supply systems.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-7",
    "rank": 7,
    "title": "Adjoint-based Inversion for the Diffusion Coefficient in Marine Lake Models",
    "slug": "energy-adjoint-based-inversion-for-the-diffusion-coefficient-in-marine-lake-models",
    "category": "Energy",
    "source": "arXiv Physics",
    "score": 9.5,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Should ArcheNova prioritize this energy capability?",
    "whyItMatters": "This matters because energy availability, reliability, and scalability determine the freedom, complexity, and resilience of civilization-scale systems.",
    "architectureHandoff": "Civilization Energy Architecture",
    "status": "Open"
  },
  {
    "id": "agenda-8",
    "rank": 8,
    "title": "Celebrate International Observe the Moon Night with NASA",
    "slug": "ai-celebrate-international-observe-the-moon-night-with-nasa",
    "category": "AI",
    "source": "NASA",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-9",
    "rank": 9,
    "title": "‘Bogland’ explores beautifully strange ecosystems",
    "slug": "space-bogland-explores-beautifully-strange-ecosystems",
    "category": "Space",
    "source": "Science News",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-10",
    "rank": 10,
    "title": "STAT+: Medicare’s AI prior authorization pilot was rushed and full of problems, new documents reveal",
    "slug": "ai-stat-medicare-s-ai-prior-authorization-pilot-was-rushed-and-full-of-problems-new",
    "category": "AI",
    "source": "STAT",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-11",
    "rank": 11,
    "title": "STAT+: New documents reveal problems with Medicare’s prior-authorization pilot",
    "slug": "ai-stat-new-documents-reveal-problems-with-medicare-s-prior-authorization-pilot",
    "category": "AI",
    "source": "STAT",
    "score": 9.2,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because biological resilience, health infrastructure, and adaptive medicine directly affect human capability, institutional stability, and long-term societal continuity.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-12",
    "rank": 12,
    "title": "From Megawatts to Tokens: How NVIDIA Maximizes AI Factory Production",
    "slug": "ai-from-megawatts-to-tokens-how-nvidia-maximizes-ai-factory-production",
    "category": "AI",
    "source": "NVIDIA",
    "score": 9.1,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because advanced civilization depends on the ability to convert knowledge into reproducible material capability, reliable production, and resilient supply systems.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  }
];
