export const senateAgenda =
[
  {
    "id": "agenda-1",
    "rank": 1,
    "title": "Generative data assimilation highlights fronts as key regulators of ocean energy cascade",
    "slug": "energy-generative-data-assimilation-highlights-fronts-as-key-regulators-of-ocean-energy",
    "category": "Energy",
    "source": "arXiv Physics",
    "score": 9.7,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Should ArcheNova prioritize this energy capability?",
    "whyItMatters": "This matters because biological engineering can reshape food security, medicine, agriculture, manufacturing, ecological resilience, and civilization’s relationship with living systems.",
    "architectureHandoff": "Civilization Energy Architecture",
    "status": "Open"
  },
  {
    "id": "agenda-2",
    "rank": 2,
    "title": "NRO to expand use of HawkEye 360’s satellite intelligence",
    "slug": "space-nro-to-expand-use-of-hawkeye-360-s-satellite-intelligence",
    "category": "Space",
    "source": "SpaceNews",
    "score": 9.6,
    "priority": "Critical",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-3",
    "rank": 3,
    "title": "NASA Student Aviation Challenge Focuses on Nation’s Infrastructure",
    "slug": "ai-nasa-student-aviation-challenge-focuses-on-nation-s-infrastructure",
    "category": "AI",
    "source": "NASA",
    "score": 9.4,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-4",
    "rank": 4,
    "title": "NASA's LRO images Falcon 9 crater on moon, learns new details",
    "slug": "ai-nasa-s-lro-images-falcon-9-crater-on-moon-learns-new-details",
    "category": "AI",
    "source": "Phys.org",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-5",
    "rank": 5,
    "title": "NASA’s LRO Images Falcon 9 Crater on Moon, Learns New Details",
    "slug": "ai-nasa-s-lro-images-falcon-9-crater-on-moon-learns-new-details",
    "category": "AI",
    "source": "NASA",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-6",
    "rank": 6,
    "title": "NASA’s B777 Gets New Coat of Paint",
    "slug": "ai-nasa-s-b777-gets-new-coat-of-paint",
    "category": "AI",
    "source": "NASA",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-7",
    "rank": 7,
    "title": "NASA Glenn’s Legacy Forged Through Decades of Flight Research",
    "slug": "ai-nasa-glenn-s-legacy-forged-through-decades-of-flight-research",
    "category": "AI",
    "source": "NASA",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-8",
    "rank": 8,
    "title": "What Spider-Man gets right — and wrong — about turning off superpowers",
    "slug": "energy-what-spider-man-gets-right-and-wrong-about-turning-off-superpowers",
    "category": "Energy",
    "source": "Science News",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Should ArcheNova prioritize this energy capability?",
    "whyItMatters": "This matters because biological engineering can reshape food security, medicine, agriculture, manufacturing, ecological resilience, and civilization’s relationship with living systems.",
    "architectureHandoff": "Civilization Energy Architecture",
    "status": "Open"
  },
  {
    "id": "agenda-9",
    "rank": 9,
    "title": "Eoptic, Inc. Selected to Supply DeepScan™ Imaging Payloads Scheduled for Launch in 2027",
    "slug": "space-eoptic-inc-selected-to-supply-deepscan-imaging-payloads-scheduled-for-launch-in-",
    "category": "Space",
    "source": "SpaceNews",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-10",
    "rank": 10,
    "title": "New report takes closer look at the Space Force spending surge",
    "slug": "space-new-report-takes-closer-look-at-the-space-force-spending-surge",
    "category": "Space",
    "source": "SpaceNews",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-11",
    "rank": 11,
    "title": "The role of the astronaut is in flux",
    "slug": "space-the-role-of-the-astronaut-is-in-flux",
    "category": "Space",
    "source": "MIT Technology Review",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "Does this capability expand civilization beyond Earth?",
    "whyItMatters": "This matters because space systems expand civilization’s ability to observe Earth, coordinate infrastructure, extend communications, and build long-term expansion pathways.",
    "architectureHandoff": "Orbital Infrastructure",
    "status": "Open"
  },
  {
    "id": "agenda-12",
    "rank": 12,
    "title": "Statistical validation of calorimeter inpainting with generative diffusion priors",
    "slug": "ai-statistical-validation-of-calorimeter-inpainting-with-generative-diffusion-prior",
    "category": "AI",
    "source": "arXiv Physics",
    "score": 9.3,
    "priority": "High",
    "stage": "Open Deliberation",
    "constitutionalQuestion": "How should this intelligence capability be governed?",
    "whyItMatters": "This matters because biological engineering can reshape food security, medicine, agriculture, manufacturing, ecological resilience, and civilization’s relationship with living systems.",
    "architectureHandoff": "Intelligence Infrastructure",
    "status": "Open"
  }
];
