"use client";

import Link from "next/link";
import { useEffect, useId, useRef, useState, type ReactNode } from "react";

/* ============================================================
   ARCHENOVA / HUMANITY & RESPONSIBILITY
   Route: /humanity-responsibility
   Independent, self-contained research exhibition.

   EVIDENCE BOUNDARY
   This page proposes a research and engineering framework.
   Its equations are definitions or design criteria, not newly
   discovered physical laws or experimentally validated metrics.
   Conceptual SVG artwork is not scientific data.
============================================================ */

type Inquiry = {
  id: string;
  number: string;
  name: string;
  domain: string;
  question: string;
  premise: string;
  mechanism: string;
  failure: string;
  test: string;
  evidence: string;
  horizon: string;
};

const INQUIRIES: Inquiry[] = [
  {
    id: "intelligence", number: "01", name: "Intelligence", domain: "COGNITIVE INFRASTRUCTURE",
    question: "Can intelligence become more capable without becoming less contestable?",
    premise: "A system may generate useful answers or perform complex tasks while remaining unreliable outside the conditions in which it was evaluated. Fluency, benchmark performance, and authorization are different things.",
    mechanism: "Separate source evidence, model inference, tool execution, and human approval. Preserve provenance, bounded permissions, observable action logs, independent evaluations, and a usable interruption path.",
    failure: "An unsupported inference becomes an operational decision; delegated authority expands faster than oversight; an incorrect output is repeatedly treated as established context.",
    test: "Introduce contradictory evidence and an out-of-distribution task. Can independent reviewers identify the unsupported claim, halt consequential action, and verify a corrected result?",
    evidence: "Task-specific evaluations, calibrated uncertainty, reproducible incident tests, authorization records, and measured correction latency—not conversational persuasiveness.",
    horizon: "Retain human agency and the ability to replace or retire a system as its capabilities, users, and operating conditions change.",
  },
  {
    id: "energy", number: "02", name: "Energy", domain: "ENERGY DYNAMICS",
    question: "Who remains responsible when energy infrastructure outlives its original operators?",
    premise: "Energy systems are physical systems: failures can propagate through equipment, ecosystems, supply chains, and communities. Different technologies have different hazards, operating lives, and end-of-life obligations.",
    mechanism: "Define the safety case, credible failure scenarios, monitoring requirements, maintenance capacity, emergency response, decommissioning route, and funded stewardship before expanding deployment.",
    failure: "The project remains productive while its monitoring, spare parts, institutional knowledge, or end-of-life resources disappear. A low-probability event exceeds available recovery capacity.",
    test: "Simulate loss of power, personnel, monitoring, funding, and access. Which essential safety functions remain available, for how long, and under whose authority?",
    evidence: "Measured reliability, independent safety review, scenario-specific emergency exercises, lifecycle cost estimates, and auditable stewardship arrangements.",
    horizon: "Make obligations transferable and inspectable across changes of ownership, technology, regulation, and generation.",
  },
  {
    id: "life", number: "03", name: "Life", domain: "BIOSYSTEMS",
    question: "Can intervention in living systems remain bounded when biology adapts?",
    premise: "Living systems evolve, interact, and respond to context. A result observed in a controlled setting may not generalize to another population, ecosystem, or time horizon.",
    mechanism: "Define the intervention boundary, causal hypothesis, exposure pathway, monitoring method, containment strategy, stopping rule, and independent ethical and safety review appropriate to the application.",
    failure: "A local benefit obscures delayed harm; an intervention reaches an unintended population; the system changes faster than the monitoring model can detect.",
    test: "Which observations would falsify the claimed benefit or indicate unacceptable spread? Can the intervention be stopped, contained, or mitigated under plausible adverse conditions?",
    evidence: "Appropriate controlled studies, replication, uncertainty analysis, surveillance, safety outcomes, and domain-specific regulatory review where required.",
    horizon: "Do not assume reversibility: some biological changes cannot be fully recalled. Prevention, containment, and long-term follow-up may matter more than recovery claims.",
  },
  {
    id: "infrastructure", number: "04", name: "Infrastructure", domain: "SPACETIME & CIVILIZATION SYSTEMS",
    question: "Can essential services survive the failure of the systems on which they depend?",
    premise: "Civilization relies on interconnected networks. Optimizing a component does not establish the resilience of the whole; common-mode failures can defeat apparently redundant pathways.",
    mechanism: "Map critical dependencies, identify minimum essential functions, diversify failure pathways, provide graceful degradation, rehearse restoration, and maintain replaceable components and human expertise.",
    failure: "A shared dependency disables multiple backups; restoration requires the very network that failed; a technically recoverable service is inaccessible to those who need it.",
    test: "Remove a critical node and then a shared dependency. Measure service continuity, restoration time, resource requirements, and unequal impacts across affected populations.",
    evidence: "Dependency maps, fault-injection results, restoration drills, independently audited maintenance records, and service-level outcomes during real incidents.",
    horizon: "Design for repair, migration, and eventual retirement rather than treating any single platform as permanent.",
  },
  {
    id: "governance", number: "05", name: "Governance", domain: "CIVILIZATION INTELLIGENCE",
    question: "Can institutions revise commitments after the evidence or the people in charge change?",
    premise: "A technically functioning system can still produce harmful outcomes when incentives, authority, accountability, or public participation are misaligned. Technical validation does not confer social permission.",
    mechanism: "Make mandates explicit; separate operators from independent oversight; establish appeal, disclosure, review, sunset, and succession mechanisms; define who bears residual risk and who may stop deployment.",
    failure: "Responsibility is diffused across contractors and generations; affected communities cannot contest decisions; an institution preserves a failing system because exit is politically or financially difficult.",
    test: "After a leadership change and a credible adverse finding, can an independent body obtain evidence, suspend the activity, provide remedy, and revise or terminate the mandate?",
    evidence: "Published decision records, independent audits, tested appeal procedures, enforceable responsibilities, and documented outcomes for affected people.",
    horizon: "Preserve accountability across institutional succession without assuming that one governance model fits every jurisdiction or domain.",
  },
];

const CAPACITIES = [
  { number: "01", title: "Observe", detail: "Detect consequential behavior and emerging failures before the opportunity to respond closes.", proof: "Coverage, detection delay, false-negative analysis, and independent access to measurements." },
  { number: "02", title: "Understand", detail: "Distinguish observations from models, assumptions, forecasts, and unresolved alternatives.", proof: "Traceable claims, calibrated uncertainty, discriminating tests, and documented model limits." },
  { number: "03", title: "Challenge", detail: "Allow affected people and independent institutions to inspect and contest consequential decisions.", proof: "Accessible records, meaningful review authority, appeal routes, and protection against conflicts of interest." },
  { number: "04", title: "Interrupt", detail: "Contain unsafe behavior before it crosses a defined harm or irreversibility threshold.", proof: "Tested stop conditions, intervention latency, safe-state behavior, and authority to act." },
  { number: "05", title: "Recover", detail: "Restore essential function or provide a viable alternative when prevention fails.", proof: "Restoration drills, replacement pathways, resource reserves, and explicit limits where recovery is impossible." },
  { number: "06", title: "Remain accountable", detail: "Keep obligations, evidence, and remedies available beyond the original creators and operators.", proof: "Named duty holders, funded stewardship, succession rules, records retention, and independent review." },
] as const;

const GATES = [
  { id: "claim", title: "01 / Define the claim", question: "What exactly is being proposed?", method: "Specify the intended benefit, affected population, operating boundary, alternatives, and plausible harms. Distinguish a demonstrated result from a hypothesis or design ambition.", advance: "The claim can be independently examined and at least one outcome could count against it." },
  { id: "discriminate", title: "02 / Discriminate", question: "What would change our conclusion?", method: "Identify rival explanations, measurement bias, missing populations, and observations that could falsify the preferred account. Predefine consequential thresholds where feasible.", advance: "The proposed test can distinguish the claim from credible alternatives within stated uncertainty." },
  { id: "reproduce", title: "03 / Reproduce", question: "Does the result survive variation?", method: "Repeat under relevant conditions and independent scrutiny. Measure not only average performance but failure tails, uncertainty, and dependence on particular people or equipment.", advance: "Evidence supports the specified operating range; remaining uncertainty is visible rather than silently averaged away." },
  { id: "control", title: "04 / Bound the capability", question: "Can adverse behavior be stopped?", method: "Test observability, interruption, containment, recovery, and authority under degraded conditions. Where harm is irreversible, prioritize prevention and exposure limits.", advance: "Safeguards have been demonstrated for the proposed scope and credible failure scenarios." },
  { id: "steward", title: "05 / Sustain responsibility", question: "Who carries the obligation tomorrow?", method: "Assign maintenance, monitoring, funding, disclosure, remedy, and end-of-life duties across ownership and institutional change.", advance: "Responsible parties, resources, review dates, and a viable succession or exit plan are documented." },
  { id: "scale", title: "06 / Reauthorize scale", question: "What justifies the next increase?", method: "Reassess the safety case when deployment, autonomy, exposure, interdependence, or time horizon increases. Require new evidence rather than extrapolating from a smaller demonstration.", advance: "The next scale remains within demonstrated oversight and harm-management capacity." },
] as const;

const HORIZONS = [
  { period: "IMMEDIATE", label: "Seconds → days", issue: "Intervention latency", detail: "A system may cause harm faster than a human can observe or interrupt it. Automation, interlocks, and bounded authority must be matched to the actual response window." },
  { period: "OPERATIONAL", label: "Months → decades", issue: "Maintenance and drift", detail: "Components age, data distributions shift, operators change, and institutional attention fades. Monitoring and corrective capacity must be maintained rather than assumed." },
  { period: "INTERGENERATIONAL", label: "Decades → centuries", issue: "Succession and stewardship", detail: "Some infrastructure and environmental effects persist beyond the organizations that created them. Knowledge, resources, duties, and public scrutiny need durable transfer mechanisms." },
  { period: "IRREVERSIBLE", label: "No reliable recovery horizon", issue: "Prevention before commitment", detail: "Extinction, permanent ecological loss, and some long-lived harms cannot be treated as ordinary repairable failures. The appropriate response may be non-deployment or a strictly bounded experiment." },
] as const;

function Arrow({ diagonal = false }: { diagonal?: boolean }) {
  return <svg viewBox="0 0 24 24" fill="none" aria-hidden="true" className="hr-arrow"><path d={diagonal ? "M5 19 19 5 M8 5h11v11" : "M3 12h17 m-7-7 7 7-7 7"} /></svg>;
}

function Glass({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`hr-glass ${className}`}>{children}</div>;
}

function Reveal({ children, className = "" }: { children: ReactNode; className?: string }) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const node = ref.current;
    if (!node) return;
    if (!("IntersectionObserver" in window) || window.matchMedia("(prefers-reduced-motion: reduce)").matches) { setVisible(true); return; }
    const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect(); } }, { threshold: 0.04, rootMargin: "0px 0px 90px 0px" });
    observer.observe(node);
    return () => observer.disconnect();
  }, []);
  return <div ref={ref} className={`hr-reveal ${visible ? "is-visible" : ""} ${className}`}>{children}</div>;
}

function random(index: number, seed: number) {
  const value = Math.sin(index * 127.1 + seed * 311.7) * 43758.5453;
  return value - Math.floor(value);
}

/* Deterministic, decorative SVG: no external images, canvas, or network calls. */
function Cosmos({ compact = false }: { compact?: boolean }) {
  const uid = useId().replace(/:/g, "");
  const stars = Array.from({ length: compact ? 95 : 230 }, (_, i) => ({ x: random(i, 7) * 1440, y: random(i, 8) * 1000, r: 0.35 + random(i, 9) * 1.25, opacity: 0.13 + random(i, 10) * 0.55 }));
  return <svg className={`hr-cosmos ${compact ? "hr-cosmos--compact" : ""}`} viewBox="0 0 1440 1000" preserveAspectRatio="xMidYMid slice" aria-hidden="true" focusable="false">
    <defs>
      <radialGradient id={`${uid}-void`} cx="67%" cy="46%" r="58%"><stop offset="0%" stopColor="#27323c" stopOpacity=".37"/><stop offset="49%" stopColor="#101820" stopOpacity=".15"/><stop offset="100%" stopColor="#030406" stopOpacity="0"/></radialGradient>
      <radialGradient id={`${uid}-planet`} cx="32%" cy="28%" r="78%"><stop offset="0%" stopColor="#536b7b" stopOpacity=".68"/><stop offset="29%" stopColor="#243543" stopOpacity=".62"/><stop offset="66%" stopColor="#0b1219" stopOpacity=".91"/><stop offset="100%" stopColor="#020306"/></radialGradient>
      <linearGradient id={`${uid}-arc`} x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#c9d5e0" stopOpacity="0"/><stop offset="48%" stopColor="#c9d5e0" stopOpacity=".42"/><stop offset="100%" stopColor="#c9d5e0" stopOpacity="0"/></linearGradient>
      <filter id={`${uid}-glow`}><feGaussianBlur stdDeviation="18"/></filter>
    </defs>
    <rect width="1440" height="1000" fill={`url(#${uid}-void)`}/>
    <g className="hr-cosmos__stars">{stars.map((star, i) => <circle key={i} cx={star.x} cy={star.y} r={star.r} fill="#e4edf5" opacity={star.opacity}/>)}</g>
    <g className="hr-cosmos__orbit" fill="none" stroke={`url(#${uid}-arc)`}>
      <ellipse cx="1050" cy="540" rx="620" ry="238" transform="rotate(-29 1050 540)" strokeWidth="1"/>
      <ellipse cx="1050" cy="540" rx="670" ry="270" transform="rotate(-29 1050 540)" strokeWidth=".6" opacity=".55"/>
      <ellipse cx="1050" cy="540" rx="730" ry="305" transform="rotate(-29 1050 540)" strokeWidth=".5" opacity=".35"/>
    </g>
    <circle cx="1090" cy="565" r="325" fill={`url(#${uid}-planet)`} opacity=".9"/>
    <circle cx="1090" cy="565" r="327" fill="none" stroke="#b5c8d8" strokeOpacity=".24" strokeWidth="2"/>
    <path d="M 802 420 A 325 325 0 0 1 1320 335" fill="none" stroke="#bed1df" strokeOpacity=".36" strokeWidth="15" filter={`url(#${uid}-glow)`}/>
    <path d="M 802 420 A 325 325 0 0 1 1320 335" fill="none" stroke="#d7e5ee" strokeOpacity=".34" strokeWidth="1"/>
    <path d="M0 830 C320 710 450 980 720 855 S1120 755 1440 885" fill="none" stroke="#9db4c8" strokeOpacity=".11" strokeWidth="1"/>
  </svg>;
}

function SectionHead({ index, label, title, muted, children }: { index: string; label: string; title: string; muted?: string; children: ReactNode }) {
  return <Reveal><div className="hr-section-head"><p className="hr-kicker">{index} / {label}</p><h2 className="hr-display">{title}{muted && <><br/><span>{muted}</span></>}</h2><p className="hr-section-lead">{children}</p></div></Reveal>;
}

function InquiryPanel() {
  const [active, setActive] = useState(0);
  const inquiry = INQUIRIES[active];
  return <div className="hr-inquiry-layout">
    <Reveal><nav className="hr-inquiry-nav" aria-label="Select a field of inquiry">{INQUIRIES.map((item, i) => <button type="button" key={item.id} onClick={() => setActive(i)} className={`hr-inquiry-tab ${active === i ? "is-active" : ""}`} aria-pressed={active === i} aria-controls="hr-inquiry-panel"><span className="hr-index">{item.number}</span><span><strong>{item.name}</strong><small>{item.domain}</small></span><Arrow diagonal/></button>)}</nav></Reveal>
    <Reveal><Glass className="hr-inquiry-panel"><div id="hr-inquiry-panel" key={inquiry.id} className="hr-panel-enter" aria-live="polite"><div className="hr-panel-meta"><span className="hr-small">FIELD {inquiry.number} / {inquiry.domain}</span><span className="hr-small">{inquiry.number} / 05</span></div><h3>{inquiry.question}</h3><p className="hr-panel-premise">{inquiry.premise}</p><div className="hr-inquiry-grid"><div><span className="hr-small">DESIGN RESPONSE</span><p>{inquiry.mechanism}</p></div><div><span className="hr-small">CREDIBLE FAILURE</span><p>{inquiry.failure}</p></div><div><span className="hr-small">DISCRIMINATING TEST</span><p>{inquiry.test}</p></div><div><span className="hr-small">REQUIRED EVIDENCE</span><p>{inquiry.evidence}</p></div></div><div className="hr-inquiry-horizon"><span className="hr-small">LONG-HORIZON OBLIGATION</span><p>{inquiry.horizon}</p></div></div></Glass></Reveal>
  </div>;
}

function Gates() {
  const [expanded, setExpanded] = useState<number | null>(0);
  return <Glass className="hr-gates">{GATES.map((gate, i) => { const open = expanded === i; return <div key={gate.id} className={`hr-gate ${open ? "is-open" : ""}`}><button type="button" className="hr-gate-trigger" aria-expanded={open} aria-controls={`hr-gate-${gate.id}`} onClick={() => setExpanded(open ? null : i)}><span className="hr-gate-count">{String(i + 1).padStart(2, "0")}</span><span><small>{gate.title}</small><strong>{gate.question}</strong></span><span className="hr-gate-symbol" aria-hidden="true">{open ? "−" : "+"}</span></button><div id={`hr-gate-${gate.id}`} className="hr-gate-detail" hidden={!open}><p>{gate.method}</p><div className="hr-gate-criterion"><span className="hr-small">ADVANCEMENT CONDITION / PROPOSED</span><p>{gate.advance}</p></div></div></div>; })}</Glass>;
}

export default function HumanityResponsibilityPage() {
  return <main className="hr" id="top">
    <div className="hr-atmosphere" aria-hidden="true"><Cosmos/><div className="hr-atmosphere__shade"/></div>
    <section className="hr-screen hr-hero" aria-labelledby="hr-title"><header className="hr-topbar"><Link href="/home/" className="hr-back hr-glass"><span aria-hidden="true">←</span><span>ARCHENOVA</span></Link><span className="hr-topbar-label">PERMANENT INQUIRY / HUMANITY & RESPONSIBILITY</span></header><div className="hr-hero-main"><Reveal><Glass className="hr-hero-copy"><p className="hr-kicker"><span className="hr-live-dot"/> THE QUESTION THAT OUTLIVES ITS ANSWERS</p><h1 id="hr-title">Can humanity<br/>remain <em>responsible</em><br/>for the power<br/>it creates?</h1><p className="hr-hero-lead">Humanity can increasingly alter matter, energy, intelligence, living systems, and the conditions of civilization. The ability to produce consequences is not the same as the ability to understand, limit, correct, or answer for them.</p><div className="hr-hero-actions"><a className="hr-button hr-button--light" href="#principle">ENTER THE INQUIRY <Arrow diagonal/></a><a className="hr-button hr-button--outline" href="#fields">EXPLORE FIVE FIELDS <Arrow/></a></div></Glass></Reveal></div><div className="hr-hero-bottom"><span>CONCEPTUAL COSMIC ART / NOT OBSERVATIONAL DATA</span><a href="#principle">SCROLL TO THE PRINCIPLE <span aria-hidden="true">↓</span></a></div></section>

    <section id="principle" className="hr-screen hr-principle" aria-labelledby="hr-principle-title"><div className="hr-inner hr-two-col"><div><Reveal><p className="hr-kicker">01 / THE FUNDAMENTAL DISTINCTION</p><h2 id="hr-principle-title" className="hr-display">Power is not<br/><span>responsibility.</span></h2><p className="hr-section-lead">A capability can be scientifically plausible, technically functional, and economically attractive while its consequences remain poorly understood or difficult to reverse. Responsible deployment therefore requires evidence about the entire system—not only its intended performance.</p></Reveal></div><Reveal><Glass className="hr-principle-card"><span className="hr-small">A RESEARCH PROPOSITION / NOT A PHYSICAL LAW</span><div className="hr-equation"><span>Capability</span><b>≠</b><span>Control</span><b>≠</b><span>Authority</span><b>≠</b><span>Responsibility</span></div><div className="hr-principle-divider"/><p><strong>Capability</strong> describes what a system can do. <strong>Control</strong> concerns whether its behavior can be bounded. <strong>Authority</strong> concerns who may permit its use. <strong>Responsibility</strong> concerns who must answer for its effects and maintain the means to respond when things go wrong.</p><p className="hr-card-foot">No one distinction automatically establishes the next.</p></Glass></Reveal></div></section>

    <section className="hr-screen hr-thesis" aria-labelledby="hr-thesis-title"><div className="hr-inner"><SectionHead index="02" label="THE CENTRAL THESIS" title="Responsibility is a" muted="continuous capability.">It is not a statement of good intentions, a one-time approval, or a promise made at launch. It is a set of operational capacities that must remain effective as a system, its environment, and its consequences change.</SectionHead><div className="hr-capacity-grid">{CAPACITIES.map(item => <Reveal key={item.number}><Glass className="hr-capacity-card"><span className="hr-small">{item.number} / 06</span><h3>{item.title}</h3><p>{item.detail}</p><div className="hr-capacity-proof"><span className="hr-small">WHAT TO DEMONSTRATE</span><p>{item.proof}</p></div></Glass></Reveal>)}</div><Reveal><Glass className="hr-thesis-note"><span className="hr-small">THE NON-SUBSTITUTION RULE</span><p>Strong performance in one capacity cannot automatically compensate for the absence of another. A system that is easy to observe but impossible to stop is not thereby controllable; a system that can be stopped but leaves irreversible harm is not thereby recoverable.</p></Glass></Reveal></div></section>

    <section id="fields" className="hr-screen hr-fields" aria-labelledby="hr-fields-title"><div className="hr-inner"><SectionHead index="03" label="FIVE FIELDS OF INQUIRY" title="One permanent question." muted="Five forms of power.">The same responsibility problem takes different physical, technical, and institutional forms. Select a field to examine its causal assumptions, plausible failures, discriminating tests, evidence requirements, and long-horizon obligations.</SectionHead><InquiryPanel/></div></section>

    <section className="hr-screen hr-model" aria-labelledby="hr-model-title"><div className="hr-inner hr-two-col hr-two-col--model"><Reveal><div><p className="hr-kicker">04 / A TESTABLE DESIGN LANGUAGE</p><h2 id="hr-model-title" className="hr-display">Measure the<br/><span>gap.</span></h2><p className="hr-section-lead">A responsible design must compare the rate and reach of consequential action with the actual capacity to observe, interrupt, and mitigate it. The expressions below are proposed engineering diagnostics. Their variables and thresholds must be operationalized separately for each domain.</p><p className="hr-model-caution">These expressions are not universal safety guarantees, empirically established constants, or substitutes for domain-specific risk analysis.</p></div></Reveal><Reveal><Glass className="hr-model-card"><span className="hr-small">01 / RESPONSE-WINDOW CONDITION</span><div className="hr-math">τ<sub>detect</sub> + τ<sub>decide</sub> + τ<sub>act</sub> &lt; τ<sub>harm</sub></div><p>The combined time to detect, decide, and intervene should be shorter than the time available before unacceptable harm, with an appropriate margin for uncertainty. If that cannot be demonstrated, reduce exposure, autonomy, or operating scope.</p><div className="hr-model-rule"/><span className="hr-small">02 / SCALE-CONSTRAINT PROPOSITION</span><div className="hr-math hr-math--text">Permissible scale ≤ Demonstrated capacity to oversee and respond</div><p>Expansion should be conditional on evidence that monitoring, intervention, recovery where feasible, and accountable governance remain effective at the proposed scale. This is a design principle, not a single scalar quantity.</p><div className="hr-model-rule"/><span className="hr-small">03 / IRREVERSIBILITY BOUNDARY</span><div className="hr-math hr-math--text">Irreversible harm → Stronger prevention and narrower exposure</div><p>When restoration cannot credibly be demonstrated, a recovery plan must not be used to justify exposure. The decision may require redesign, a smaller experiment, or non-deployment.</p></Glass></Reveal></div></section>

    <section id="gates" className="hr-screen hr-validation" aria-labelledby="hr-validation-title"><div className="hr-inner hr-two-col hr-two-col--validation"><Reveal><div><p className="hr-kicker">05 / THE EVIDENCE-TO-AUTHORITY PATH</p><h2 id="hr-validation-title" className="hr-display">No scale<br/><span>without a gate.</span></h2><p className="hr-section-lead">A proposed sequence for moving from an idea to consequential deployment. These are evaluation gates, not a claim that ArcheNova has completed them or that one procedure fits every field.</p><Glass className="hr-side-note"><span className="hr-small">THE QUESTION AT EVERY GATE</span><p>What evidence would justify the next commitment—and what result would require us to stop, revise, or withdraw it?</p></Glass></div></Reveal><Reveal><Gates/></Reveal></div></section>

    <section className="hr-screen hr-horizon" aria-labelledby="hr-horizon-title"><div className="hr-inner"><SectionHead index="06" label="THE LONG HORIZON" title="Consequences outlive" muted="their creators.">The relevant timescale is not the duration of a launch, a product cycle, or an institution's mandate. It is the duration of the consequence and the period over which meaningful stewardship must remain possible.</SectionHead><div className="hr-horizon-grid">{HORIZONS.map((item, i) => <Reveal key={item.period}><Glass className="hr-horizon-card"><div className="hr-horizon-top"><span className="hr-small">0{i + 1} / {item.period}</span><span className="hr-horizon-line"/></div><span className="hr-horizon-period">{item.label}</span><h3>{item.issue}</h3><p>{item.detail}</p></Glass></Reveal>)}</div><Reveal><Glass className="hr-horizon-statement"><span className="hr-small">INTERGENERATIONAL RESPONSIBILITY</span><p>Transfer the capacity to know what was built, why it was authorized, how it can fail, who is obligated to act, and what resources remain available for maintenance, remedy, replacement, or safe closure.</p></Glass></Reveal></div></section>

    <section className="hr-screen hr-case" aria-labelledby="hr-case-title"><div className="hr-inner hr-two-col"><Reveal><div><p className="hr-kicker">07 / THE COUNTERFACTUAL TEST</p><h2 id="hr-case-title" className="hr-display">Design for<br/><span>the day after.</span></h2><p className="hr-section-lead">A system should not be judged solely by how it performs when its creators, funding, infrastructure, and assumptions remain intact. The harder question is whether its responsibilities can still be discharged after those supports change.</p></div></Reveal><Reveal><Glass className="hr-case-card"><span className="hr-small">A SCENARIO TO TEST / NOT A REPORTED EVENT</span><h3>The original operator disappears.</h3><p>A consequential system remains in use. Its original team is gone, its records are incomplete, an essential supplier has failed, and a previously unknown hazard has emerged.</p><div className="hr-case-questions"><p><span>01</span> Who can establish what the system is doing?</p><p><span>02</span> Who has authority and resources to intervene?</p><p><span>03</span> Can essential functions continue through an alternative pathway?</p><p><span>04</span> Who provides remedy if harm cannot be reversed?</p><p><span>05</span> What evidence would justify continued operation—or closure?</p></div><p className="hr-case-ending">If these questions have no credible answer, the original deployment plan has an unresolved responsibility gap.</p></Glass></Reveal></div></section>

    <section className="hr-screen hr-boundaries" aria-labelledby="hr-boundaries-title"><div className="hr-inner"><SectionHead index="08" label="EVIDENCE & LIMITS" title="A framework must also" muted="answer to reality.">The concepts on this page are proposed principles for inquiry and design. Their usefulness depends on whether they improve real decisions under specified conditions and survive independent challenge.</SectionHead><div className="hr-boundary-grid"><Reveal><Glass className="hr-boundary-card"><span className="hr-small">PRESENTED HERE</span><h3>A structured research proposition</h3><p>Definitions, domain-specific questions, candidate design constraints, and a proposed sequence of validation and stewardship gates.</p></Glass></Reveal><Reveal><Glass className="hr-boundary-card"><span className="hr-small">REQUIRES VALIDATION</span><h3>Operational effectiveness</h3><p>Each application requires measurable variables, comparison with existing methods, failure testing, relevant expert review, and evidence from actual operating conditions.</p></Glass></Reveal><Reveal><Glass className="hr-boundary-card"><span className="hr-small">NOT CLAIMED</span><h3>A universal law or proof of safety</h3><p>No equation here establishes a new physical law, guarantees the absence of harm, or proves that every technology can be made reversible or fully governable.</p></Glass></Reveal></div></div></section>

    <section className="hr-screen hr-closing" aria-labelledby="hr-closing-title"><div className="hr-closing-art" aria-hidden="true"><Cosmos compact/></div><div className="hr-inner hr-closing-inner"><Reveal><Glass className="hr-closing-glass"><p className="hr-kicker">ARCHENOVA / PERMANENT INQUIRY</p><h2 id="hr-closing-title">The question<br/><span>remains open.</span></h2><p>Every new capability changes what humanity can do. It also changes what must be observed, challenged, bounded, sustained, and—when necessary—refused. Responsibility is not the end of discovery. It is a condition for carrying its consequences into the future.</p><div className="hr-closing-actions"><Link href="/home/" className="hr-button hr-button--light">RETURN TO ARCHENOVA <Arrow diagonal/></Link><a href="#top" className="hr-button hr-button--outline">REVISIT THE QUESTION <span aria-hidden="true">↑</span></a></div></Glass></Reveal></div></section>
    <footer className="hr-footer"><span>ARCHENOVA / HUMANITY & RESPONSIBILITY</span><span>REALITY · CAPABILITY · CORRECTABILITY · STEWARDSHIP</span></footer>

    <style jsx global>{`
      html:has(.hr), body:has(.hr){margin:0!important;padding:0!important;width:100%!important;max-width:none!important;background:#030406!important;scroll-behavior:smooth}
      body:has(.hr){overflow-x:clip!important}
      body:has(.hr) .site-header{display:none!important}
      body:has(.hr) .site-content{position:relative!important;z-index:1!important;display:block!important;width:100%!important;min-width:0!important;max-width:none!important;min-height:100svh!important;margin:0!important;padding:0!important;border:0!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;transform:none!important;overflow:visible!important}
      body:has(.hr) .site-content::before,body:has(.hr) .site-content::after{display:none!important}
      .hr,.hr *,.hr *::before,.hr *::after{box-sizing:border-box}
      .hr{--hr-white:rgba(249,251,253,.97);--hr-muted:rgba(231,237,244,.77);--hr-faint:rgba(225,234,243,.55);--hr-line:rgba(233,241,249,.15);--hr-side:clamp(16px,4.1vw,76px);--hr-block:clamp(75px,10vw,156px);position:relative;isolation:isolate;width:100%;min-width:0;min-height:100svh;overflow-x:clip;background:#030406;color:var(--hr-white);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text","Helvetica Neue",Arial,sans-serif;-webkit-font-smoothing:antialiased}
      .hr a{color:inherit;text-decoration:none;-webkit-tap-highlight-color:transparent}.hr button{font:inherit;-webkit-tap-highlight-color:transparent}.hr a:focus-visible,.hr button:focus-visible{outline:2px solid #e7f0f8;outline-offset:4px}.hr a,.hr button,.hr h1,.hr h2,.hr h3,.hr p,.hr span,.hr strong{min-width:0}.hr p{overflow-wrap:break-word}
      .hr-atmosphere{position:absolute;z-index:-1;inset:0;overflow:hidden;pointer-events:none;background:radial-gradient(ellipse at 76% 12%,rgba(44,58,69,.28),transparent 35%),radial-gradient(ellipse at 12% 65%,rgba(29,36,47,.21),transparent 35%),#030406}.hr-atmosphere>.hr-cosmos{position:absolute;top:0;left:0;width:100%;height:min(130svh,1100px);opacity:.92}.hr-atmosphere__shade{position:absolute;inset:0;background:linear-gradient(180deg,transparent 0%,#030406 18%,rgba(3,4,6,.95) 35%,#030406 100%)}
      .hr-cosmos{display:block;width:100%;height:100%;pointer-events:none}.hr-cosmos__orbit{transform-origin:1050px 540px;animation:hrOrbit 55s linear infinite}.hr-cosmos__stars{animation:hrStars 11s ease-in-out infinite alternate}@keyframes hrOrbit{to{transform:rotate(6deg)}}@keyframes hrStars{to{opacity:.65}}
      .hr-screen{position:relative;display:flex;flex-direction:column;justify-content:center;width:100%;min-height:100svh;padding:var(--hr-block) var(--hr-side);scroll-margin-top:0;background:transparent}.hr-inner{width:100%;min-width:0;max-width:1680px;margin-inline:auto}.hr-kicker,.hr-small{font-size:10px;font-weight:600;line-height:1.6;letter-spacing:.16em}.hr-kicker{margin:0 0 clamp(19px,3vw,39px);color:var(--hr-faint)}.hr-small{color:var(--hr-faint)}.hr-display{margin:0;font-size:clamp(43px,7.3vw,116px);font-weight:500;line-height:1.065;letter-spacing:-.075em;overflow-wrap:break-word}.hr-display span{color:rgba(224,234,245,.48)}.hr-section-lead{max-width:790px;margin:clamp(24px,3vw,42px) 0 0;color:var(--hr-muted);font-size:clamp(15px,1.35vw,20px);line-height:1.85}.hr-section-head{margin-bottom:clamp(35px,5vw,75px)}
      .hr-glass{position:relative;isolation:isolate;min-width:0;max-width:100%;overflow:hidden;border:1px solid rgba(231,240,250,.17);border-radius:clamp(20px,2.3vw,34px);background:linear-gradient(142deg,rgba(36,42,49,.43),rgba(12,16,22,.55) 49%,rgba(5,8,13,.65));-webkit-backdrop-filter:blur(25px) saturate(108%);backdrop-filter:blur(25px) saturate(108%);box-shadow:inset 0 1px 0 rgba(255,255,255,.08),0 26px 80px rgba(0,0,0,.18)}.hr-glass::before{content:"";position:absolute;z-index:-1;inset:0;border-radius:inherit;pointer-events:none;background:linear-gradient(145deg,rgba(255,255,255,.035),transparent 46%,rgba(255,255,255,.012))}
      .hr-reveal{width:100%;min-width:0;opacity:0;transform:translate3d(0,20px,0);transition:opacity .85s ease,transform 1s cubic-bezier(.16,1,.3,1)}.hr-reveal.is-visible{opacity:1;transform:none}.hr-arrow{flex:0 0 auto;width:19px;height:19px;stroke:currentColor;stroke-width:1.35;stroke-linecap:round;stroke-linejoin:round}
      .hr-hero{justify-content:space-between;gap:35px;min-height:100svh;padding-top:clamp(24px,4svh,55px);padding-bottom:clamp(22px,3svh,42px)}.hr-topbar,.hr-hero-bottom{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:15px}.hr-topbar{position:relative;z-index:2}.hr-back{display:inline-flex;align-items:center;gap:13px;min-height:45px;padding:10px 19px;border-radius:999px;font-size:10px;font-weight:650;letter-spacing:.13em}.hr-back>span:first-child{font-size:18px;font-weight:400}.hr-topbar-label,.hr-hero-bottom{color:var(--hr-faint);font-size:9px;letter-spacing:.13em;line-height:1.6}.hr-hero-main{width:100%;max-width:1680px;margin:auto}.hr-hero-copy{width:min(100%,1040px);padding:clamp(29px,4.8vw,82px)}.hr-live-dot{display:inline-block;width:6px;height:6px;margin-right:10px;border-radius:50%;background:#c6d9e8;box-shadow:0 0 13px rgba(204,225,243,.6);vertical-align:middle}.hr-hero h1{margin:0;font-size:clamp(48px,7.4vw,120px);font-weight:510;line-height:1.035;letter-spacing:-.077em;overflow-wrap:break-word}.hr-hero h1 em{font-style:normal;color:rgba(220,233,244,.54)}.hr-hero-lead{max-width:810px;margin:clamp(25px,3.2vw,48px) 0 0;color:var(--hr-muted);font-size:clamp(15px,1.4vw,21px);line-height:1.8}.hr-hero-actions,.hr-closing-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:clamp(26px,3vw,42px)}.hr-button{display:inline-flex;align-items:center;justify-content:space-between;gap:22px;min-height:55px;padding:14px 23px;border-radius:999px;font-size:10px;font-weight:650;letter-spacing:.1em;line-height:1.5;transition:transform .25s ease,border-color .25s ease,background .25s ease}.hr-button--light{background:rgba(246,249,252,.96);color:#0b1117!important}.hr-button--outline{border:1px solid rgba(234,242,251,.3);background:rgba(9,13,18,.35);color:var(--hr-white)!important;-webkit-backdrop-filter:blur(12px);backdrop-filter:blur(12px)}.hr-hero-bottom a{display:inline-flex;align-items:center;gap:13px;color:var(--hr-white)}.hr-hero-bottom a span{font-size:19px}
      .hr-two-col{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,.95fr);align-items:center;gap:clamp(30px,5vw,95px)}.hr-principle-card{padding:clamp(26px,3.6vw,62px)}.hr-equation{display:flex;align-items:center;flex-wrap:wrap;gap:10px 16px;margin:clamp(28px,3vw,43px) 0;font-size:clamp(20px,2.2vw,36px);font-weight:500;letter-spacing:-.045em;line-height:1.4}.hr-equation b{font-size:.7em;font-weight:400;color:var(--hr-faint)}.hr-principle-divider,.hr-model-rule{height:1px;background:var(--hr-line)}.hr-principle-card>p{margin:24px 0 0;color:var(--hr-muted);font-size:15px;line-height:1.85}.hr-principle-card>p strong{color:var(--hr-white);font-weight:550}.hr-principle-card .hr-card-foot{font-size:12px;color:var(--hr-faint)}
      .hr-capacity-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:clamp(12px,1.5vw,24px)}.hr-capacity-grid>.hr-reveal{height:100%}.hr-capacity-card{display:flex;flex-direction:column;height:100%;min-height:340px;padding:clamp(25px,2.7vw,45px)}.hr-capacity-card h3{margin:30px 0 16px;font-size:clamp(26px,2.6vw,42px);font-weight:490;letter-spacing:-.055em}.hr-capacity-card>p,.hr-capacity-proof p{margin:0;color:var(--hr-muted);font-size:14px;line-height:1.8}.hr-capacity-proof{margin-top:auto;padding-top:26px}.hr-capacity-proof .hr-small{display:block;padding-top:21px;border-top:1px solid var(--hr-line)}.hr-capacity-proof p{margin-top:10px;font-size:12px}.hr-thesis-note{margin-top:clamp(15px,2vw,27px);padding:clamp(25px,3vw,43px)}.hr-thesis-note p{max-width:1100px;margin:15px 0 0;font-size:clamp(17px,1.8vw,26px);line-height:1.65;letter-spacing:-.025em}
      .hr-inquiry-layout{display:grid;grid-template-columns:minmax(0,.62fr) minmax(0,1.38fr);align-items:start;gap:clamp(15px,2.5vw,38px)}.hr-inquiry-nav{display:grid;gap:10px}.hr-inquiry-tab{display:grid;grid-template-columns:24px minmax(0,1fr) 19px;align-items:center;width:100%;min-height:92px;gap:15px;padding:20px;border:1px solid var(--hr-line);border-radius:19px;background:rgba(19,25,32,.34);color:var(--hr-muted);text-align:left;cursor:pointer;transition:border-color .25s ease,background .25s ease,color .25s ease}.hr-inquiry-tab.is-active{border-color:rgba(230,240,250,.46);background:rgba(52,63,74,.42);color:#fff}.hr-inquiry-tab .hr-index{font-size:10px;color:var(--hr-faint)}.hr-inquiry-tab strong{display:block;font-size:clamp(18px,1.6vw,25px);font-weight:500;letter-spacing:-.035em}.hr-inquiry-tab small{display:block;margin-top:8px;color:var(--hr-faint);font-size:9px;letter-spacing:.09em;line-height:1.5}.hr-inquiry-panel{min-height:780px;padding:clamp(26px,3.4vw,57px)}.hr-panel-enter{animation:hrPanel .4s ease both}@keyframes hrPanel{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}.hr-panel-meta{display:flex;justify-content:space-between;flex-wrap:wrap;gap:12px}.hr-inquiry-panel h3{max-width:900px;margin:32px 0 20px;font-size:clamp(34px,3.9vw,65px);font-weight:490;line-height:1.12;letter-spacing:-.065em}.hr-panel-premise{max-width:900px;margin:0;color:var(--hr-muted);font-size:clamp(16px,1.45vw,21px);line-height:1.75}.hr-inquiry-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 28px;margin-top:33px;border-top:1px solid var(--hr-line)}.hr-inquiry-grid>div{padding:23px 0;border-bottom:1px solid var(--hr-line)}.hr-inquiry-grid p{margin:12px 0 0;color:var(--hr-muted);font-size:13px;line-height:1.85}.hr-inquiry-horizon{margin-top:30px;padding:clamp(20px,2.4vw,34px);border:1px solid var(--hr-line);border-radius:18px;background:rgba(255,255,255,.035)}.hr-inquiry-horizon p{margin:13px 0 0;font-size:clamp(16px,1.6vw,23px);line-height:1.6}
      .hr-model-card{padding:clamp(27px,3.5vw,59px)}.hr-math{margin:20px 0;font-size:clamp(23px,2.4vw,38px);line-height:1.55;letter-spacing:-.04em;overflow-wrap:anywhere}.hr-math sub{font-size:.48em;letter-spacing:0}.hr-math--text{font-size:clamp(19px,1.8vw,28px)}.hr-model-card>p{margin:0;color:var(--hr-muted);font-size:14px;line-height:1.85}.hr-model-rule{margin:30px 0}.hr-model-caution{max-width:690px;margin:25px 0 0;color:var(--hr-faint);font-size:12px;line-height:1.8}
      .hr-two-col--validation{grid-template-columns:minmax(0,.85fr) minmax(0,1.15fr)}.hr-side-note{margin-top:clamp(30px,4vw,60px);padding:clamp(23px,2.8vw,42px)}.hr-side-note p{margin:14px 0 0;font-size:clamp(17px,1.7vw,25px);line-height:1.65}.hr-gates{padding:clamp(20px,3vw,48px)}.hr-gate{border-top:1px solid var(--hr-line)}.hr-gate:first-child{border-top:0}.hr-gate-trigger{display:grid;grid-template-columns:25px minmax(0,1fr) 24px;align-items:center;width:100%;min-height:97px;gap:15px;padding:19px 0;border:0;background:transparent;color:var(--hr-white);text-align:left;cursor:pointer}.hr-gate-count{color:var(--hr-faint);font-size:10px}.hr-gate-trigger small{display:block;color:var(--hr-faint);font-size:9px;letter-spacing:.12em;line-height:1.5}.hr-gate-trigger strong{display:block;margin-top:8px;font-size:clamp(18px,1.7vw,26px);font-weight:500;line-height:1.35;letter-spacing:-.035em}.hr-gate-symbol{font-size:22px;font-weight:300;text-align:center}.hr-gate-detail{padding:0 0 26px 40px}.hr-gate-detail>p{margin:0;color:var(--hr-muted);font-size:14px;line-height:1.85}.hr-gate-criterion{margin-top:20px;padding:20px;border-radius:15px;background:rgba(255,255,255,.045)}.hr-gate-criterion p{margin:9px 0 0;font-size:13px;line-height:1.8}
      .hr-horizon-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:clamp(12px,1.5vw,23px)}.hr-horizon-grid>.hr-reveal{height:100%}.hr-horizon-card{height:100%;min-height:365px;padding:clamp(23px,2.5vw,40px)}.hr-horizon-top{display:flex;align-items:center;gap:15px}.hr-horizon-line{flex:1;height:1px;background:var(--hr-line)}.hr-horizon-period{display:block;margin-top:42px;color:var(--hr-faint);font-size:12px;letter-spacing:.04em}.hr-horizon-card h3{margin:16px 0 20px;font-size:clamp(23px,2.1vw,34px);font-weight:490;line-height:1.25;letter-spacing:-.045em}.hr-horizon-card p{margin:0;color:var(--hr-muted);font-size:13px;line-height:1.85}.hr-horizon-statement{margin-top:clamp(15px,2vw,27px);padding:clamp(26px,3.4vw,54px)}.hr-horizon-statement p{max-width:1180px;margin:16px 0 0;font-size:clamp(19px,2.1vw,32px);line-height:1.6;letter-spacing:-.035em}
      .hr-case-card{padding:clamp(27px,3.5vw,58px)}.hr-case-card h3{margin:26px 0 16px;font-size:clamp(30px,3.3vw,52px);font-weight:490;line-height:1.15;letter-spacing:-.055em}.hr-case-card>p{color:var(--hr-muted);font-size:14px;line-height:1.85}.hr-case-questions{margin:27px 0;border-top:1px solid var(--hr-line)}.hr-case-questions p{display:grid;grid-template-columns:26px minmax(0,1fr);gap:12px;margin:0;padding:16px 0;border-bottom:1px solid var(--hr-line);font-size:14px;line-height:1.7}.hr-case-questions span{color:var(--hr-faint);font-size:10px}.hr-case-card .hr-case-ending{margin:25px 0 0;color:var(--hr-white);font-size:clamp(17px,1.7vw,24px);line-height:1.6}
      .hr-boundary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:clamp(12px,1.5vw,24px)}.hr-boundary-grid>.hr-reveal{height:100%}.hr-boundary-card{height:100%;min-height:290px;padding:clamp(25px,2.8vw,45px)}.hr-boundary-card h3{margin:29px 0 18px;font-size:clamp(23px,2.3vw,35px);font-weight:490;line-height:1.25;letter-spacing:-.045em}.hr-boundary-card p{margin:0;color:var(--hr-muted);font-size:14px;line-height:1.85}
      .hr-closing{min-height:100svh;overflow:hidden}.hr-closing-art{position:absolute;inset:0;opacity:.48;pointer-events:none}.hr-closing-art::after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,4,6,.6),transparent 75%),linear-gradient(0deg,#030406,transparent 35%,transparent 70%,#030406)}.hr-closing-inner{position:relative;z-index:1}.hr-closing-glass{width:min(100%,1100px);padding:clamp(30px,5vw,83px)}.hr-closing h2{margin:0;font-size:clamp(48px,8vw,132px);font-weight:500;line-height:1.04;letter-spacing:-.078em}.hr-closing h2 span{color:rgba(224,234,245,.52)}.hr-closing-glass>p:not(.hr-kicker){max-width:820px;margin:clamp(25px,3vw,43px) 0 0;color:var(--hr-muted);font-size:clamp(16px,1.5vw,22px);line-height:1.8}.hr-footer{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:14px;padding:28px var(--hr-side) 36px;border-top:1px solid var(--hr-line);color:var(--hr-faint);font-size:9px;line-height:1.7;letter-spacing:.12em}
      @media(hover:hover){.hr-button:hover{transform:translateY(-2px)}.hr-button--light:hover{background:#fff}.hr-button--outline:hover{border-color:rgba(255,255,255,.6)}.hr-inquiry-tab:hover{border-color:rgba(231,240,250,.4);color:#fff}.hr-gate-trigger:hover strong{color:rgba(255,255,255,.75)}}
      @media(max-width:1100px){.hr-two-col,.hr-two-col--validation,.hr-inquiry-layout{grid-template-columns:minmax(0,1fr)}.hr-inquiry-nav{grid-template-columns:repeat(2,minmax(0,1fr))}.hr-capacity-grid,.hr-boundary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.hr-horizon-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.hr-inquiry-panel{min-height:0}}
      @media(max-width:760px){.hr{--hr-side:13px;--hr-block:clamp(66px,11svh,95px)}.hr-glass{border-radius:21px}.hr-kicker,.hr-small{font-size:9px;letter-spacing:.12em}.hr-display{font-size:clamp(41px,9.2vw,70px)}.hr-section-lead{font-size:14px}.hr-hero{padding-top:22px;padding-bottom:24px;gap:24px}.hr-topbar-label{display:none}.hr-hero-copy{padding:clamp(23px,5.5vw,36px)}.hr-hero h1{font-size:clamp(37px,9vw,68px);line-height:1.06}.hr-hero-lead{font-size:14px}.hr-hero-actions,.hr-closing-actions{flex-direction:column}.hr-button{width:100%;min-height:52px;font-size:9px}.hr-hero-bottom{font-size:8px;letter-spacing:.07em}.hr-principle-card,.hr-model-card,.hr-case-card{padding:25px}.hr-equation{font-size:23px}.hr-capacity-grid,.hr-boundary-grid,.hr-horizon-grid,.hr-inquiry-nav{grid-template-columns:minmax(0,1fr)}.hr-capacity-card,.hr-boundary-card,.hr-horizon-card{min-height:0;padding:26px}.hr-capacity-card h3{margin-top:18px}.hr-capacity-proof{margin-top:24px}.hr-inquiry-tab{min-height:68px;padding:15px}.hr-inquiry-tab strong{font-size:17px}.hr-inquiry-panel{padding:24px}.hr-inquiry-panel h3{font-size:clamp(30px,7.8vw,49px)}.hr-inquiry-grid{grid-template-columns:minmax(0,1fr)}.hr-inquiry-grid>div{padding:19px 0}.hr-inquiry-horizon{padding:20px}.hr-gates{padding:21px}.hr-gate-trigger{min-height:84px;gap:10px}.hr-gate-trigger strong{font-size:18px}.hr-gate-detail{padding-left:0}.hr-horizon-period{margin-top:24px}.hr-horizon-card h3{font-size:26px}.hr-closing-glass{padding:27px}.hr-closing h2{font-size:clamp(43px,10vw,76px)}.hr-footer{font-size:8px}}
      @media(max-width:390px){.hr{--hr-side:9px}.hr-hero h1{font-size:clamp(33px,8.6vw,43px)}.hr-hero-copy,.hr-inquiry-panel,.hr-gates{padding:20px}.hr-inquiry-tab{grid-template-columns:19px minmax(0,1fr) 17px;gap:10px}.hr-topbar{gap:9px}}
      @media(max-height:650px){.hr-hero{gap:18px}.hr-hero-main{margin:10px auto}.hr-hero-copy{padding:clamp(20px,3vw,42px)}.hr-hero h1{font-size:clamp(38px,6vw,75px)}}
      @media(prefers-reduced-motion:reduce){html:has(.hr){scroll-behavior:auto}.hr *,.hr *::before,.hr *::after{animation:none!important;transition:none!important}.hr-reveal{opacity:1!important;transform:none!important}}
    `}</style>
  </main>;
}
