"use client";

import Link from "next/link";
import {
  useEffect,
  useRef,
  useState,
  type ReactNode,
} from "react";

/* ============================================================
   ARCHENOVA / HUMANITY & RESPONSIBILITY

   Route:
     /humanity-responsibility

   DESIGN
   - Full-bleed, viewport-based research exhibition
   - Monochromatic, soft-black atmosphere
   - No narrow page-wide content frame
   - Individual research items receive their own space
   - Responsive desktop / tablet / mobile layouts
   - No external images or additional libraries

   EVIDENCE BOUNDARY
   The research architecture below is a proposal.
   Its criteria are design propositions, not newly discovered
   physical laws, completed experiments, or proof of safety.
============================================================ */

type Domain = {
  number: string;
  id: string;
  name: string;
  subtitle: string;
  question: string;
  abstract: string;
  causal: string;
  method: string;
  falsification: string;
  boundary: string;
  horizon: string;
  openProblem: string;
};

const DOMAINS: Domain[] = [
  {
    number: "01",
    id: "intelligence",
    name: "Intelligence",
    subtitle: "THE POWER TO REASON AND ACT",
    question:
      "Can increasingly capable intelligence remain understandable, contestable, and correctable?",
    abstract:
      "Intelligence becomes a responsibility problem when an inference can influence consequential action. A system may perform well on a defined evaluation while failing under unfamiliar conditions, ambiguous instructions, unreliable evidence, or expanded authority. Apparent competence does not establish that a conclusion is true, that an action is authorized, or that its consequences can be controlled.",
    causal:
      "The relevant unit of analysis is not the model alone. It is the complete causal pathway: source evidence → representation → inference → authorization → action → downstream consequence. Each transition introduces a different failure mode. An inaccurate source can produce a coherent answer; a correct answer can be used to justify an unauthorized action; an authorized action can produce an unacceptable outcome when the operating environment changes.",
    method:
      "Specify the intended task, operating conditions, affected parties, permitted actions, and independent intervention points. Evaluate unsupported claims, uncertainty communication, tool-use boundaries, escalation behavior, and the time required for an authorized reviewer to interrupt or reverse an action. Introduce contradictory evidence, distribution shifts, unavailable tools, and attempts to exceed delegated authority. Compare performance against a defined baseline rather than treating a persuasive demonstration as validation.",
    falsification:
      "The proposed control architecture fails its stated objective if consequential actions proceed without the required authorization, independent reviewers cannot reconstruct the evidential basis of a decision, or an identified unsafe action cannot be interrupted within the available response window.",
    boundary:
      "An explanation generated by a model is not necessarily a faithful account of its internal computation. A log is not equivalent to meaningful oversight. Human approval is not sufficient when the reviewer lacks time, information, authority, or a practical alternative.",
    horizon:
      "Preserve the ability to restrict, retrain, replace, or retire the system as its capabilities, dependencies, and uses change. Records and oversight procedures must remain interpretable beyond the original development team.",
    openProblem:
      "How can independent correction remain effective when a system's capabilities and operational reach evolve faster than the procedures used to evaluate them?",
  },
  {
    number: "02",
    id: "energy",
    name: "Energy",
    subtitle: "THE POWER OVER PHYSICAL SYSTEMS",
    question:
      "Can the benefits of powerful energy systems remain inseparable from long-term safety and stewardship?",
    abstract:
      "Energy infrastructure converts physical possibility into persistent societal dependence. Its benefits may be immediate, while some hazards, maintenance obligations, environmental effects, and end-of-life responsibilities extend far beyond the original investment horizon. A functioning installation is therefore not, by itself, evidence that its entire lifecycle is responsibly governed.",
    causal:
      "A credible safety argument must connect the physical system to its institutional support. Equipment depends on instrumentation, skilled operators, replacement parts, financing, emergency access, environmental monitoring, and accountable decision-making. The failure of one shared dependency may disable several apparently independent safeguards. Component reliability cannot be substituted for system-level resilience.",
    method:
      "Define the installation, operating envelope, hazard pathways, exposure scenarios, essential safety functions, and closure obligations. Construct a lifecycle safety case that includes construction, operation, maintenance, abnormal conditions, decommissioning, and post-closure stewardship where applicable. Stress-test the loss of external power, qualified personnel, monitoring, site access, funding, and critical suppliers. Establish who can act, with what resources, before a hazardous state is reached.",
    falsification:
      "The stewardship proposition is not supported if essential protective functions depend on an unavailable resource, credible failures propagate faster than intervention is possible, or the installation cannot meet its specified monitoring and closure obligations after a change of ownership or operator.",
    boundary:
      "Hazards differ substantially across energy technologies. No single generic safety model establishes the adequacy of a particular installation. Long-term performance requires application-specific evidence, qualified review, and reassessment when operating conditions change.",
    horizon:
      "Transfer the knowledge, resources, authority, and obligations necessary for safe operation and eventual closure. A project must not treat the disappearance of its original operator as the disappearance of its consequences.",
    openProblem:
      "What combination of technical safeguards, durable records, funded obligations, and institutional succession can maintain effective stewardship across multiple generations?",
  },
  {
    number: "03",
    id: "life",
    name: "Life",
    subtitle: "THE POWER TO ALTER LIVING SYSTEMS",
    question:
      "Can humanity intervene in living systems while preserving the capacity to detect, limit, and respond to unintended consequences?",
    abstract:
      "Living systems are adaptive, context-dependent, and interconnected. An intervention that produces a measurable benefit under controlled conditions may behave differently across populations, ecological relationships, or longer timescales. Biological responsibility therefore requires attention not only to intended function but also to exposure pathways, delayed effects, adaptation, and the limits of recall.",
    causal:
      "The causal boundary may extend beyond the treated organism or immediate recipient. Biological changes can interact with other organisms, environmental conditions, and selection pressures. A short observation window may detect the intended endpoint while missing a delayed or displaced adverse effect. Withdrawal of an intervention does not automatically restore the prior biological state.",
    method:
      "State the causal hypothesis, intended beneficiaries, relevant comparators, exposure boundary, monitoring sensitivity, and stopping conditions before intervention. Distinguish treatment effects from confounding, selection bias, and natural adaptation. Assess plausible routes of spread and persistence where relevant. Use appropriate controlled studies, replication, long-term observation, containment assessment, and independent ethical and safety review for the specific application.",
    falsification:
      "A claim of bounded intervention fails if an identified exposure pathway cannot be monitored or contained to the stated standard, an adverse outcome crosses a predefined stopping threshold, or the assumed ability to reverse an effect cannot be demonstrated under relevant conditions.",
    boundary:
      "Laboratory containment does not establish ecological recoverability. An absence of detected harm is not proof of absence when surveillance is insensitive or the observation period is too short. Some biological consequences may not be fully reversible.",
    horizon:
      "Where recovery cannot credibly be demonstrated, prevention, restricted exposure, and sustained observation take precedence over an unsupported promise of restoration.",
    openProblem:
      "How should evidence requirements and deployment boundaries change when benefits are observable in the present but plausible harms may be delayed, adaptive, or impossible to recall?",
  },
  {
    number: "04",
    id: "infrastructure",
    name: "Infrastructure",
    subtitle: "THE POWER TO SHAPE CIVILIZATION",
    question:
      "Can systems that sustain civilization remain observable, recoverable, and adaptable across generations?",
    abstract:
      "Civilization depends on interacting networks of energy, communication, transport, computation, water, materials, and human expertise. A highly efficient component can increase whole-system fragility when its failure propagates through shared dependencies. The central responsibility is to preserve essential function under disruption—not merely to optimize performance during normal operation.",
    causal:
      "Infrastructure failure is often relational. Two services that appear independent may rely on the same electrical supply, communication network, supplier, software component, workforce, or institutional authority. Restoration may require the very infrastructure that has failed. The practical outcome also depends on who can access replacement services, not only whether those services technically exist.",
    method:
      "Represent essential services as a dependency network that includes physical assets, digital control, maintenance, supply chains, trained personnel, and access by affected populations. Identify minimum essential functions and common-mode failures. Test component loss, shared-dependency loss, cascading disruption, and degraded restoration conditions. Measure service continuity, restoration time, resource sufficiency, and the distribution of effects across users.",
    falsification:
      "A resilience claim is not supported if nominally redundant pathways fail through a shared dependency, restoration requires unavailable infrastructure, or essential service cannot be delivered to the population for whom continuity was claimed.",
    boundary:
      "Redundancy is not equivalent to independence. A successful simulation is evidence only for the scenarios and assumptions it represents. Restoration of technical capacity does not automatically establish restoration of equitable access.",
    horizon:
      "Preserve repairability, migration pathways, documented interfaces, replacement capacity, and the option to retire obsolete infrastructure without losing essential societal functions.",
    openProblem:
      "What is the minimum sufficient architecture that preserves essential services when multiple physical, digital, economic, and institutional dependencies fail together?",
  },
  {
    number: "05",
    id: "governance",
    name: "Governance",
    subtitle: "THE POWER TO AUTHORIZE AND DECIDE",
    question:
      "Can institutions retain the authority and practical capacity to revise decisions as evidence and consequences change?",
    abstract:
      "Technical feasibility cannot determine, on its own, who should bear a risk, who may authorize an intervention, or what remedy is owed after harm. Institutions establish the decision rights and obligations through which technical capability becomes socially consequential. Their responsibility must remain operative when evidence changes, leadership turns over, and the original decision-makers are no longer present.",
    causal:
      "Institutional failure can occur even when equipment performs as designed. Authority may be fragmented among owners, contractors, operators, and oversight bodies. Affected people may lack access to evidence or a meaningful route to challenge decisions. Financial and organizational incentives may favor continued operation even when the original justification has weakened.",
    method:
      "Map decision rights, duties, affected populations, disclosure requirements, review mechanisms, funding, and remedies. Separate technical evaluation from authorization and independent oversight. Conduct an adversarial exercise in which new evidence contradicts the original safety case after a change in leadership or ownership. Test whether records remain accessible, review remains independent, operations can be suspended, and corrective action can actually be financed and executed.",
    falsification:
      "The accountability architecture fails its stated objective if a credible adverse finding cannot reach an empowered reviewer, affected parties cannot use the established challenge process, or no accountable institution has the authority and resources to implement a required correction or remedy.",
    boundary:
      "No universal institutional arrangement is presumed appropriate for every technology, population, or jurisdiction. An audit record does not itself establish legitimacy, and formal authority does not guarantee practical capacity to act.",
    horizon:
      "Make responsibilities inspectable and transferable without binding future generations to an unchangeable decision. Continuity of obligation must coexist with the ability to revise or terminate a mandate.",
    openProblem:
      "How can enforceable responsibility survive changes in ownership, jurisdiction, incentives, and public priorities while preserving meaningful independent revision?",
  },
];

const CAPACITIES = [
  {
    number: "01",
    title: "Observe",
    question: "Can emerging failure be detected while action is still possible?",
    explanation:
      "Observation requires defined indicators, sufficient coverage, known detection limits, and a response window. Monitoring that detects harm only after an irreversible threshold has been crossed does not establish effective control.",
    evidence:
      "Detection latency, coverage, false-negative analysis, independent measurement access, and tested alert pathways.",
  },
  {
    number: "02",
    title: "Understand",
    question: "Can the claim be distinguished from a persuasive representation?",
    explanation:
      "A model is a candidate account of reality. Responsible understanding separates measured outcomes, inferred mechanisms, assumptions, uncertainty, and competing explanations.",
    evidence:
      "Traceable sources, discriminating experiments, uncertainty analysis, explicit operating limits, and reproducible review.",
  },
  {
    number: "03",
    title: "Challenge",
    question: "Can an independent party question the system with practical effect?",
    explanation:
      "Challenge requires more than permission to express disagreement. Reviewers and affected people need relevant evidence, accessible procedures, sufficient independence, and a route to change a consequential decision.",
    evidence:
      "Independent review access, documented objections, appeal procedures, decision records, and demonstrated authority to intervene.",
  },
  {
    number: "04",
    title: "Correct",
    question: "Can unsafe behavior be interrupted before consequences escalate?",
    explanation:
      "Correctability depends on the relationship between detection, decision, and intervention time. A nominal stop mechanism is insufficient if it cannot act under degraded conditions or before the relevant harm threshold.",
    evidence:
      "Intervention exercises, safe-state tests, response latency, bounded authority, and failure-mode-specific stopping criteria.",
  },
  {
    number: "05",
    title: "Recover",
    question: "Can essential function be restored when prevention fails?",
    explanation:
      "Recovery may mean repair, substitution, restoration of service, or remedy for affected people. It must be demonstrated for the claimed failure conditions. Some losses have no credible recovery pathway.",
    evidence:
      "Restoration drills, alternative pathways, resource reserves, measured service outcomes, and explicit identification of irreversible harms.",
  },
  {
    number: "06",
    title: "Remain accountable",
    question: "Who retains the obligation after the original creator disappears?",
    explanation:
      "Responsibility must survive changes in personnel, ownership, technology, and institutional form. Knowledge, authority, resources, and duties must be transferred in a way that can be independently inspected.",
    evidence:
      "Named duty holders, funded stewardship, retained records, succession arrangements, review dates, and enforceable remedy pathways.",
  },
] as const;

const GATES = [
  {
    number: "01",
    title: "Define the claim",
    question: "What is actually being proposed?",
    body:
      "Specify the intended benefit, affected population, operating conditions, alternatives, plausible harms, and limits of the present evidence. A claim must be narrow enough that a relevant observation could count against it.",
  },
  {
    number: "02",
    title: "Discriminate",
    question: "What observation would change the conclusion?",
    body:
      "Identify rival explanations, measurement bias, missing populations, and conditions under which the preferred model would fail. Define meaningful outcomes before examining the results where feasible.",
  },
  {
    number: "03",
    title: "Reproduce",
    question: "Does the result survive independent examination?",
    body:
      "Repeat relevant tests across operating conditions and independent reviewers. Examine uncertainty, failure tails, dependence on particular personnel, and the boundary beyond which results cannot be generalized.",
  },
  {
    number: "04",
    title: "Bound the capability",
    question: "Can adverse behavior be detected and stopped?",
    body:
      "Demonstrate observation, interruption, containment, and recovery where recovery is feasible. When harm may be irreversible, use stronger prevention and narrower exposure rather than assuming a future repair.",
  },
  {
    number: "05",
    title: "Sustain the obligation",
    question: "Who remains responsible tomorrow?",
    body:
      "Assign monitoring, maintenance, funding, disclosure, remedy, replacement, and end-of-life duties. Test the arrangements against the disappearance of the original operator or a change in ownership.",
  },
  {
    number: "06",
    title: "Reauthorize scale",
    question: "What evidence supports the next increase in reach?",
    body:
      "Reassess the safety and responsibility case whenever autonomy, deployment, exposure, interdependence, or time horizon expands. Evidence at one scale does not automatically authorize the next.",
  },
] as const;

const HORIZONS = [
  {
    number: "01",
    label: "SECONDS → DAYS",
    title: "The intervention window",
    body:
      "Some systems can cross a harm threshold faster than a person can recognize the problem and respond. The design must therefore establish the actual time available for detection, authorization, and intervention. Where human response is too slow, the operating envelope must be constrained or appropriate protective mechanisms must act independently.",
  },
  {
    number: "02",
    label: "MONTHS → DECADES",
    title: "Maintenance and drift",
    body:
      "Equipment ages, environments change, models lose calibration, and personnel move on. A safety case must account for inspection intervals, replacement resources, changes in use, and the possibility that initially valid assumptions will cease to hold.",
  },
  {
    number: "03",
    label: "DECADES → CENTURIES",
    title: "Intergenerational stewardship",
    body:
      "Consequences can persist beyond the organization that created them. Durable responsibility requires records that remain understandable, obligations that can be transferred, resources that remain available, and institutions capable of revising decisions when new evidence emerges.",
  },
  {
    number: "04",
    label: "NO CREDIBLE RECOVERY HORIZON",
    title: "The irreversibility boundary",
    body:
      "Some losses cannot be restored by ordinary repair. When recovery is not credible, a design must not rely on it to justify exposure. The relevant options may include prevention, smaller-scale investigation, alternative approaches, or non-deployment.",
  },
] as const;

function Reveal({
  children,
  className = "",
}: {
  children: ReactNode;
  className?: string;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const element = ref.current;
    if (!element) return;

    if (
      !("IntersectionObserver" in window) ||
      window.matchMedia("(prefers-reduced-motion: reduce)").matches
    ) {
      setVisible(true);
      return;
    }

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          observer.disconnect();
        }
      },
      {
        threshold: 0.05,
        rootMargin: "0px 0px 80px 0px",
      }
    );

    observer.observe(element);

    return () => observer.disconnect();
  }, []);

  return (
    <div
      ref={ref}
      className={`hr-reveal ${visible ? "is-visible" : ""} ${className}`}
    >
      {children}
    </div>
  );
}

function SectionHeading({
  index,
  label,
  title,
  secondary,
  children,
}: {
  index: string;
  label: string;
  title: string;
  secondary?: string;
  children: ReactNode;
}) {
  return (
    <Reveal className="hr-heading">
      <div className="hr-heading__top">
        <span className="hr-index">{index}</span>
        <span className="hr-eyebrow">{label}</span>
      </div>

      <h2>
        {title}
        {secondary && (
          <>
            <br />
            <span>{secondary}</span>
          </>
        )}
      </h2>

      <p>{children}</p>
    </Reveal>
  );
}

function Background() {
  return (
    <div className="hr-background" aria-hidden="true">
      <div className="hr-background__field" />

      <svg
        className="hr-background__art"
        viewBox="0 0 1600 1000"
        preserveAspectRatio="xMidYMid slice"
        focusable="false"
      >
        <defs>
          <radialGradient id="hr-world" cx="36%" cy="28%" r="78%">
            <stop offset="0%" stopColor="#494949" stopOpacity=".42" />
            <stop offset="35%" stopColor="#262626" stopOpacity=".35" />
            <stop offset="76%" stopColor="#101010" stopOpacity=".95" />
            <stop offset="100%" stopColor="#080808" />
          </radialGradient>

          <radialGradient id="hr-halo">
            <stop offset="0%" stopColor="#8c8c8c" stopOpacity=".12" />
            <stop offset="100%" stopColor="#8c8c8c" stopOpacity="0" />
          </radialGradient>

          <linearGradient id="hr-orbit" x1="0" y1="0" x2="1" y2="1">
            <stop offset="0%" stopColor="#a4a4a4" stopOpacity="0" />
            <stop offset="48%" stopColor="#a4a4a4" stopOpacity=".2" />
            <stop offset="100%" stopColor="#a4a4a4" stopOpacity="0" />
          </linearGradient>
        </defs>

        <ellipse
          cx="1200"
          cy="510"
          rx="630"
          ry="610"
          fill="url(#hr-halo)"
        />

        <g className="hr-background__orbits">
          <ellipse
            cx="1210"
            cy="510"
            rx="570"
            ry="210"
            fill="none"
            stroke="url(#hr-orbit)"
            strokeWidth="1"
            transform="rotate(-28 1210 510)"
          />
          <ellipse
            cx="1210"
            cy="510"
            rx="660"
            ry="300"
            fill="none"
            stroke="url(#hr-orbit)"
            strokeWidth=".8"
            transform="rotate(27 1210 510)"
          />
          <ellipse
            cx="1210"
            cy="510"
            rx="730"
            ry="410"
            fill="none"
            stroke="url(#hr-orbit)"
            strokeWidth=".65"
            transform="rotate(-16 1210 510)"
          />
        </g>

        <circle
          className="hr-background__world"
          cx="1210"
          cy="510"
          r="285"
          fill="url(#hr-world)"
          stroke="#777"
          strokeOpacity=".12"
        />

        <circle
          cx="1210"
          cy="510"
          r="296"
          fill="none"
          stroke="#b0b0b0"
          strokeOpacity=".075"
        />

        <path
          d="M 930 465 Q 1200 365 1480 495"
          fill="none"
          stroke="#bcbcbc"
          strokeOpacity=".09"
        />
        <path
          d="M 960 610 Q 1230 480 1450 620"
          fill="none"
          stroke="#bcbcbc"
          strokeOpacity=".055"
        />
      </svg>

      <div className="hr-background__veil" />
      <div className="hr-background__grain" />
    </div>
  );
}

function DomainSection({ domain }: { domain: Domain }) {
  return (
    <section
      id={domain.id}
      className="hr-screen hr-domain"
      aria-labelledby={`hr-${domain.id}-title`}
    >
      <div className="hr-domain__watermark" aria-hidden="true">
        {domain.number}
      </div>

      <div className="hr-width">
        <Reveal className="hr-domain__heading">
          <div className="hr-domain__meta">
            <span className="hr-index">{domain.number} / 05</span>
            <span className="hr-eyebrow">{domain.subtitle}</span>
          </div>

          <h2 id={`hr-${domain.id}-title`}>{domain.name}</h2>

          <p className="hr-domain__question">{domain.question}</p>
        </Reveal>

        <Reveal>
          <article className="hr-paper hr-domain__abstract">
            <span className="hr-paper__label">RESEARCH ABSTRACT</span>
            <p>{domain.abstract}</p>
          </article>
        </Reveal>

        <div className="hr-domain__research">
          <Reveal>
            <article className="hr-paper hr-research-card">
              <span className="hr-paper__label">01 / CAUSAL STRUCTURE</span>
              <h3>Where responsibility enters the system</h3>
              <p>{domain.causal}</p>
            </article>
          </Reveal>

          <Reveal>
            <article className="hr-paper hr-research-card">
              <span className="hr-paper__label">02 / RESEARCH METHOD</span>
              <h3>How the claim should be examined</h3>
              <p>{domain.method}</p>
            </article>
          </Reveal>

          <Reveal>
            <article className="hr-paper hr-research-card">
              <span className="hr-paper__label">03 / FALSIFICATION CONDITION</span>
              <h3>What would count against the claim</h3>
              <p>{domain.falsification}</p>
            </article>
          </Reveal>

          <Reveal>
            <article className="hr-paper hr-research-card">
              <span className="hr-paper__label">04 / EVIDENCE BOUNDARY</span>
              <h3>What must not be assumed</h3>
              <p>{domain.boundary}</p>
            </article>
          </Reveal>
        </div>

        <Reveal>
          <article className="hr-paper hr-domain__horizon">
            <div>
              <span className="hr-paper__label">THE LONG HORIZON</span>
              <h3>Responsibility beyond the moment of creation</h3>
            </div>
            <p>{domain.horizon}</p>
          </article>
        </Reveal>

        <Reveal>
          <div className="hr-domain__open">
            <span className="hr-paper__label">OPEN RESEARCH QUESTION</span>
            <p>{domain.openProblem}</p>
          </div>
        </Reveal>
      </div>
    </section>
  );
}

function GateSection() {
  const [expanded, setExpanded] = useState<string | null>("01");

  return (
    <div className="hr-gates">
      {GATES.map((gate) => {
        const open = expanded === gate.number;

        return (
          <article
            className={`hr-gate ${open ? "is-open" : ""}`}
            key={gate.number}
          >
            <button
              type="button"
              className="hr-gate__button"
              aria-expanded={open}
              aria-controls={`hr-gate-${gate.number}`}
              onClick={() =>
                setExpanded(open ? null : gate.number)
              }
            >
              <span className="hr-index">{gate.number}</span>

              <span className="hr-gate__title">
                <strong>{gate.title}</strong>
                <small>{gate.question}</small>
              </span>

              <span className="hr-gate__symbol" aria-hidden="true">
                {open ? "−" : "+"}
              </span>
            </button>

            <div
              id={`hr-gate-${gate.number}`}
              className="hr-gate__body"
              hidden={!open}
            >
              <p>{gate.body}</p>
            </div>
          </article>
        );
      })}
    </div>
  );
}

export default function HumanityResponsibilityPage() {
  const [readingProgress, setReadingProgress] = useState(0);

  useEffect(() => {
    let frame = 0;

    const updateProgress = () => {
      cancelAnimationFrame(frame);

      frame = requestAnimationFrame(() => {
        const root = document.documentElement;
        const available = root.scrollHeight - window.innerHeight;

        setReadingProgress(
          available > 0
            ? Math.min(100, (window.scrollY / available) * 100)
            : 0
        );
      });
    };

    updateProgress();

    window.addEventListener("scroll", updateProgress, {
      passive: true,
    });
    window.addEventListener("resize", updateProgress);

    return () => {
      cancelAnimationFrame(frame);
      window.removeEventListener("scroll", updateProgress);
      window.removeEventListener("resize", updateProgress);
    };
  }, []);

  return (
    <main className="hr" id="top">
      <Background />

      <div className="hr-progress" aria-hidden="true">
        <div style={{ width: `${readingProgress}%` }} />
      </div>

      {/* HERO */}

      <section className="hr-screen hr-hero" aria-labelledby="hr-title">
        <header className="hr-topbar">
          <Link href="/home/" className="hr-home">
            <span aria-hidden="true">←</span>
            <span>ARCHENOVA HOME</span>
          </Link>

          <span className="hr-topbar__identity">
            PERMANENT INQUIRY / HUMANITY & RESPONSIBILITY
          </span>
        </header>

        <div className="hr-hero__body hr-width">
          <Reveal>
            <span className="hr-eyebrow hr-hero__eyebrow">
              AN OPEN QUESTION FOR EVERY GENERATION
            </span>

            <h1 id="hr-title">
              Can Humanity
              <br />
              Remain Responsible
              <br />
              <span>for the Power</span>
              <br />
              <span>It Creates?</span>
            </h1>

            <div className="hr-hero__intro">
              <p>
                Humanity continues to expand its power over
                matter, energy, intelligence, life, and the
                conditions of civilization.
              </p>

              <p>
                The ability to create consequences is not the
                same as the ability to understand, govern,
                correct, and remain responsible for them.
              </p>
            </div>

            <div className="hr-hero__actions">
              <a href="#principle" className="hr-action">
                EXPLORE THE QUESTION
                <span aria-hidden="true">↓</span>
              </a>

              <a href="#fields" className="hr-action hr-action--quiet">
                FIVE FIELDS OF INQUIRY
                <span aria-hidden="true">↗</span>
              </a>
            </div>
          </Reveal>
        </div>

        <div className="hr-hero__footer">
          <span>ARCHENOVA / PERMANENT INQUIRY</span>
          <span>SCROLL TO CONTINUE ↓</span>
        </div>
      </section>

      {/* PRINCIPLE */}

      <section
        id="principle"
        className="hr-screen hr-principle"
        aria-labelledby="hr-principle-title"
      >
        <div className="hr-width">
          <Reveal className="hr-principle__intro">
            <span className="hr-eyebrow">
              01 / THE GOVERNING PRINCIPLE
            </span>

            <h2 id="hr-principle-title">
              Capability must
              <br />
              <span>not outgrow responsibility.</span>
            </h2>

            <p>
              A capability may be scientifically possible,
              technically functional, and economically
              attractive without its long-term consequences
              being sufficiently understood or its failures
              being recoverable.
            </p>
          </Reveal>

          <Reveal>
            <div className="hr-principle__statement hr-paper">
              <span className="hr-paper__label">
                THE FUNDAMENTAL DISTINCTION
              </span>

              <div className="hr-principle__formula">
                <span>CAPABILITY</span>
                <span className="hr-principle__operator">≠</span>
                <span>CONTROL</span>
                <span className="hr-principle__operator">≠</span>
                <span>RESPONSIBILITY</span>
              </div>

              <p>
                Creating power does not, by itself, establish
                the ability to govern its consequences.
              </p>
            </div>
          </Reveal>

          <div className="hr-principle__analysis">
            <Reveal>
              <article>
                <span className="hr-paper__label">
                  EPISTEMIC REQUIREMENT
                </span>
                <h3>Reality must remain distinct from its representation.</h3>
                <p>
                  Observations, measurements, datasets, models,
                  and forecasts are ways of examining reality;
                  none is reality itself. A responsible decision
                  identifies the evidence supporting its claims,
                  the uncertainty that remains, and the
                  observations that could require revision.
                </p>
              </article>
            </Reveal>

            <Reveal>
              <article>
                <span className="hr-paper__label">
                  OPERATIONAL REQUIREMENT
                </span>
                <h3>Control must exist before it is needed.</h3>
                <p>
                  Responsibility requires a practical capacity
                  to detect adverse behavior, intervene within
                  the available response window, and preserve
                  essential function where recovery is possible.
                  A safeguard that works only under ideal
                  conditions does not establish control during
                  the failures it is intended to address.
                </p>
              </article>
            </Reveal>

            <Reveal>
              <article>
                <span className="hr-paper__label">
                  INTERGENERATIONAL REQUIREMENT
                </span>
                <h3>Obligations must survive their creators.</h3>
                <p>
                  Consequences may persist after the original
                  team, owner, technology, or institution has
                  disappeared. Knowledge, resources, authority,
                  review, and remedy must be designed for
                  transfer rather than assumed to remain
                  available indefinitely.
                </p>
              </article>
            </Reveal>
          </div>
        </div>
      </section>

      {/* CONTINUOUS TEST */}

      <section
        className="hr-screen hr-capacities"
        aria-labelledby="hr-capacities-title"
      >
        <div className="hr-width">
          <SectionHeading
            index="02"
            label="THE CONTINUOUS TEST"
            title="Responsibility must"
            secondary="remain operational."
          >
            Responsibility is not merely an intention, a
            promise, or an approval issued once. It requires
            capacities that can be demonstrated, independently
            challenged, and reassessed as the system becomes
            more powerful, interconnected, or difficult to
            reverse.
          </SectionHeading>

          <div className="hr-capacities__list">
            {CAPACITIES.map((capacity) => (
              <Reveal key={capacity.number}>
                <article className="hr-capacity">
                  <div className="hr-capacity__identity">
                    <span className="hr-index">
                      {capacity.number} / 06
                    </span>
                    <h3>{capacity.title}</h3>
                  </div>

                  <div className="hr-capacity__content">
                    <h4>{capacity.question}</h4>
                    <p>{capacity.explanation}</p>

                    <div className="hr-capacity__evidence">
                      <span className="hr-paper__label">
                        WHAT WOULD COUNT AS EVIDENCE
                      </span>
                      <p>{capacity.evidence}</p>
                    </div>
                  </div>
                </article>
              </Reveal>
            ))}
          </div>

          <Reveal>
            <p className="hr-section-endnote">
              A safeguard adequate at one scale may become
              insufficient at another. The test must continue
              as capabilities, dependencies, and consequences
              change.
            </p>
          </Reveal>
        </div>
      </section>

      {/* FIVE FIELDS */}

      <section
        id="fields"
        className="hr-screen hr-fields-intro"
        aria-labelledby="hr-fields-title"
      >
        <div className="hr-width">
          <Reveal>
            <span className="hr-eyebrow">
              03 / THE FIELDS OF INQUIRY
            </span>

            <h2 id="hr-fields-title">
              One question.
              <br />
              <span>Many forms of power.</span>
            </h2>

            <p>
              The same responsibility problem appears wherever
              human capability can produce consequences that
              extend beyond immediate observation, control,
              or recovery.
            </p>
          </Reveal>

          <nav
            className="hr-field-navigation"
            aria-label="Five fields of inquiry"
          >
            {DOMAINS.map((domain) => (
              <a key={domain.id} href={`#${domain.id}`}>
                <span className="hr-index">{domain.number}</span>
                <span>{domain.name}</span>
                <span aria-hidden="true">↗</span>
              </a>
            ))}
          </nav>
        </div>
      </section>

      {DOMAINS.map((domain) => (
        <DomainSection key={domain.id} domain={domain} />
      ))}

      {/* DESIGN CONDITIONS */}

      <section
        className="hr-screen hr-conditions"
        aria-labelledby="hr-conditions-title"
      >
        <div className="hr-width">
          <SectionHeading
            index="04"
            label="THE ENGINEERING OF RESPONSIBILITY"
            title="The response must"
            secondary="precede the consequence."
          >
            The central engineering question is not whether a
            system possesses a nominal safeguard. It is whether
            the safeguard remains effective under the conditions
            in which it is actually needed.
          </SectionHeading>

          <div className="hr-conditions__list">
            <Reveal>
              <article className="hr-paper hr-condition">
                <span className="hr-paper__label">
                  DESIGN CONDITION / RESPONSE TIME
                </span>

                <h3>
                  Detection + decision + intervention
                  <br />
                  <span>must fit within the available window.</span>
                </h3>

                <p>
                  The time required to recognize a hazard,
                  authorize a response, and execute an
                  intervention must be evaluated against the
                  time remaining before a specified adverse
                  threshold is crossed. If the response cannot
                  reliably arrive in time, the operating
                  envelope or the protective architecture must
                  change.
                </p>

                <div className="hr-condition__note">
                  <span>VALIDATION QUESTION</span>
                  <p>
                    Does the response remain timely when
                    sensors, communications, personnel, or
                    other dependencies are degraded?
                  </p>
                </div>
              </article>
            </Reveal>

            <Reveal>
              <article className="hr-paper hr-condition">
                <span className="hr-paper__label">
                  DESIGN CONDITION / PERMISSIBLE SCALE
                </span>

                <h3>
                  Reach must remain bounded
                  <br />
                  <span>by demonstrated oversight.</span>
                </h3>

                <p>
                  Expansion can increase exposure, autonomy,
                  coupling, and the speed at which failure
                  propagates. Evidence obtained from a limited
                  demonstration cannot automatically establish
                  that monitoring, intervention, recovery, and
                  accountable authorization remain adequate
                  after deployment grows.
                </p>

                <div className="hr-condition__note">
                  <span>VALIDATION QUESTION</span>
                  <p>
                    Which new failure pathways appear at the
                    proposed scale, and what new evidence is
                    required before expansion?
                  </p>
                </div>
              </article>
            </Reveal>

            <Reveal>
              <article className="hr-paper hr-condition">
                <span className="hr-paper__label">
                  DESIGN CONDITION / IRREVERSIBILITY
                </span>

                <h3>
                  When recovery is not credible,
                  <br />
                  <span>prevention becomes decisive.</span>
                </h3>

                <p>
                  Not every consequence can be undone. The
                  absence of a credible restoration pathway
                  changes the design problem: exposure may need
                  to be reduced, experiments may need to be
                  bounded more tightly, and some commitments
                  may need to be deferred or avoided. A
                  speculative recovery plan must not be treated
                  as demonstrated protection.
                </p>

                <div className="hr-condition__note">
                  <span>VALIDATION QUESTION</span>
                  <p>
                    What irreversible outcome is plausible,
                    what evidence supports that assessment,
                    and how is the exposure boundary enforced?
                  </p>
                </div>
              </article>
            </Reveal>
          </div>

          <Reveal>
            <p className="hr-section-endnote">
              These are proposed design conditions, not
              universal numerical laws. Each application
              requires its own variables, thresholds,
              uncertainty analysis, and independent validation.
            </p>
          </Reveal>
        </div>
      </section>

      {/* VALIDATION GATES */}

      <section
        className="hr-screen hr-validation"
        aria-labelledby="hr-validation-title"
      >
        <div className="hr-width">
          <SectionHeading
            index="05"
            label="FROM EVIDENCE TO AUTHORITY"
            title="No expansion"
            secondary="without renewed evidence."
          >
            A proposed pathway from an idea to consequential
            deployment. Each gate asks what must be established
            before a further commitment is made—and what
            finding would require revision, restriction,
            or withdrawal.
          </SectionHeading>

          <Reveal>
            <GateSection />
          </Reveal>

          <Reveal>
            <div className="hr-validation__footnote">
              <span className="hr-paper__label">
                STATUS OF THIS FRAMEWORK
              </span>
              <p>
                These gates are proposed evaluation criteria.
                Their presence on this page does not mean
                ArcheNova has completed the associated tests
                or that the same procedure is sufficient for
                every scientific, technical, or institutional
                domain.
              </p>
            </div>
          </Reveal>
        </div>
      </section>

      {/* LONG HORIZON */}

      <section
        className="hr-screen hr-horizons"
        aria-labelledby="hr-horizons-title"
      >
        <div className="hr-width">
          <SectionHeading
            index="06"
            label="THE LONG HORIZON"
            title="Consequences may outlive"
            secondary="their creators."
          >
            The relevant timescale is not the duration of a
            launch, a product cycle, or an institution's
            mandate. It is the duration of the consequence
            and the period over which meaningful stewardship
            must remain possible.
          </SectionHeading>

          <div className="hr-horizons__list">
            {HORIZONS.map((horizon) => (
              <Reveal key={horizon.number}>
                <article className="hr-horizon">
                  <div className="hr-horizon__time">
                    <span className="hr-index">
                      {horizon.number} / 04
                    </span>
                    <span>{horizon.label}</span>
                  </div>

                  <div className="hr-horizon__body">
                    <h3>{horizon.title}</h3>
                    <p>{horizon.body}</p>
                  </div>
                </article>
              </Reveal>
            ))}
          </div>

          <Reveal>
            <div className="hr-paper hr-horizons__statement">
              <span className="hr-paper__label">
                THE INTERGENERATIONAL REQUIREMENT
              </span>

              <p>
                Monitoring, correction, recovery where
                possible, and accountability must be designed
                to continue beyond the moment of creation.
              </p>
            </div>
          </Reveal>
        </div>
      </section>

      {/* COUNTERFACTUAL */}

      <section
        className="hr-screen hr-counterfactual"
        aria-labelledby="hr-counterfactual-title"
      >
        <div className="hr-width">
          <SectionHeading
            index="07"
            label="THE COUNTERFACTUAL TEST"
            title="Design for"
            secondary="the day after."
          >
            A system should not be judged only by how it
            performs while its creators, funding, equipment,
            and original assumptions remain intact. The harder
            question is whether its responsibilities can still
            be discharged after those supports change.
          </SectionHeading>

          <Reveal>
            <article className="hr-paper hr-scenario">
              <span className="hr-paper__label">
                PROPOSED STRESS-TEST SCENARIO / NOT A REPORTED EVENT
              </span>

              <h3>The original operator disappears.</h3>

              <p className="hr-scenario__lead">
                A consequential system remains in use. Its
                original team is gone, its records are
                incomplete, an essential supplier has failed,
                and a previously unknown hazard has emerged.
              </p>

              <div className="hr-scenario__questions">
                {[
                  "Who can establish what the system is doing?",
                  "Who has the authority and resources to intervene?",
                  "Can essential functions continue through an alternative pathway?",
                  "Who provides remedy if harm cannot be reversed?",
                  "What evidence would justify continued operation—or closure?",
                ].map((question, index) => (
                  <div key={question}>
                    <span className="hr-index">
                      {String(index + 1).padStart(2, "0")}
                    </span>
                    <p>{question}</p>
                  </div>
                ))}
              </div>

              <p className="hr-scenario__conclusion">
                If these questions have no credible answer,
                the original deployment plan contains an
                unresolved responsibility gap.
              </p>
            </article>
          </Reveal>
        </div>
      </section>

      {/* EVIDENCE BOUNDARY */}

      <section
        className="hr-screen hr-evidence"
        aria-labelledby="hr-evidence-title"
      >
        <div className="hr-width">
          <SectionHeading
            index="08"
            label="EVIDENCE & LIMITS"
            title="The framework must"
            secondary="answer to reality."
          >
            A research architecture is valuable only if it
            improves the quality of real decisions under
            specified conditions and remains open to
            independent criticism, contrary evidence,
            and revision.
          </SectionHeading>

          <div className="hr-evidence__grid">
            <Reveal>
              <article className="hr-paper">
                <span className="hr-paper__label">
                  PRESENTED HERE
                </span>
                <h3>A structured research proposition</h3>
                <p>
                  A governing question, domain-specific causal
                  analyses, proposed design conditions,
                  falsification criteria, and a framework for
                  sustained responsibility.
                </p>
              </article>
            </Reveal>

            <Reveal>
              <article className="hr-paper">
                <span className="hr-paper__label">
                  REQUIRES VALIDATION
                </span>
                <h3>Operational effectiveness</h3>
                <p>
                  Every real application requires measurable
                  variables, comparison with existing methods,
                  relevant failure testing, independent
                  expertise, and evidence from its actual
                  operating conditions.
                </p>
              </article>
            </Reveal>

            <Reveal>
              <article className="hr-paper">
                <span className="hr-paper__label">
                  NOT CLAIMED
                </span>
                <h3>A universal law or proof of safety</h3>
                <p>
                  No statement on this page establishes a new
                  physical law, guarantees the absence of harm,
                  or proves that every technology can be made
                  reversible, recoverable, or fully governable.
                </p>
              </article>
            </Reveal>
          </div>
        </div>
      </section>

      {/* CLOSING */}

      <section
        className="hr-screen hr-closing"
        aria-labelledby="hr-closing-title"
      >
        <div className="hr-width">
          <Reveal>
            <span className="hr-eyebrow">
              ARCHENOVA / PERMANENT INQUIRY
            </span>

            <h2 id="hr-closing-title">
              The question
              <br />
              <span>remains open.</span>
            </h2>

            <p>
              Every new capability creates a new occasion to
              test whether humanity can remain responsible
              for the power it creates.
            </p>

            <p>
              Responsibility is not the end of discovery. It
              is the continuing obligation to distinguish
              what is known from what is assumed, to preserve
              the ability to challenge and correct, and to
              carry the consequences of creation into a future
              that its creators will not fully control.
            </p>

            <div className="hr-closing__actions">
              <Link href="/home/" className="hr-action">
                RETURN TO ARCHENOVA
                <span aria-hidden="true">↗</span>
              </Link>

              <a
                href="#top"
                className="hr-action hr-action--quiet"
              >
                REVISIT THE QUESTION
                <span aria-hidden="true">↑</span>
              </a>
            </div>
          </Reveal>
        </div>
      </section>

      <footer className="hr-footer">
        <span>ARCHENOVA / HUMANITY & RESPONSIBILITY</span>
        <span>
          CAPABILITY · CORRECTABILITY · STEWARDSHIP
        </span>
      </footer>

      <style jsx global>{`
        /* ====================================================
           00 / FULL-VIEWPORT RESET

           The page is deliberately NOT placed inside a
           centered, fixed-width global content container.
        ==================================================== */

        html:has(.hr) {
          scroll-behavior: smooth;
          background: #0b0b0b;
        }

        body:has(.hr) {
          margin: 0;
          background: #0b0b0b;
        }

        html:has(.hr),
        body:has(.hr) {
          width: 100%;
          min-width: 0;
          overflow-x: clip;
        }

        body:has(.hr) .site-content,
        body:has(.hr) #site-content,
        body:has(.hr) .main-content,
        body:has(.hr) .page-content {
          width: 100% !important;
          max-width: none !important;
          min-width: 0 !important;
          margin: 0 !important;
          padding: 0 !important;
          border: 0 !important;
          background: transparent !important;
        }

        body:has(.hr) .site-header {
          display: none !important;
        }

        .hr,
        .hr *,
        .hr *::before,
        .hr *::after {
          box-sizing: border-box;
        }

        .hr {
          --hr-black: #0b0b0b;
          --hr-text: #f2f2f2;
          --hr-muted: rgba(242, 242, 242, 0.68);
          --hr-faint: rgba(242, 242, 242, 0.43);
          --hr-line: rgba(255, 255, 255, 0.105);
          --hr-side: clamp(24px, 6.1vw, 116px);
          --hr-space: clamp(108px, 13vh, 190px);

          position: relative;
          isolation: isolate;
          width: 100%;
          max-width: none;
          min-width: 0;
          min-height: 100vh;
          margin: 0;
          padding: 0;
          overflow: clip;
          color: var(--hr-text);
          background: var(--hr-black);
          font-family:
            Inter,
            -apple-system,
            BlinkMacSystemFont,
            "Segoe UI",
            sans-serif;
          -webkit-font-smoothing: antialiased;
          text-rendering: optimizeLegibility;
        }

        .hr a {
          color: inherit;
          text-decoration: none;
        }

        .hr button {
          font: inherit;
        }

        .hr button,
        .hr a {
          -webkit-tap-highlight-color: transparent;
        }

        .hr button:focus-visible,
        .hr a:focus-visible {
          outline: 2px solid rgba(255, 255, 255, 0.9);
          outline-offset: 5px;
        }

        .hr h1,
        .hr h2,
        .hr h3,
        .hr h4,
        .hr p {
          overflow-wrap: break-word;
        }

        /* ====================================================
           01 / MONOCHROMATIC LIVING BACKGROUND
        ==================================================== */

        .hr-background {
          position: fixed;
          z-index: -1;
          inset: 0;
          width: 100%;
          height: 100vh;
          height: 100dvh;
          overflow: hidden;
          pointer-events: none;
          background: #0b0b0b;
        }

        .hr-background__field {
          position: absolute;
          inset: 0;
          background:
            radial-gradient(
              ellipse at 76% 40%,
              rgba(65, 65, 65, 0.16),
              transparent 53%
            ),
            linear-gradient(
              125deg,
              #0b0b0b 0%,
              #111111 48%,
              #090909 100%
            );
        }

        .hr-background__art {
          position: absolute;
          inset: 0;
          width: 100%;
          height: 100%;
          opacity: 0.8;
          animation: hr-background-drift 45s ease-in-out infinite alternate;
        }

        .hr-background__world {
          animation: hr-world-breathe 12s ease-in-out infinite alternate;
        }

        .hr-background__orbits {
          transform-origin: 1210px 510px;
          animation: hr-orbit-drift 70s linear infinite;
        }

        .hr-background__veil {
          position: absolute;
          inset: 0;
          background:
            linear-gradient(
              90deg,
              rgba(8, 8, 8, 0.52),
              rgba(8, 8, 8, 0.1) 70%
            ),
            linear-gradient(
              180deg,
              rgba(8, 8, 8, 0.22),
              transparent 25%,
              transparent 72%,
              rgba(8, 8, 8, 0.46)
            );
        }

        .hr-background__grain {
          position: absolute;
          inset: 0;
          opacity: 0.12;
          background-image: repeating-linear-gradient(
            0deg,
            transparent 0,
            transparent 3px,
            rgba(255, 255, 255, 0.012) 4px
          );
        }

        @keyframes hr-background-drift {
          from {
            transform: scale(1.04) translate3d(-1%, 0, 0);
          }
          to {
            transform: scale(1.13) translate3d(1%, 1%, 0);
          }
        }

        @keyframes hr-world-breathe {
          from {
            opacity: 0.65;
          }
          to {
            opacity: 1;
          }
        }

        @keyframes hr-orbit-drift {
          from {
            transform: rotate(0deg);
          }
          to {
            transform: rotate(360deg);
          }
        }

        .hr-progress {
          position: fixed;
          z-index: 30;
          top: 0;
          left: 0;
          width: 100%;
          height: 2px;
          background: rgba(255, 255, 255, 0.055);
          pointer-events: none;
        }

        .hr-progress > div {
          height: 100%;
          background: rgba(255, 255, 255, 0.78);
          transition: width 0.12s linear;
        }

        /* ====================================================
           02 / FULL-BLEED SECTION SYSTEM

           Every section fills the available screen width.
           hr-width controls padding, NOT page width.
        ==================================================== */

        .hr-screen {
          position: relative;
          display: flex;
          align-items: center;
          width: 100%;
          max-width: none;
          min-width: 0;
          min-height: 100vh;
          min-height: 100svh;
          margin: 0;
          padding: var(--hr-space) 0;
          scroll-margin-top: 0;
          border-bottom: 1px solid rgba(255, 255, 255, 0.055);
        }

        .hr-width {
          position: relative;
          z-index: 1;
          width: 100%;
          max-width: none;
          min-width: 0;
          margin: 0;
          padding-inline: var(--hr-side);
        }

        .hr-eyebrow,
        .hr-index,
        .hr-paper__label {
          display: block;
          color: var(--hr-faint);
          font-size: 10px;
          font-weight: 650;
          line-height: 1.6;
          letter-spacing: 0.17em;
        }

        .hr-index {
          font-variant-numeric: tabular-nums;
        }

        .hr-reveal {
          opacity: 0;
          transform: translateY(20px);
          transition:
            opacity 0.85s ease,
            transform 0.85s cubic-bezier(0.2, 0.75, 0.2, 1);
        }

        .hr-reveal.is-visible {
          opacity: 1;
          transform: none;
        }

        /* ====================================================
           03 / GLASS

           Glass is applied to individual research exhibits.
           No enclosing vertical glass column.
        ==================================================== */

        .hr-paper {
          min-width: 0;
          border: 1px solid var(--hr-line);
          border-radius: clamp(20px, 2.4vw, 34px);
          background: rgba(19, 19, 19, 0.58);
          -webkit-backdrop-filter: blur(24px);
          backdrop-filter: blur(24px);
          box-shadow:
            inset 0 1px 0 rgba(255, 255, 255, 0.045),
            0 24px 85px rgba(0, 0, 0, 0.11);
        }

        .hr-paper h3 {
          margin: 0;
          font-size: clamp(25px, 2.5vw, 40px);
          font-weight: 470;
          line-height: 1.23;
          letter-spacing: -0.05em;
        }

        .hr-paper p {
          color: var(--hr-muted);
          font-size: clamp(15px, 1.12vw, 18px);
          line-height: 1.95;
        }

        /* ====================================================
           04 / HERO
        ==================================================== */

        .hr-hero {
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          align-items: stretch;
          min-height: 100vh;
          min-height: 100svh;
          padding: 0;
        }

        .hr-topbar {
          position: relative;
          z-index: 2;
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 20px;
          width: 100%;
          padding: 27px var(--hr-side);
        }

        .hr-home {
          display: inline-flex;
          align-items: center;
          gap: 13px;
          min-height: 44px;
          padding: 11px 18px;
          border: 1px solid var(--hr-line);
          border-radius: 999px;
          background: rgba(18, 18, 18, 0.6);
          -webkit-backdrop-filter: blur(18px);
          backdrop-filter: blur(18px);
          font-size: 10px;
          font-weight: 650;
          letter-spacing: 0.11em;
        }

        .hr-home > span:first-child {
          font-size: 18px;
          font-weight: 400;
        }

        .hr-topbar__identity,
        .hr-hero__footer {
          color: var(--hr-faint);
          font-size: 9px;
          line-height: 1.6;
          letter-spacing: 0.14em;
        }

        .hr-hero__body {
          display: flex;
          align-items: center;
          flex: 1;
          padding-block: 65px;
        }

        .hr-hero__body > .hr-reveal {
          width: 100%;
        }

        .hr-hero__eyebrow {
          margin-bottom: clamp(30px, 5vh, 65px);
        }

        .hr-hero h1 {
          max-width: 1500px;
          margin: 0;
          font-size: clamp(52px, 7.7vw, 142px);
          font-weight: 470;
          line-height: 1.045;
          letter-spacing: -0.078em;
        }

        .hr-hero h1 span {
          color: rgba(242, 242, 242, 0.53);
        }

        .hr-hero__intro {
          display: grid;
          grid-template-columns: repeat(2, minmax(0, 1fr));
          gap: clamp(30px, 5vw, 100px);
          max-width: 1320px;
          margin-top: clamp(44px, 7vh, 90px);
        }

        .hr-hero__intro p {
          max-width: 610px;
          margin: 0;
          color: var(--hr-muted);
          font-size: clamp(16px, 1.35vw, 22px);
          line-height: 1.8;
        }

        .hr-hero__actions,
        .hr-closing__actions {
          display: flex;
          flex-wrap: wrap;
          gap: 12px;
          margin-top: 48px;
        }

        .hr-action {
          display: inline-flex;
          align-items: center;
          justify-content: space-between;
          gap: 35px;
          min-height: 56px;
          padding: 15px 23px;
          border: 1px solid rgba(255, 255, 255, 0.28);
          border-radius: 999px;
          background: rgba(225, 225, 225, 0.92);
          color: #101010 !important;
          font-size: 10px;
          font-weight: 700;
          line-height: 1.5;
          letter-spacing: 0.11em;
          transition:
            transform 0.25s ease,
            background 0.25s ease,
            border-color 0.25s ease;
        }

        .hr-action--quiet {
          background: rgba(18, 18, 18, 0.56);
          color: var(--hr-text) !important;
          -webkit-backdrop-filter: blur(18px);
          backdrop-filter: blur(18px);
        }

        .hr-hero__footer {
          display: flex;
          justify-content: space-between;
          gap: 20px;
          padding: 23px var(--hr-side) 30px;
        }

        /* ====================================================
           05 / SHARED SECTION HEADINGS
        ==================================================== */

        .hr-heading {
          max-width: 1300px;
          margin-bottom: clamp(55px, 8vh, 110px);
        }

        .hr-heading__top {
          display: flex;
          align-items: center;
          gap: 25px;
          margin-bottom: clamp(25px, 4vh, 48px);
        }

        .hr-heading h2,
        .hr-principle h2,
        .hr-fields-intro h2,
        .hr-closing h2 {
          margin: 0;
          font-size: clamp(47px, 6.3vw, 112px);
          font-weight: 470;
          line-height: 1.07;
          letter-spacing: -0.075em;
        }

        .hr-heading h2 span,
        .hr-principle h2 span,
        .hr-fields-intro h2 span,
        .hr-closing h2 span {
          color: rgba(242, 242, 242, 0.48);
        }

        .hr-heading > p,
        .hr-principle__intro > p,
        .hr-fields-intro > .hr-width > .hr-reveal > p,
        .hr-closing > .hr-width > .hr-reveal > p {
          max-width: 920px;
          margin: 34px 0 0;
          color: var(--hr-muted);
          font-size: clamp(17px, 1.5vw, 23px);
          line-height: 1.85;
        }

        /* ====================================================
           06 / PRINCIPLE
        ==================================================== */

        .hr-principle__intro {
          max-width: 1380px;
        }

        .hr-principle__intro > .hr-eyebrow {
          margin-bottom: 38px;
        }

        .hr-principle__statement {
          margin-top: clamp(55px, 8vh, 105px);
          padding: clamp(30px, 5vw, 85px);
        }

        .hr-principle__formula {
          display: flex;
          flex-wrap: wrap;
          align-items: center;
          gap: clamp(14px, 2.5vw, 45px);
          margin-top: 45px;
          font-size: clamp(26px, 4vw, 72px);
          font-weight: 470;
          line-height: 1.3;
          letter-spacing: -0.055em;
        }

        .hr-principle__operator {
          color: var(--hr-faint);
          font-weight: 350;
        }

        .hr-principle__statement > p {
          max-width: 850px;
          margin: 35px 0 0;
        }

        .hr-principle__analysis {
          display: grid;
          grid-template-columns: repeat(3, minmax(0, 1fr));
          gap: clamp(25px, 3vw, 65px);
          margin-top: clamp(70px, 10vh, 135px);
        }

        .hr-principle__analysis article {
          padding-top: 26px;
          border-top: 1px solid var(--hr-line);
        }

        .hr-principle__analysis h3 {
          margin: 25px 0 20px;
          font-size: clamp(24px, 2.15vw, 35px);
          font-weight: 480;
          line-height: 1.3;
          letter-spacing: -0.045em;
        }

        .hr-principle__analysis p {
          margin: 0;
          color: var(--hr-muted);
          font-size: 15px;
          line-height: 1.9;
        }

        /* ====================================================
           07 / CAPACITIES — ONE ITEM PER SPACIOUS ROW
        ==================================================== */

        .hr-capacities__list {
          border-top: 1px solid var(--hr-line);
        }

        .hr-capacity {
          display: grid;
          grid-template-columns: minmax(0, 0.8fr) minmax(0, 1.2fr);
          gap: clamp(40px, 6vw, 125px);
          min-height: clamp(340px, 47vh, 520px);
          padding: clamp(52px, 7vh, 95px) 0;
          border-bottom: 1px solid var(--hr-line);
        }

        .hr-capacity__identity h3 {
          margin: 30px 0 0;
          font-size: clamp(46px, 5vw, 88px);
          font-weight: 470;
          line-height: 1.1;
          letter-spacing: -0.07em;
        }

        .hr-capacity__content h4 {
          max-width: 900px;
          margin: 0;
          font-size: clamp(24px, 2.5vw, 41px);
          font-weight: 480;
          line-height: 1.28;
          letter-spacing: -0.05em;
        }

        .hr-capacity__content > p {
          max-width: 900px;
          margin: 27px 0 0;
          color: var(--hr-muted);
          font-size: clamp(16px, 1.3vw, 20px);
          line-height: 1.95;
        }

        .hr-capacity__evidence {
          max-width: 900px;
          margin-top: 43px;
          padding: 26px 0 0;
          border-top: 1px solid var(--hr-line);
        }

        .hr-capacity__evidence p {
          margin: 12px 0 0;
          color: var(--hr-muted);
          font-size: 14px;
          line-height: 1.85;
        }

        .hr-section-endnote {
          max-width: 1000px;
          margin: 55px 0 0;
          color: var(--hr-faint);
          font-size: 14px;
          line-height: 1.9;
        }

        /* ====================================================
           08 / FIELDS INTRODUCTION
        ==================================================== */

        .hr-fields-intro > .hr-width > .hr-reveal > .hr-eyebrow {
          margin-bottom: 38px;
        }

        .hr-field-navigation {
          display: grid;
          grid-template-columns: repeat(5, minmax(0, 1fr));
          gap: 12px;
          margin-top: clamp(65px, 10vh, 130px);
        }

        .hr-field-navigation a {
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          gap: 38px;
          min-height: 190px;
          padding: 25px;
          border: 1px solid var(--hr-line);
          border-radius: 22px;
          background: rgba(19, 19, 19, 0.52);
          -webkit-backdrop-filter: blur(18px);
          backdrop-filter: blur(18px);
          transition:
            background 0.25s ease,
            border-color 0.25s ease,
            transform 0.25s ease;
        }

        .hr-field-navigation a > span:nth-child(2) {
          font-size: clamp(18px, 1.65vw, 28px);
          letter-spacing: -0.045em;
        }

        .hr-field-navigation a > span:last-child {
          align-self: flex-end;
          color: var(--hr-faint);
        }

        /* ====================================================
           09 / EACH DOMAIN IS ITS OWN RESEARCH EXHIBITION
        ==================================================== */

        .hr-domain {
          align-items: flex-start;
          overflow: hidden;
          padding-top: clamp(110px, 14vh, 190px);
          padding-bottom: clamp(110px, 14vh, 190px);
        }

        .hr-domain__watermark {
          position: absolute;
          top: 20px;
          right: -0.035em;
          color: rgba(255, 255, 255, 0.025);
          font-size: clamp(240px, 36vw, 670px);
          font-weight: 600;
          line-height: 1;
          letter-spacing: -0.12em;
          pointer-events: none;
          user-select: none;
        }

        .hr-domain__heading {
          position: relative;
          max-width: 1400px;
          margin-bottom: clamp(55px, 8vh, 105px);
        }

        .hr-domain__meta {
          display: flex;
          flex-wrap: wrap;
          gap: 20px;
          align-items: center;
          margin-bottom: 35px;
        }

        .hr-domain__heading h2 {
          margin: 0;
          font-size: clamp(75px, 11vw, 190px);
          font-weight: 460;
          line-height: 0.98;
          letter-spacing: -0.085em;
        }

        .hr-domain__question {
          max-width: 1130px;
          margin: 38px 0 0;
          color: rgba(242, 242, 242, 0.78);
          font-size: clamp(24px, 2.65vw, 45px);
          line-height: 1.4;
          letter-spacing: -0.045em;
        }

        .hr-domain__abstract {
          padding: clamp(32px, 5vw, 78px);
        }

        .hr-domain__abstract p {
          max-width: 1260px;
          margin: 27px 0 0;
          color: rgba(242, 242, 242, 0.84);
          font-size: clamp(18px, 1.65vw, 26px);
          line-height: 1.85;
          letter-spacing: -0.015em;
        }

        .hr-domain__research {
          display: grid;
          grid-template-columns: repeat(2, minmax(0, 1fr));
          gap: clamp(16px, 2vw, 32px);
          margin-top: clamp(22px, 3vw, 44px);
        }

        .hr-domain__research > .hr-reveal {
          display: flex;
          min-width: 0;
        }

        .hr-research-card {
          width: 100%;
          min-height: clamp(370px, 43vh, 540px);
          padding: clamp(32px, 3.5vw, 62px);
        }

        .hr-research-card h3 {
          max-width: 740px;
          margin-top: 31px;
        }

        .hr-research-card p {
          max-width: 850px;
          margin: 24px 0 0;
        }

        .hr-domain__horizon {
          display: grid;
          grid-template-columns: minmax(0, 0.75fr) minmax(0, 1.25fr);
          gap: clamp(35px, 5vw, 100px);
          margin-top: clamp(22px, 3vw, 44px);
          padding: clamp(34px, 4vw, 70px);
        }

        .hr-domain__horizon h3 {
          max-width: 680px;
          margin-top: 28px;
        }

        .hr-domain__horizon p {
          max-width: 900px;
          margin: 0;
        }

        .hr-domain__open {
          display: grid;
          grid-template-columns: minmax(0, 0.35fr) minmax(0, 1fr);
          gap: clamp(35px, 5vw, 100px);
          align-items: start;
          margin-top: clamp(65px, 9vh, 115px);
          padding-top: 30px;
          border-top: 1px solid var(--hr-line);
        }

        .hr-domain__open p {
          max-width: 1050px;
          margin: 0;
          font-size: clamp(22px, 2.3vw, 37px);
          line-height: 1.5;
          letter-spacing: -0.035em;
        }

        /* ====================================================
           10 / DESIGN CONDITIONS
        ==================================================== */

        .hr-conditions__list {
          display: grid;
          gap: clamp(22px, 3vw, 45px);
        }

        .hr-condition {
          padding: clamp(35px, 5vw, 85px);
        }

        .hr-condition h3 {
          margin-top: 38px;
          font-size: clamp(31px, 3.5vw, 60px);
          line-height: 1.2;
        }

        .hr-condition h3 span {
          color: rgba(242, 242, 242, 0.5);
        }

        .hr-condition > p {
          max-width: 1180px;
          margin: 35px 0 0;
          font-size: clamp(16px, 1.4vw, 21px);
        }

        .hr-condition__note {
          display: grid;
          grid-template-columns: minmax(0, 0.3fr) minmax(0, 1fr);
          gap: 40px;
          max-width: 1350px;
          margin-top: 48px;
          padding-top: 28px;
          border-top: 1px solid var(--hr-line);
        }

        .hr-condition__note > span {
          color: var(--hr-faint);
          font-size: 10px;
          letter-spacing: 0.13em;
        }

        .hr-condition__note p {
          margin: 0;
          color: rgba(242, 242, 242, 0.8);
          font-size: clamp(15px, 1.2vw, 18px);
          line-height: 1.8;
        }

        /* ====================================================
           11 / VALIDATION GATES
        ==================================================== */

        .hr-gates {
          border-top: 1px solid var(--hr-line);
        }

        .hr-gate {
          border-bottom: 1px solid var(--hr-line);
        }

        .hr-gate__button {
          display: grid;
          grid-template-columns: 70px minmax(0, 1fr) 42px;
          gap: clamp(20px, 4vw, 70px);
          align-items: center;
          width: 100%;
          min-height: clamp(130px, 17vh, 210px);
          padding: 35px 0;
          border: 0;
          background: transparent;
          color: var(--hr-text);
          text-align: left;
          cursor: pointer;
        }

        .hr-gate__title strong {
          display: block;
          font-size: clamp(27px, 3vw, 51px);
          font-weight: 470;
          line-height: 1.2;
          letter-spacing: -0.055em;
        }

        .hr-gate__title small {
          display: block;
          margin-top: 12px;
          color: var(--hr-muted);
          font-size: clamp(14px, 1.15vw, 18px);
          line-height: 1.7;
        }

        .hr-gate__symbol {
          justify-self: end;
          color: var(--hr-faint);
          font-size: 34px;
          font-weight: 300;
        }

        .hr-gate__body {
          padding: 0 70px clamp(35px, 5vh, 70px)
            calc(70px + clamp(20px, 4vw, 70px));
        }

        .hr-gate__body p {
          max-width: 1150px;
          margin: 0;
          color: var(--hr-muted);
          font-size: clamp(16px, 1.35vw, 21px);
          line-height: 1.9;
        }

        .hr-validation__footnote {
          display: grid;
          grid-template-columns: minmax(0, 0.35fr) minmax(0, 1fr);
          gap: 40px;
          margin-top: 65px;
        }

        .hr-validation__footnote p {
          max-width: 920px;
          margin: 0;
          color: var(--hr-faint);
          font-size: 14px;
          line-height: 1.9;
        }

        /* ====================================================
           12 / LONG HORIZON
        ==================================================== */

        .hr-horizons__list {
          border-top: 1px solid var(--hr-line);
        }

        .hr-horizon {
          display: grid;
          grid-template-columns: minmax(0, 0.65fr) minmax(0, 1.35fr);
          gap: clamp(40px, 6vw, 120px);
          min-height: clamp(300px, 38vh, 470px);
          padding: clamp(50px, 6vh, 85px) 0;
          border-bottom: 1px solid var(--hr-line);
        }

        .hr-horizon__time {
          display: flex;
          flex-direction: column;
          gap: 24px;
        }

        .hr-horizon__time > span:last-child {
          color: var(--hr-faint);
          font-size: clamp(15px, 1.35vw, 21px);
          letter-spacing: 0.025em;
        }

        .hr-horizon__body h3 {
          margin: 0;
          font-size: clamp(31px, 3.3vw, 55px);
          font-weight: 470;
          line-height: 1.2;
          letter-spacing: -0.055em;
        }

        .hr-horizon__body p {
          max-width: 1050px;
          margin: 25px 0 0;
          color: var(--hr-muted);
          font-size: clamp(16px, 1.3vw, 20px);
          line-height: 1.9;
        }

        .hr-horizons__statement {
          margin-top: 65px;
          padding: clamp(35px, 5vw, 85px);
        }

        .hr-horizons__statement p {
          max-width: 1350px;
          margin: 30px 0 0;
          color: var(--hr-text);
          font-size: clamp(25px, 3vw, 49px);
          line-height: 1.5;
          letter-spacing: -0.045em;
        }

        /* ====================================================
           13 / COUNTERFACTUAL
        ==================================================== */

        .hr-scenario {
          padding: clamp(35px, 5vw, 85px);
        }

        .hr-scenario h3 {
          margin-top: 36px;
          font-size: clamp(36px, 4.5vw, 75px);
          letter-spacing: -0.065em;
        }

        .hr-scenario__lead {
          max-width: 1080px;
          margin: 28px 0 0;
          font-size: clamp(17px, 1.45vw, 23px) !important;
        }

        .hr-scenario__questions {
          margin-top: 60px;
          border-top: 1px solid var(--hr-line);
        }

        .hr-scenario__questions > div {
          display: grid;
          grid-template-columns: 65px minmax(0, 1fr);
          gap: 30px;
          align-items: start;
          padding: clamp(25px, 3vh, 45px) 0;
          border-bottom: 1px solid var(--hr-line);
        }

        .hr-scenario__questions p {
          margin: 0;
          color: var(--hr-text);
          font-size: clamp(20px, 2vw, 32px);
          line-height: 1.5;
          letter-spacing: -0.035em;
        }

        .hr-scenario__conclusion {
          max-width: 1120px;
          margin: 55px 0 0;
          color: rgba(242, 242, 242, 0.85) !important;
          font-size: clamp(21px, 2.2vw, 35px) !important;
          line-height: 1.6 !important;
          letter-spacing: -0.035em;
        }

        /* ====================================================
           14 / EVIDENCE
        ==================================================== */

        .hr-evidence__grid {
          display: grid;
          grid-template-columns: repeat(3, minmax(0, 1fr));
          gap: clamp(18px, 2vw, 32px);
        }

        .hr-evidence__grid > .hr-reveal {
          display: flex;
        }

        .hr-evidence__grid .hr-paper {
          width: 100%;
          min-height: 410px;
          padding: clamp(30px, 3vw, 55px);
        }

        .hr-evidence__grid h3 {
          margin-top: 35px;
        }

        .hr-evidence__grid p {
          margin: 25px 0 0;
        }

        /* ====================================================
           15 / CLOSING
        ==================================================== */

        .hr-closing {
          min-height: 100vh;
          min-height: 100svh;
        }

        .hr-closing > .hr-width > .hr-reveal {
          max-width: 1450px;
        }

        .hr-closing .hr-eyebrow {
          margin-bottom: 42px;
        }

        .hr-closing h2 {
          font-size: clamp(65px, 9vw, 160px);
        }

        .hr-closing > .hr-width > .hr-reveal > p {
          max-width: 1100px;
        }

        .hr-closing__actions {
          margin-top: 65px;
        }

        .hr-footer {
          display: flex;
          align-items: center;
          justify-content: space-between;
          flex-wrap: wrap;
          gap: 20px;
          width: 100%;
          padding: 35px var(--hr-side);
          border-top: 1px solid var(--hr-line);
          color: var(--hr-faint);
          font-size: 9px;
          line-height: 1.8;
          letter-spacing: 0.13em;
        }

        /* ====================================================
           16 / TABLET — FULL SCREEN, WIDER READING COLUMNS
        ==================================================== */

        @media (max-width: 1100px) {
          .hr {
            --hr-side: clamp(26px, 4.5vw, 60px);
          }

          .hr-hero h1 {
            font-size: clamp(53px, 8vw, 100px);
          }

          .hr-principle__analysis {
            grid-template-columns: minmax(0, 1fr);
            gap: 45px;
          }

          .hr-principle__analysis article {
            max-width: 900px;
          }

          .hr-field-navigation {
            grid-template-columns: repeat(3, minmax(0, 1fr));
          }

          .hr-domain__research {
            grid-template-columns: minmax(0, 1fr);
          }

          .hr-research-card {
            min-height: 0;
          }

          .hr-domain__horizon {
            grid-template-columns: minmax(0, 1fr);
          }

          .hr-domain__horizon p {
            margin-top: 15px;
          }

          .hr-evidence__grid {
            grid-template-columns: minmax(0, 1fr);
          }

          .hr-evidence__grid .hr-paper {
            min-height: 0;
          }
        }

        /* ====================================================
           17 / MOBILE — TRUE VIEWPORT-WIDTH EXHIBITIONS

           No horizontal overflow.
           No text clipped to fit a fixed-height screen.
        ==================================================== */

        @media (max-width: 700px) {
          .hr {
            --hr-side: 20px;
            --hr-space: clamp(85px, 12svh, 120px);
          }

          .hr-screen {
            min-height: 100svh;
            min-height: 100dvh;
            align-items: center;
          }

          .hr-background__art {
            width: 170%;
            max-width: none;
            left: -36%;
            opacity: 0.55;
          }

          .hr-topbar {
            padding: 20px var(--hr-side);
          }

          .hr-topbar__identity {
            display: none;
          }

          .hr-home {
            min-height: 42px;
            padding: 10px 15px;
            font-size: 9px;
          }

          .hr-hero__body {
            padding-block: 50px;
          }

          .hr-hero__eyebrow {
            margin-bottom: 30px;
          }

          .hr-hero h1 {
            font-size: clamp(39px, 9.15vw, 65px);
            line-height: 1.075;
            letter-spacing: -0.075em;
          }

          .hr-hero__intro {
            grid-template-columns: minmax(0, 1fr);
            gap: 20px;
            margin-top: 35px;
          }

          .hr-hero__intro p {
            font-size: 15px;
            line-height: 1.8;
          }

          .hr-hero__actions,
          .hr-closing__actions {
            flex-direction: column;
            margin-top: 35px;
          }

          .hr-action {
            width: 100%;
            min-height: 54px;
            font-size: 9px;
          }

          .hr-hero__footer {
            padding-block: 17px 22px;
            font-size: 8px;
            letter-spacing: 0.055em;
          }

          .hr-eyebrow,
          .hr-index,
          .hr-paper__label {
            font-size: 9px;
            letter-spacing: 0.12em;
          }

          .hr-heading {
            margin-bottom: 50px;
          }

          .hr-heading__top {
            gap: 15px;
            margin-bottom: 25px;
          }

          .hr-heading h2,
          .hr-principle h2,
          .hr-fields-intro h2 {
            font-size: clamp(42px, 9.5vw, 68px);
          }

          .hr-heading > p,
          .hr-principle__intro > p,
          .hr-fields-intro > .hr-width > .hr-reveal > p,
          .hr-closing > .hr-width > .hr-reveal > p {
            margin-top: 24px;
            font-size: 16px;
            line-height: 1.8;
          }

          .hr-paper {
            border-radius: 21px;
            -webkit-backdrop-filter: blur(16px);
            backdrop-filter: blur(16px);
          }

          .hr-principle__intro > .hr-eyebrow {
            margin-bottom: 27px;
          }

          .hr-principle__statement {
            margin-top: 45px;
            padding: 27px;
          }

          .hr-principle__formula {
            gap: 10px 14px;
            margin-top: 28px;
            font-size: clamp(21px, 5.7vw, 34px);
          }

          .hr-principle__statement > p {
            margin-top: 25px;
          }

          .hr-principle__analysis {
            margin-top: 65px;
          }

          .hr-principle__analysis h3 {
            margin-top: 19px;
            font-size: 26px;
          }

          .hr-capacity {
            grid-template-columns: minmax(0, 1fr);
            gap: 32px;
            min-height: 0;
            padding: 50px 0;
          }

          .hr-capacity__identity h3 {
            margin-top: 15px;
            font-size: clamp(42px, 10vw, 64px);
          }

          .hr-capacity__content h4 {
            font-size: 26px;
          }

          .hr-capacity__content > p {
            margin-top: 19px;
            font-size: 15px;
          }

          .hr-capacity__evidence {
            margin-top: 28px;
          }

          .hr-field-navigation {
            grid-template-columns: minmax(0, 1fr);
            gap: 10px;
            margin-top: 45px;
          }

          .hr-field-navigation a {
            flex-direction: row;
            align-items: center;
            gap: 16px;
            min-height: 77px;
            padding: 19px;
            border-radius: 17px;
          }

          .hr-field-navigation a > span:nth-child(2) {
            flex: 1;
            font-size: 20px;
          }

          .hr-domain {
            padding-block: 100px;
          }

          .hr-domain__watermark {
            top: 45px;
            right: 0;
            font-size: 230px;
          }

          .hr-domain__heading {
            margin-bottom: 42px;
          }

          .hr-domain__meta {
            gap: 13px;
            margin-bottom: 25px;
          }

          .hr-domain__heading h2 {
            font-size: clamp(56px, 12vw, 90px);
          }

          .hr-domain__question {
            margin-top: 25px;
            font-size: clamp(23px, 5.8vw, 32px);
          }

          .hr-domain__abstract,
          .hr-research-card,
          .hr-domain__horizon {
            padding: 27px;
          }

          .hr-domain__abstract p {
            margin-top: 19px;
            font-size: 17px;
          }

          .hr-domain__research {
            gap: 13px;
            margin-top: 13px;
          }

          .hr-research-card h3 {
            margin-top: 22px;
            font-size: 27px;
          }

          .hr-research-card p {
            margin-top: 18px;
            font-size: 15px;
          }

          .hr-domain__horizon {
            margin-top: 13px;
            gap: 17px;
          }

          .hr-domain__open {
            grid-template-columns: minmax(0, 1fr);
            gap: 20px;
            margin-top: 60px;
          }

          .hr-domain__open p {
            font-size: 24px;
          }

          .hr-conditions__list {
            gap: 13px;
          }

          .hr-condition {
            padding: 27px;
          }

          .hr-condition h3 {
            margin-top: 25px;
            font-size: clamp(27px, 6.6vw, 40px);
          }

          .hr-condition > p {
            margin-top: 24px;
            font-size: 15px;
          }

          .hr-condition__note {
            grid-template-columns: minmax(0, 1fr);
            gap: 12px;
            margin-top: 30px;
          }

          .hr-gate__button {
            grid-template-columns: 35px minmax(0, 1fr) 22px;
            gap: 12px;
            min-height: 110px;
            padding: 25px 0;
          }

          .hr-gate__title strong {
            font-size: 24px;
          }

          .hr-gate__title small {
            margin-top: 8px;
            font-size: 13px;
          }

          .hr-gate__symbol {
            font-size: 25px;
          }

          .hr-gate__body {
            padding: 0 0 30px 47px;
          }

          .hr-gate__body p {
            font-size: 15px;
          }

          .hr-validation__footnote {
            grid-template-columns: minmax(0, 1fr);
            gap: 15px;
            margin-top: 45px;
          }

          .hr-horizon {
            grid-template-columns: minmax(0, 1fr);
            gap: 25px;
            min-height: 0;
            padding: 45px 0;
          }

          .hr-horizon__time {
            gap: 12px;
          }

          .hr-horizon__time > span:last-child {
            font-size: 13px;
          }

          .hr-horizon__body h3 {
            font-size: 29px;
          }

          .hr-horizon__body p {
            margin-top: 18px;
            font-size: 15px;
          }

          .hr-horizons__statement {
            margin-top: 45px;
            padding: 27px;
          }

          .hr-horizons__statement p {
            font-size: 24px;
          }

          .hr-scenario {
            padding: 27px;
          }

          .hr-scenario h3 {
            margin-top: 25px;
            font-size: 37px;
          }

          .hr-scenario__lead {
            font-size: 16px !important;
          }

          .hr-scenario__questions {
            margin-top: 38px;
          }

          .hr-scenario__questions > div {
            grid-template-columns: 27px minmax(0, 1fr);
            gap: 14px;
            padding: 22px 0;
          }

          .hr-scenario__questions p {
            font-size: 19px;
          }

          .hr-scenario__conclusion {
            margin-top: 38px;
            font-size: 23px !important;
          }

          .hr-evidence__grid {
            gap: 13px;
          }

          .hr-evidence__grid .hr-paper {
            padding: 27px;
          }

          .hr-evidence__grid h3 {
            margin-top: 23px;
            font-size: 27px;
          }

          .hr-evidence__grid p {
            margin-top: 18px;
            font-size: 15px;
          }

          .hr-closing h2 {
            font-size: clamp(55px, 12vw, 85px);
          }

          .hr-closing__actions {
            margin-top: 45px;
          }

          .hr-footer {
            padding-block: 26px;
            font-size: 8px;
            letter-spacing: 0.07em;
          }
        }

        /* ====================================================
           18 / SMALL MOBILE
        ==================================================== */

        @media (max-width: 390px) {
          .hr {
            --hr-side: 15px;
          }

          .hr-hero h1 {
            font-size: clamp(36px, 9vw, 43px);
          }

          .hr-hero__intro p {
            font-size: 14px;
          }

          .hr-domain__heading h2 {
            font-size: clamp(49px, 11.5vw, 62px);
          }

          .hr-domain__abstract,
          .hr-research-card,
          .hr-domain__horizon,
          .hr-condition,
          .hr-scenario,
          .hr-evidence__grid .hr-paper {
            padding: 22px;
          }

          .hr-principle__formula {
            font-size: 21px;
          }

          .hr-hero__footer span:last-child {
            display: none;
          }
        }

        /* ====================================================
           19 / SHORT LANDSCAPE SCREENS
        ==================================================== */

        @media (max-height: 650px) and (min-width: 701px) {
          .hr-hero__body {
            padding-block: 35px;
          }

          .hr-hero h1 {
            font-size: clamp(46px, 6.4vw, 92px);
          }

          .hr-hero__intro {
            margin-top: 25px;
          }

          .hr-hero__actions {
            margin-top: 25px;
          }
        }

        /* ====================================================
           20 / MOTION & INTERACTION
        ==================================================== */

        @media (hover: hover) {
          .hr-action:hover {
            transform: translateY(-2px);
          }

          .hr-action--quiet:hover,
          .hr-field-navigation a:hover {
            background: rgba(45, 45, 45, 0.72);
            border-color: rgba(255, 255, 255, 0.3);
          }

          .hr-field-navigation a:hover {
            transform: translateY(-3px);
          }

          .hr-gate__button:hover .hr-gate__title strong {
            color: rgba(242, 242, 242, 0.68);
          }
        }

        @media (prefers-reduced-motion: reduce) {
          html:has(.hr) {
            scroll-behavior: auto;
          }

          .hr *,
          .hr *::before,
          .hr *::after {
            animation: none !important;
            transition: none !important;
          }

          .hr-reveal {
            opacity: 1 !important;
            transform: none !important;
          }
        }
      `}</style>
    </main>
  );
}