name: Update Science & Technology Feeds



on:
    schedule:
        - cron: '0 21 * * *'
    workflow_dispatch:



permissions:
    contents: write



jobs:
    update-feeds:
        runs-on: ubuntu-latest 